[package]
name = "kern"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zerocopy = "0.3.0"
byteorder = {version = "1.3.4", default-features = false}
bitflags = "1.2.1"
