name = "demo"
target = "thumbv7em-none-eabihf"

[kernel]
path = "."
name = "demo-stm32h7"
requires = {flash = 65536, ram = 4096}
#
# For the kernel (and for any task that logs), we are required to enable
# either "itm" (denoting logging/panicking via ARM's Instrumentation Trace
# Macrocell) or "semihosting" (denoting logging/panicking via ARM
# semihosting).  We are biased to ITM because semihosting is excruciatingly
# slow (it is breakpoint based) and has an undesirable failure mode if logging
# output is generated and debugger is not attached (namely, the target stops).
# If one does choose to change this to semihosting for purposes of
# development, be sure to also change it in every task of interest.
#
features = ["itm"]

[supervisor]
notification = 1

[outputs.flash]
address = 0x08000000
size = 262144
read = true
execute = true

[outputs.ram]
address = 0x20000000
size = 114688
read = true
write = true
execute = true

[tasks.jefe]
path = "../task-jefe"
name = "task-jefe"
priority = 0
requires = {flash = 32768, ram = 1024}
start = true
features = ["itm"]

[tasks.rcc_driver]
path = "../drv/stm32h7-rcc"
name = "drv-stm32h7-rcc"
priority = 1
requires = {flash = 8192, ram = 1024}
uses = ["rcc"]
start = true

[tasks.pong]
path = "../task-pong"
name = "task-pong"
features = ["stm32h7"]
priority = 2
requires = {flash = 8192, ram = 1024}
uses = ["gpiog"]
start = true

[tasks.ping]
path = "../task-ping"
name = "task-ping"
features = ["stm32h7"]
priority = 3
requires = {flash = 8192, ram = 512}
uses = ["gpiog"]
start = true

[tasks.idle]
path = "../task-idle"
name = "task-idle"
priority = 4
requires = {flash = 256, ram = 256}
start = true

[peripherals.rcc]
address = 0x58024400
size = 1024

[peripherals.gpiog]
address = 0x58021800
size = 1024

