[package]
name = "drv-user-leds"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib"}
stm32f3 = { version = "0.13.0", features = ["stm32f303"], optional = true }
stm32f4 = { version = "0.13.0", features = ["stm32f407"], optional = true }
lpc55-pac = { version = "0.3.0", optional = true }
zerocopy = "0.3.0"
num-traits = { version = "0.2.12", default-features = false }
drv-stm32h7-gpio-api = {path = "../stm32h7-gpio-api", optional = true}
drv-lpc55-gpio-api = {path = "../lpc55-gpio-api", default-features = false, optional = true}
cfg-if = "0.1.10"

[build-dependencies]
build-util = {path = "../../build/util"}

[features]
default = ["standalone"]
standalone = ["stm32h7"]
stm32h7 = ["drv-stm32h7-gpio-api"]
lpc55 = ["lpc55-pac", "drv-lpc55-gpio-api"]

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-user-leds"
test = false
bench = false
