[package]
name = "drv-user-leds"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib"}
drv-user-leds-api = {path = "../user-leds-api"}
stm32f3 = { version = "0.13.0", features = ["stm32f303"], optional = true }
stm32f4 = { version = "0.13.0", features = ["stm32f407"], optional = true }
lpc55-pac = { version = "0.3.0", optional = true }
zerocopy = "0.6.1"
num-traits = { version = "0.2.12", default-features = false }
drv-stm32xx-sys-api = {path = "../stm32xx-sys-api", optional = true}
drv-lpc55-gpio-api = {path = "../lpc55-gpio-api", optional = true}
cfg-if = "0.1.10"
idol-runtime = {git = "https://github.com/oxidecomputer/idolatry.git"}
drv-rp2040-sys-api = {path = "../rp2040-sys-api", optional = true}

[build-dependencies]
build-util = {path = "../../build/util"}
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

[features]
stm32g0 = ["drv-stm32xx-sys-api/family-stm32g0"]
stm32h7 = ["drv-stm32xx-sys-api/family-stm32h7"]
lpc55 = ["lpc55-pac", "drv-lpc55-gpio-api"]
panic-messages = ["userlib/panic-messages"]
rp2040 = ["drv-rp2040-sys-api"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-user-leds"
test = false
bench = false
