[package]
name = "task-spam"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

[dependencies]
# suppress default features to avoid including panic message collection, to
# ensure the spam task remains tiny.
userlib = {path = "../userlib", default-features = false, features = ["log"]}
cortex-m-semihosting = "0.3.5"
zerocopy = "0.3.0"
lpc55-pac = "0.1.0"
cortex-m = "0.6.3"
defmt = "0.1.0"

[features]
default = [
    "standalone",
    "defmt-trace",
]
standalone = []
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-spam"
test = false
bench = false
