[package]
name = "task-spi"
version = "0.1.0"
authors = ["Laura Abbott <laura@oxide.computer>"]
edition = "2018"

[dependencies]
# suppress default features to avoid including panic message collection, to
# ensure the spi task remains tiny.
userlib = {path = "../userlib", default-features = false}
cortex-m = "0.6.2"
cortex-m-semihosting = { version = "0.3.5", optional = true }
zerocopy = "0.3.0"
cfg-if = "0.1.10"

[build-dependencies]
build-util = {path = "../build-util"}

[features]
default = ["standalone"]
standalone = ["itm"]
itm = [ "userlib/log-itm" ]
semihosting = [ "cortex-m-semihosting", "userlib/log-semihosting" ]

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-spi"
test = false
bench = false
