[package]
name = "drv-sidecar-seq-api"
version = "0.1.0"
edition = "2021"

[dependencies]
idol-runtime.workspace = true
num-traits.workspace = true
zerocopy.workspace = true

derive-idol-err = { path = "../../lib/derive-idol-err"  }
drv-fpga-api = { path = "../fpga-api" }
drv-sidecar-mainboard-controller = { path = "../sidecar-mainboard-controller" }
userlib = { path = "../../sys/userlib" }

[build-dependencies]
idol.workspace = true
