[package]
name = "drv-auxflash-server"
version = "0.1.0"
authors = ["Matt Keeter <matt@oxide.computer>"]
edition = "2021"

[dependencies]
cfg-if = { workspace = true }
idol-runtime = { workspace = true }
num-traits = { workspace = true }
stm32h7 = { workspace = true }
tlvc = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

drv-auxflash-api = { path = "../auxflash-api" }
drv-stm32h7-qspi = { path = "../stm32h7-qspi" }
drv-stm32xx-sys-api = { path = "../stm32xx-sys-api" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
build-util = { path = "../../build/util" }
idol = { workspace = true }

[features]
h753 = ["stm32h7/stm32h753", "drv-stm32xx-sys-api/h753", "drv-stm32h7-qspi/h753"]
no-ipc-counters = ["idol/no-counters"]
gotta-go-fast = [] # runs in quad mode + 66 MHz, instead of single + 40 MHz

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-auxflash-server"
test = false
doctest = false
bench = false

[lints]
workspace = true
