[package]
name = "task-monorail-server"
version = "0.1.0"
edition = "2021"

[dependencies]
drv-medusa-seq-api = { path = "../../drv/medusa-seq-api", optional = true }
drv-front-io-api = { path = "../../drv/front-io-api", optional = true }
drv-monorail-api = { path = "../../drv/monorail-api" }
drv-sidecar-mainboard-controller = { path = "../../drv/sidecar-mainboard-controller" }
drv-sidecar-seq-api = { path = "../../drv/sidecar-seq-api", optional = true }
drv-spi-api = { path = "../../drv/spi-api" }
drv-stm32h7-spi-server-core = { path = "../../drv/stm32h7-spi-server-core", optional = true }
drv-stm32xx-sys-api = { path = "../../drv/stm32xx-sys-api", features = ["family-stm32h7"] }
drv-user-leds-api = { path = "../../drv/user-leds-api", optional = true  }
idol-runtime = { workspace = true }
counters = { path = "../../lib/counters" }
ringbuf = { path = "../../lib/ringbuf"  }
task-net-api = { path = "../net-api", optional = true }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }
vsc7448 = { path = "../../drv/vsc7448"  }
vsc7448-pac = { workspace = true }
vsc85xx = { path = "../../drv/vsc85xx"  }

cfg-if.workspace = true
hubpack.workspace = true
num-traits.workspace = true
serde.workspace = true
zerocopy.workspace = true
zerocopy-derive.workspace = true

[features]
leds = ["drv-user-leds-api"]
medusa = ["drv-medusa-seq-api", "drv-front-io-api"]
mgmt = ["task-net-api"]
sidecar = ["drv-sidecar-seq-api", "drv-front-io-api"]
minibar = []
vlan = ["task-net-api?/vlan"]
no-ipc-counters = ["idol/no-counters"]
use-spi-core = ["drv-stm32h7-spi-server-core"]
h743 = ["drv-stm32h7-spi-server-core?/h743"]
h753 = ["drv-stm32h7-spi-server-core?/h753"]

spi1 = ["drv-stm32h7-spi-server-core?/spi1"]
spi2 = ["drv-stm32h7-spi-server-core?/spi2"]
spi3 = ["drv-stm32h7-spi-server-core?/spi3"]
spi4 = ["drv-stm32h7-spi-server-core?/spi4"]
spi5 = ["drv-stm32h7-spi-server-core?/spi5"]
spi6 = ["drv-stm32h7-spi-server-core?/spi6"]

[build-dependencies]
build-util = {path = "../../build/util"}
idol = { workspace = true }

[[bin]]
name = "task-monorail-server"
test = false
doctest = false
bench = false

[lints]
workspace = true
