[package]
name = "stm32h7-update-server"
version = "0.1.0"
edition = "2021"

[dependencies]
hubpack = { workspace = true }
idol-runtime = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
stm32h7 = { workspace = true, features = ["stm32h753"] }
zerocopy = { workspace = true }

drv-update-api = { path = "../update-api/" }
notifications = { path = "../../lib/notifications", features = ["stm32h7-update-server"] }
ringbuf = { path = "../../lib/ringbuf" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
idol = { workspace = true }
build-util = { path = "../../build/util" }

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "stm32h7-update-server"
test = false
bench = false
