[package]
name = "drv-sprot-api"
version = "0.1.0"
edition = "2021"

[dependencies]
crc = { workspace = true }
derive_more = { workspace = true }
hubpack = { workspace = true }
idol-runtime = { workspace = true }
if_chain = { workspace = true }
memoffset = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
sprockets-common = { workspace = true }
zerocopy = { workspace = true }

derive-idol-err = { path = "../../lib/derive-idol-err" }
drv-spi-api = { path = "../../drv/spi-api" }
drv-update-api = { path = "../../drv/update-api" }
dumper-api = { path = "../../task/dumper-api" }
ringbuf = { path = "../../lib/ringbuf" }
unwrap-lite = { path = "../../lib/unwrap-lite" }
userlib = { path = "../../sys/userlib" }

[build-dependencies]
idol = { workspace = true }

[features]
sink_test = []

