[package]
name = "drv-sprot-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.0"
derive-idol-err = {path = "../../lib/derive-idol-err" }
drv-update-api = {path = "../../drv/update-api"}
if_chain = "1"
memoffset = {version = "0.6.5", default-features = false}
num-traits = { version = "0.2.12", default-features = false }
ringbuf = {path = "../../lib/ringbuf"}
serde = { version = "1.0", default-features = false, features = ["derive"] }
unwrap-lite = { path = "../../lib/unwrap-lite" }
userlib = {path = "../../sys/userlib"}
zerocopy = "0.6.1"
hubpack = { git = "https://github.com/cbiffle/hubpack" }
ssmarshal = {version = "1", default-features = false}

[build-dependencies]
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}


