name = "sidecar"
target = "thumbv7em-none-eabihf"
board = "sidecar-1"
chip = "../../chips/stm32h7-nonredundant"
stacksize = 896
memory = "memory-large.toml"

[kernel]
name = "sidecar"
requires = {flash = 22776, ram = 5424}
#
# For the kernel (and for any task that logs), we are required to enable
# either "itm" (denoting logging/panicking via ARM's Instrumentation Trace
# Macrocell) or "semihosting" (denoting logging/panicking via ARM
# semihosting).  We are biased to ITM because semihosting is excruciatingly
# slow (it is breakpoint based) and has an undesirable failure mode if logging
# output is generated and debugger is not attached (namely, the target stops).
# If one does choose to change this to semihosting for purposes of
# development, be sure to also change it in every task of interest.
#
features = ["itm"]

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536

[tasks.jefe.config.allowed-callers]
set_reset_reason = ["sys"]
request_reset = ["hiffy"]

[tasks.sys]
name = "drv-stm32xx-sys"
features = ["h753"]
priority = 1
max-sizes = {flash = 2048, ram = 1024}
uses = ["rcc", "gpios1", "gpios2", "gpios3"]
start = true
task-slots = ["jefe"]

[tasks.spi1_driver]
name = "drv-stm32h7-spi-server"
priority = 2
max-sizes = {flash = 16384, ram = 2048}
features = ["h753", "spi1"]
uses = ["spi1"]
start = true
interrupts = {"spi1.irq" = 1}
stacksize = 880
task-slots = ["sys"]

[tasks.spi1_driver.config.spi]
global_config = "spi1"

[tasks.spi2_driver]
name = "drv-stm32h7-spi-server"
priority = 2
max-sizes = {flash = 16384, ram = 2048}
features = ["h753", "spi2"]
uses = ["spi2"]
start = true
interrupts = {"spi2.irq" = 1}
stacksize = 880
task-slots = ["sys"]

[tasks.spi2_driver.config.spi]
global_config = "spi2"

[tasks.spi3_driver]
name = "drv-stm32h7-spi-server"
priority = 2
max-sizes = {flash = 16384, ram = 4096}
features = ["h753", "spi3"]
uses = ["spi3"]
start = true
interrupts = {"spi3.irq" = 1}
stacksize = 1000
task-slots = ["sys"]

[tasks.spi3_driver.config.spi]
global_config = "spi3"

[tasks.spi5_driver]
name = "drv-stm32h7-spi-server"
priority = 2
max-sizes = {flash = 16384, ram = 2048}
features = ["h753", "spi5"]
uses = ["spi5"]
start = true
interrupts = {"spi5.irq" = 1}
stacksize = 880
task-slots = ["sys"]

[tasks.spi5_driver.config.spi]
global_config = "spi5"

[tasks.net]
name = "task-net"
stacksize = 4640
priority = 5
features = ["mgmt", "h753", "sidecar", "vlan"]
max-sizes = {flash = 131072, ram = 32768, sram1 = 16384}
sections = {eth_bulk = "sram1"}
uses = ["eth", "eth_dma", "system_flash"]
start = true
interrupts = {"eth.irq" = 0b1}
task-slots = ["sys",
              { spi_driver = "spi3_driver" },
              { seq = "sequencer" }]

[tasks.udpecho]
name = "task-udpecho"
priority = 6
max-sizes = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]

[tasks.udpbroadcast]
name = "task-udpbroadcast"
priority = 6
max-sizes = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]

[tasks.udprpc]
name = "task-udprpc"
priority = 6
max-sizes = {flash = 32768, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]

[tasks.monorail]
name = "task-monorail-server"
priority = 6
max-sizes = {flash = 262144, ram = 8192}
features = ["mgmt", "sidecar", "vlan"]
stacksize = 4096
start = true
task-slots = ["sys", "net", "ecp5_front_io",
              { spi_driver = "spi2_driver" },
              { seq = "sequencer" }]

[tasks.i2c_driver]
name = "drv-stm32h7-i2c-server"
features = ["h753", "itm"]
priority = 2
max-sizes = {flash = 16384, ram = 2048}
uses = ["i2c1", "i2c2", "i2c3", "i2c4"]
start = true
task-slots = ["sys"]

[tasks.i2c_driver.interrupts]
"i2c1.event" = 0b0000_0001
"i2c1.error" = 0b0000_0001
"i2c2.event" = 0b0000_0010
"i2c2.error" = 0b0000_0010
"i2c3.event" = 0b0000_0100
"i2c3.error" = 0b0000_0100
"i2c4.event" = 0b0000_1000
"i2c4.error" = 0b0000_1000

[tasks.hiffy]
name = "task-hiffy"
features = ["h753", "spi", "stm32h7", "itm", "i2c", "gpio"]
priority = 5
max-sizes = {flash = 32768, ram = 16384 }
stacksize = 1024
start = true
task-slots = ["sys", "i2c_driver"]

[tasks.sensor]
name = "task-sensor"
features = ["itm"]
priority = 4
max-sizes = {flash = 8192, ram = 2048 }
stacksize = 1920        # Sensor data is stored on the stack
start = true

[tasks.ecp5_mainboard]
name = "drv-fpga-server"
features = ["mainboard"]
priority = 3
max-sizes = {flash = 32768, ram = 4096}
stacksize = 2048
start = true
task-slots = ["sys", {spi_driver = "spi5_driver"}]

[tasks.ecp5_front_io]
name = "drv-fpga-server"
features = ["front_io"]
priority = 3
max-sizes = {flash = 32768, ram = 4096}
stacksize = 2048
start = true
task-slots = ["sys", "i2c_driver", {spi_driver = "spi1_driver"}]

[tasks.sequencer]
name = "drv-sidecar-seq-server"
features = []
priority = 4
stacksize = 1024
start = true
task-slots = [
    "sys",
    "i2c_driver",
    {mainboard = "ecp5_mainboard"},
    {front_io = "ecp5_front_io"}]

[tasks.thermal]
name = "task-thermal"
features = ["itm", "sidecar"]
priority = 5
max-sizes = {flash = 32768, ram = 8192 }
stacksize = 4504
start = true
task-slots = ["i2c_driver", "sensor", "sequencer"]

[tasks.power]
name = "task-power"
features = ["itm", "sidecar"]
priority = 6
max-sizes = {flash = 16384, ram = 4096 }
stacksize = 2048
start = true
task-slots = ["i2c_driver", "sensor", "sequencer"]

[tasks.validate]
name = "task-validate"
priority = 5
max-sizes = {flash = 16384, ram = 4096 }
stacksize = 1000
start = true
task-slots = ["i2c_driver"]

[tasks.idle]
name = "task-idle"
priority = 7
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[config]

#
# I2C1: Northeast corridors
#
[[config.i2c.controllers]]
controller = 1

#
# I2C_NORTH_EAST0_SCL
# I2C_NORTH_EAST0_SDA
#
[config.i2c.controllers.ports.B1]
name = "northeast0"
description = "Northeast Corridor 0"
pins = [ { gpio_port = "B", pins = [ 6, 7 ], af = 4 } ]
muxes = [ { driver = "pca9548", address = 0x70 } ]

#
# I2C_NORTH_EAST1_SCL
# I2C_NORTH_EAST1_SDA
#
[config.i2c.controllers.ports.B2]
name = "northeast1"
description = "Northeast Corridor 1"
pins = [ { gpio_port = "B", pins = [ 8, 9 ], af = 4 } ]

#
# I2C2: Front I/O
#
[[config.i2c.controllers]]
controller = 2

#
# I2C_FRONT_IO0_SCL
# I2C_FRONT_IO0_SDA
#
[config.i2c.controllers.ports.F]
name = "front_io"
description = "Front I/O Board"
pins = [ { pins = [ 0, 1 ], af = 4 } ]

#
# I2C_FRONT_IO1_SCL
# I2C_FRONT_IO1_SDA
#
[config.i2c.controllers.ports.H]
name = "frontgps"
description = "Front I/O GPS"
pins = [ { pins = [ 4, 5 ], af = 4 } ]

#
# I2C3: Northwest corridors
#
[[config.i2c.controllers]]
controller = 3

#
# I2C_NORTH_WEST0_SCL
# I2C_NORTH_WEST0_SDL
#
[config.i2c.controllers.ports.C]
name = "northwest0"
description = "Northwest Corridor 0"

[[config.i2c.controllers.ports.C.pins]]
gpio_port = "A"
pins = [ 8 ]
af = 4

[[config.i2c.controllers.ports.C.pins]]
gpio_port = "C"
pins = [ 9 ]
af = 4

#
# I2C_NORTH_WEST1_SCL
# I2C_NORTH_WEST1_SDL
#
[config.i2c.controllers.ports.H]
name = "northwest1"
description = "Northwest Corridor 1"
pins = [ { pins = [ 7, 8 ], af = 4 } ]
muxes = [ { driver = "pca9548", address = 0x70 } ]

#
# I2C4: South bend
#
[[config.i2c.controllers]]
controller = 4

#
# I2C_SOUTH0_SCL
# I2C_SOUTH0_SDA
#
[config.i2c.controllers.ports.F]
name = "south0"
description = "South Bend 0"
pins = [ { pins = [ 14, 15 ], af = 4 } ]

#
# I2C_SOUTH1_SCL
# I2C_SOUTH1_SDA
#
[config.i2c.controllers.ports.H]
name = "south1"
description = "South Bend 1"
pins = [ { pins = [ 11, 12 ], af = 4 } ]

#
# I2C_SOUTH2_SCL
# I2C_SOUTH2_SDA
#
[config.i2c.controllers.ports.D]
name = "south2"
description = "South Bend 2"
pins = [ { pins = [ 12, 13 ], af = 4 } ]

[[config.i2c.devices]]
bus = "northeast0"
address = 0b0010_000
device = "adm1272"
description = "Fan 1 hot swap controller"
pmbus = { rails = [ "V54_FAN1" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U6"

[[config.i2c.devices]]
bus = "northeast0"
address = 0b0100_011
device = "max31790"
name = "East"
description = "Fan 0/1 controller"
sensors = { speed = 4 }
refdes = "U66"

[[config.i2c.devices]]
bus = "northeast0"
address = 0b1001_001
device = "tmp117"
name = "NNE"
description = "North-northeast temperature sensor"
sensors = { temperature = 1 }
refdes = "J69"
removable = true

[[config.i2c.devices]]
bus = "northeast0"
address = 0b1100_011
device = "raa229618"
description = "TF2 VDD rail"
pmbus = { rails = [ "V0P8_TF2_VDD_CORE" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U31"

[[config.i2c.devices]]
bus = "northeast0"
address = 0b1110_000
device = "pca9545"
description = "Northeast fan mux"
refdes = "U92"

[[config.i2c.devices]]
bus = "northeast1"
address = 0b0010_011
device = "adm1272"
description = "Fan 0 hot swap controller"
pmbus = { rails = [ "V54_FAN0" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U4"

[[config.i2c.devices]]
bus = "northeast1"
address = 0b0011_010
device = "tps546b24a"
description = "V3P3_SYS rail"
pmbus = { rails = [ "V3P3_SYS" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U19"

[[config.i2c.devices]]
bus = "northeast1"
address = 0b1001_000
device = "tmp117"
name = "Northeast"
description = "Northeast temperature sensor"
sensors = { temperature = 1 }
refdes = "J70"
removable = true

[[config.i2c.devices]]
bus = "northwest0"
address = 0b0010_110
device = "adm1272"
description = "54V hot swap controller"
pmbus = { rails = [ "V54_HSC" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U2"

[[config.i2c.devices]]
bus = "northwest0"
address = 0b0011_001
device = "tps546b24a"
description = "V5P0_SYS rail"
pmbus = { rails = [ "V5P0_SYS" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U18"

[[config.i2c.devices]]
bus = "northwest0"
address = 0b1001_000
device = "tmp117"
name = "NNW"
description = "North-northwest temperature sensor"
sensors = { temperature = 1 }
refdes = "J68"
removable = true

[[config.i2c.devices]]
bus = "northwest0"
address = 0b1001_100
device = "tmp451"
name = "tf2"
description = "TF2 temperature sensor"
sensors = { temperature = 1 }
refdes = "U64"

[[config.i2c.devices]]
bus = "northwest0"
address = 0b1100_000
device = "raa229618"
description = "TF2 VDDA rail"
pmbus = { rails = [ "V1P5_TF2_VDDA", "V0P9_TF2_VDDT" ] }
sensors = { temperature = 2, voltage = 2, current = 2 }
refdes = "U32"

[[config.i2c.devices]]
bus = "northwest0"
address = 0b1100_111
device = "bmr491"
name = "IBC"
description = "Intermediate bus converter"
pmbus = { rails = [ "V12P0_SYS" ] }
sensors = { temperature = 1, power = 1, voltage = 1, current = 1 }
refdes = "U12"

[[config.i2c.devices]]
bus = "northwest1"
address = 0b0010_011
device = "adm1272"
description = "Fan 2 hot swap controller"
pmbus = { rails = [ "V54_FAN2" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U8"

[[config.i2c.devices]]
bus = "northwest1"
address = 0b0010_000
device = "adm1272"
description = "Fan 3 hot swap controller"
pmbus = { rails = [ "V54_FAN3" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U10"

[[config.i2c.devices]]
bus = "northwest1"
address = 0b1001_001
device = "tmp117"
name = "Northwest"
description = "Northwest temperature sensor"
sensors = { temperature = 1 }
refdes = "J67"
removable = true

[[config.i2c.devices]]
bus = "northwest1"
address = 0b0100_000
device = "max31790"
name = "West"
description = "Fan 2/3 controller"
sensors = { speed = 4 }
refdes = "U78"

[[config.i2c.devices]]
bus = "northwest1"
address = 0b1110_000
device = "pca9545"
description = "Northwest fan mux"
refdes = "U90"

#
# U29: DNI ADM1272
#

[[config.i2c.devices]]
bus = "south0"
address = 0b1100_010
device = "isl68224"
description = "VDD[A]18 rail"
pmbus = { rails = [ "V1P8_TF2_VDDA", "V1P8_TF2_VDD" ] }
sensors = { temperature = 2, voltage = 2, current = 2 }
refdes = "U33"

[[config.i2c.devices]]
bus = "south0"
address = 0b1011_000
device = "idt8a34001"
description = "Clock generator"
refdes = "U38"

[[config.i2c.devices]]
bus = "south0"
address = 0b1001_010
device = "tmp117"
name = "South"
description = "South temperature sensor"
sensors = { temperature = 1 }
refdes = "J71"
removable = true

[[config.i2c.devices]]
bus = "south0"
address = 0b1001_000
device = "tmp117"
name = "Southeast"
description = "Southeast temperature sensor"
sensors = { temperature = 1 }
refdes = "J73"
removable = true

[[config.i2c.devices]]
bus = "south0"
address = 0b1001_001
device = "tmp117"
name = "Southwest"
description = "Southwest temperature sensor"
sensors = { temperature = 1 }
refdes = "J72"
removable = true

[[config.i2c.devices]]
bus = "south1"
address = 0b0011_011
device = "tps546b24a"
description = "V1P0_SYS rail"
pmbus = { rails = [ "V1P0_MGMT" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U21"

[[config.i2c.devices]]
bus = "south1"
address = 0b0011_100
device = "tps546b24a"
description = "V1P8_SYS rail"
pmbus = { rails = [ "V1P8_SYS" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U20"

[[config.i2c.devices]]
bus = "south1"
address = 0b1001_100
device = "tmp451"
name = "vsc7448"
description = "VSC7448 temperature sensor"
sensors = { temperature = 1 }
refdes = "U65"

# [[config.i2c.devices]]
# bus = "south1"
# address = ??
# device = "ecp5"
# refdes = "U43"

# [[config.i2c.devices]]
# device = "at24csw080"
# bus = "northeast0"
# address = 0b1010_0**
# description = ""

# [[config.i2c.devices]]
# bus = "northwest1"
# address = 0b1010_0**
# device = "at24csw080"
# description = ""

[[config.i2c.devices]]
bus = "south2"
address = 0b1010_000
device = "at24csw080"
description = "Mainboard FRUID"
refdes = "U91"

# [[config.i2c.devices]]
# device = "tf2"
# bus = "ECP5->S?"
# address = 0b1011_011
# description = ""

[[config.i2c.devices]]
bus = "front_io"
address = 0b1010_000
device = "at24csw080"
description = "Front IO board FRUID"
removable = true

[[config.i2c.devices]]
bus = "front_io"
address = 0b1110_011
device = "pca9538"
description = "Front IO GPIO expander"
removable = true

[config.spi.spi1]
controller = 1

[config.spi.spi1.mux_options.port_adg]
outputs = [
    {port = "A", pins = [5], af = 5}, # FRONT_IO_SCK
    {port = "D", pins = [7], af = 5}, # FRONT_IO_COPI
]
input = {port = "G", pin = 9, af = 5} # FRONT_IO_CIPO

[config.spi.spi1.devices.ecp5_front_io_fpga]
mux = "port_adg"
cs = [{port = "G", pin = 10}] # FRONT_IO_CS0

[config.spi.spi1.devices.ecp5_front_io_user_design]
mux = "port_adg"
cs = [{port = "A", pin = 15}] # FRONT_IO_CS1

[config.spi.spi2]
controller = 2

[config.spi.spi2.mux_options.port_i]
outputs = [
    {port = "I", pins = [1, 3], af = 5},
]
input = {port = "I", pin = 2, af = 5}

[config.spi.spi2.devices.vsc7448]
mux = "port_i"
cs = [{port = "I", pin = 0}]

[config.spi.spi3]
controller = 3

[config.spi.spi3.mux_options.port_c]
outputs = [
    {port = "C", pins = [10, 12], af = 6},
]
input = {port = "C", pin = 11, af = 6}

[config.spi.spi3.devices.ksz8463]
mux = "port_c"
cs = [{port = "A", pin = 4}, {port = "B", pin = 13}]


[config.spi.spi5]
controller = 5

[config.spi.spi5.mux_options.port_jk]
outputs = [
    {port = "J", pins = [10], af = 5},
    {port = "K", pins = [0], af = 5},
]
input = {port = "J", pin = 11, af = 5}

[config.spi.spi5.devices.ecp5_mainboard_fpga]
mux = "port_jk"
cs = [{port = "K", pin = 1}]

[config.spi.spi5.devices.ecp5_mainboard_user_design]
mux = "port_jk"
cs = [{port = "J", pin = 6}]

[config.net]
vlan = { start = 0x301, count = 2 }

[config.net.sockets.echo]
kind = "udp"
owner = {name = "udpecho", notification = 1}
port = 7
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.broadcast]
kind = "udp"
owner = {name = "udpbroadcast", notification = 1}
port = 997
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.rpc]
kind = "udp"
owner = {name = "udprpc", notification = 1}
port = 998
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }
