[package]
name = "drv-i2c-devices"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib"}
ringbuf = {path = "../../lib/ringbuf" }
zerocopy = "0.3.0"
num-traits = { version = "0.2.12", default-features = false }
drv-onewire = {path = "../onewire"}
drv-i2c-api = {path = "../i2c-api"}
pmbus = { git = "https://github.com/oxidecomputer/pmbus" }
bitfield = "0.13"

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
bench = false
