[package]
name = "drv-caboose"
version = "0.1.0"
edition = "2021"

[dependencies]
hubpack.workspace = true
num-traits.workspace = true
tlvc.workspace = true

counters = { path = "../../lib/counters" }
derive-idol-err.path = "../../lib/derive-idol-err"
userlib.path = "../../sys/userlib"

[lib]
test = false
doctest = false
bench = false

[lints]
workspace = true
