[package]
name = "task-spd"
version = "0.1.0"
authors = ["Bryan Cantrill <bryan@oxide.computer>"]
edition = "2018"

[dependencies]
userlib = {path = "../sys/userlib"}
ringbuf = {path = "../ringbuf"}
spd = {path = "../spd" }
num-traits = { version = "0.2.12", default-features = false }
drv-stm32h7-gpio-api = {path = "../drv/stm32h7-gpio-api", default-features = false}
drv-stm32h7-rcc-api = {path = "../drv/stm32h7-rcc-api", default-features = false}
drv-stm32h7-i2c = {path = "../drv/stm32h7-i2c", default-features = false}
drv-i2c-api = {path = "../drv/i2c-api", default-features = false}
cortex-m-semihosting = "0.3.5"
cortex-m = { version = "0.7", features = ["inline-asm"] }
cfg-if = "0.1.10"
stm32h7 = { version = "0.13.0", default-features = false }

[build-dependencies]
build-util = {path = "../build/util"}
build-i2c = {path = "../build/i2c"}
anyhow = "1.0.31"
cfg-if = "0.1.10"

[features]
default = ["standalone"]
standalone = [ "h753", "itm" ]
h743 = ["stm32h7/stm32h743", "drv-stm32h7-i2c/h743", "drv-stm32h7-rcc-api/h743", "build-i2c/h743"]
h753 = ["stm32h7/stm32h753", "drv-stm32h7-i2c/h753", "drv-stm32h7-rcc-api/h753", "build-i2c/h753"]
h7b3 = ["stm32h7/stm32h7b3", "drv-stm32h7-i2c/h7b3", "drv-stm32h7-rcc-api/h7b3", "build-i2c/h7b3"]
itm = [ "userlib/log-itm" ]

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-spd"
test = false
bench = false

