[package]
name = "drv-lpc55-usart"
version = "0.1.0"
edition = "2021"

[dependencies]
lpc55-pac = { workspace = true }
nb = { workspace = true }
zerocopy = { workspace = true }

drv-lpc55-gpio-api = { path = "../lpc55-gpio-api" }
drv-lpc55-syscon-api = { path = "../lpc55-syscon-api" }
lib-lpc55-usart = { path = "../../lib/lpc55-usart" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
anyhow = { workspace = true }
serde = { workspace = true }

build-lpc55pins = { path = "../../build/lpc55pins" }
build-util = { path = "../../build/util" }

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-lpc55-usart"
test = false
bench = false
