name = "psc-b"
target = "thumbv7em-none-eabihf"
board = "psc-b"
chip = "../../chips/stm32h7"
memory = "memory-large.toml"
stacksize = 896

[kernel]
name = "psc"
requires = {flash = 32768, ram = 4800}

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536

[tasks.jefe.config.allowed-callers]
set_reset_reason = ["sys"]
request_reset = ["hiffy", "control_plane_agent"]

[tasks.sys]
name = "drv-stm32xx-sys"
features = ["h753"]
priority = 1
max-sizes = {flash = 2048, ram = 1024}
uses = ["rcc", "gpios1", "gpios2", "gpios3"]
start = true
task-slots = ["jefe"]

[tasks.spi4_driver]
name = "drv-stm32h7-spi-server"
priority = 2
max-sizes = {flash = 16384, ram = 2048}
features = ["spi4", "h753"]
uses = ["spi4"]
start = true
interrupts = {"spi4.irq" = 1}
stacksize = 872
task-slots = ["sys"]

[tasks.spi4_driver.config.spi]
global_config = "spi4"

[tasks.spi2_driver]
name = "drv-stm32h7-spi-server"
priority = 2
max-sizes = {flash = 16384, ram = 2048}
features = ["spi2", "h753"]
uses = ["spi2"]
start = true
interrupts = {"spi2.irq" = 1}
stacksize = 872
task-slots = ["sys"]

[tasks.spi2_driver.config.spi]
global_config = "spi2"

[tasks.i2c_driver]
name = "drv-stm32xx-i2c-server"
features = ["h753", "itm"]
priority = 2
max-sizes = {flash = 16384, ram = 2048}
uses = ["i2c2", "i2c3"]
start = true
task-slots = ["sys"]

[tasks.i2c_driver.interrupts]
"i2c2.event" = 0b0000_0010
"i2c2.error" = 0b0000_0010
"i2c3.event" = 0b0000_0100
"i2c3.error" = 0b0000_0100

[tasks.update_server]
name = "stm32h7-update-server"
priority = 2
max-sizes = {flash = 16384, ram = 4096}
stacksize = 2048
start = true
uses = ["flash_controller", "bank2"]
interrupts = {"flash_controller.irq" = 0b1}

[tasks.hiffy]
name = "task-hiffy"
features = ["h753", "stm32h7", "itm", "i2c", "gpio", "spi", "sprot"]
priority = 5
max-sizes = {flash = 32768, ram = 16384 }
stacksize = 1024
start = true
task-slots = ["sys", "i2c_driver", "sprot"]

[tasks.validate]
name = "task-validate"
priority = 3
max-sizes = {flash = 16384, ram = 4096 }
stacksize = 1000
start = true
task-slots = ["i2c_driver"]

[tasks.net]
name = "task-net"
stacksize = 6040
priority = 3
features = ["mgmt", "h753", "vlan", "vpd-mac"]
max-sizes = {flash = 131072, ram = 32768, sram1 = 16384}
sections = {eth_bulk = "sram1"}
uses = ["eth", "eth_dma", "system_flash", "tim16"]
start = true
interrupts = {"eth.irq" = 0b1, "tim16.irq" = 0b10}
task-slots = ["sys", "i2c_driver", { spi_driver = "spi2_driver" }]

[tasks.control_plane_agent]
name = "task-control-plane-agent"
priority = 4
max-sizes = {flash = 65536, ram = 16384}
stacksize = 4096
start = true
uses = [
    "system_flash", # TODO also used by `net`, both to read the stm32 uid
]
task-slots = [
    "jefe",
    "net",
    "update_server",
    "sys",
    "validate",
    "sensor",
    "sprot",
]
features = ["psc", "vlan"]

[tasks.sprot]
name = "drv-stm32h7-sprot-server"
priority = 3
max-sizes = {flash = 32768, ram = 32768}
stacksize = 16384
start = true
task-slots = ["sys", {spi_driver = "spi4_driver"}]
features = ["sink_test"]

[tasks.udpecho]
name = "task-udpecho"
priority = 4
max-sizes = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]

[tasks.udpbroadcast]
name = "task-udpbroadcast"
priority = 4
max-sizes = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]

[tasks.udprpc]
name = "task-udprpc"
priority = 4
max-sizes = {flash = 32768, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]

[tasks.eeprom]
name = "drv-eeprom"
priority = 3
max-sizes = {flash = 2048, ram = 256}
stacksize = 256
start = true
task-slots = ["i2c_driver"]

[tasks.power]
name = "task-power"
priority = 4
max-sizes = {flash = 32768, ram = 4096}
stacksize = 1000
start = true
task-slots = ["i2c_driver", "sensor", "sys"]
features = ["psc"]

[tasks.sensor]
name = "task-sensor"
priority = 3
max-sizes = {flash = 8192, ram = 4096 }
stacksize = 1024
start = true

[tasks.sensor_polling]
name = "task-sensor-polling"
priority = 4
max-sizes = {flash = 16384, ram = 2048 }
start = true
task-slots = ["i2c_driver", "sensor"]

[tasks.idle]
name = "task-idle"
priority = 6
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[config]
#
# I2C2: Local bus
#
[[config.i2c.controllers]]
controller = 2

#
# I2C_SP_TO_LOCAL_SDA
# I2C_SP_TO_LOCAL_SCL
#
[config.i2c.controllers.ports.F]
name = "local"
description = "Local bus"
pins = [ { pins = [ 0, 1 ], af = 4 } ]

#
# I2C3: Backplane bus
#
[[config.i2c.controllers]]
controller = 3

#
# I2C_SP_TO_PS_SCL
# I2C_SP_TO_PS_SDA
#
[config.i2c.controllers.ports.H]
name = "backplane"
description = "Backplane bus"
pins = [ { pins = [ 7, 8 ], af = 4 } ]

[[config.i2c.devices]]
bus = "local"
address = 0b1001_000
device = "tmp116"
description = "Temperature sensor"

[[config.i2c.devices]]
bus = "local"
address = 0b1010_000
device = "at24csw080"
name = "local_vpd"
description = "FRU ID EEPROM"

# NOTE: the schematic labels the PSUs as 1-6 (matching Murata's numbering
# scheme), but they are 0-indexed in user-facing markings (RFD 200)
[[config.i2c.devices]]
bus = "backplane"
name = "psu0eeprom"
address = 0b1010_000
device = "m24c02"
description = "PSU 0 EEPROM"

[[config.i2c.devices]]
bus = "backplane"
name = "psu0mcu"
address = 0b1011_000
device = "mwocp68"
description = "PSU 0 MCU"
power = { rails = [ "V54_PSU0", "V12_PSU0" ], sensors = ["voltage", "current", "input-voltage", "input-current"] }
sensors = { input-voltage = 2, input-current = 2, voltage = 2, current = 2, temperature = 3, speed = 2 }

[[config.i2c.devices]]
bus = "backplane"
name = "psu1eeprom"
address = 0b1010_001
device = "m24c02"
description = "PSU 1 EEPROM"

[[config.i2c.devices]]
bus = "backplane"
name = "psu1mcu"
address = 0b1011_001
device = "mwocp68"
description = "PSU 1 MCU"
power = { rails = [ "V54_PSU1", "V12_PSU1" ], sensors = ["voltage", "current", "input-voltage", "input-current"] }
sensors = { input-voltage = 2, input-current = 2, voltage = 2, current = 2, temperature = 3, speed = 2 }

[[config.i2c.devices]]
bus = "backplane"
name = "psu2eeprom"
address = 0b1010_010
device = "m24c02"
description = "PSU 2 EEPROM"

[[config.i2c.devices]]
bus = "backplane"
name = "psu2mcu"
address = 0b1011_010
device = "mwocp68"
description = "PSU 2 MCU"
power = { rails = [ "V54_PSU2", "V12_PSU2" ], sensors = ["voltage", "current", "input-voltage", "input-current"] }
sensors = { input-voltage = 2, input-current = 2, voltage = 2, current = 2, temperature = 3, speed = 2 }

[[config.i2c.devices]]
bus = "backplane"
name = "psu3eeprom"
address = 0b1010_011
device = "m24c02"
description = "PSU 3 EEPROM"

[[config.i2c.devices]]
bus = "backplane"
name = "psu3mcu"
address = 0b1011_011
device = "mwocp68"
description = "PSU 3 MCU"
power = { rails = [ "V54_PSU3", "V12_PSU3" ], sensors = ["voltage", "current", "input-voltage", "input-current"] }
sensors = { input-voltage = 2, input-current = 2, voltage = 2, current = 2, temperature = 3, speed = 2 }

[[config.i2c.devices]]
bus = "backplane"
name = "psu4eeprom"
address = 0b1010_100
device = "m24c02"
description = "PSU 4 EEPROM"

[[config.i2c.devices]]
bus = "backplane"
name = "psu4mcu"
address = 0b1011_100
device = "mwocp68"
description = "PSU 4 MCU"
power = { rails = [ "V54_PSU4", "V12_PSU4" ], sensors = ["voltage", "current", "input-voltage", "input-current"] }
sensors = { input-voltage = 2, input-current = 2, voltage = 2, current = 2, temperature = 3, speed = 2 }

[[config.i2c.devices]]
bus = "backplane"
name = "psu5eeprom"
address = 0b1010_101
device = "m24c02"
description = "PSU 5 EEPROM"

[[config.i2c.devices]]
bus = "backplane"
name = "psu5mcu"
address = 0b1011_101
device = "mwocp68"
description = "PSU 5 MCU"
power = { rails = [ "V54_PSU5", "V12_PSU5" ], sensors = ["voltage", "current", "input-voltage", "input-current"] }
sensors = { input-voltage = 2, input-current = 2, voltage = 2, current = 2, temperature = 3, speed = 2 }

[config.spi.spi2]
controller = 2

[config.spi.spi2.mux_options.port_i]
outputs = [
    {port = "I", pins = [1, 3], af = 5},
]
input = {port = "I", pin = 2, af = 5}

[config.spi.spi2.devices.ksz8463]
mux = "port_i"
cs = [{port = "I", pin = 0}]

[config.spi.spi4]
controller = 4

[config.spi.spi4.mux_options.rot]
outputs = [
    {port = "E", pins = [2, 6], af = 5},
]
input = {port = "E", pin = 5, af = 5}

[config.spi.spi4.devices.rot]
mux = "rot"
cs = [{port = "E", pin = 4}]
clock_divider = "DIV256"

[config.net]
vlan = { start = 0x301, count = 2 }

[config.net.sockets.echo]
kind = "udp"
owner = {name = "udpecho", notification = 1}
port = 7
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.broadcast]
kind = "udp"
owner = {name = "udpbroadcast", notification = 1}
port = 997
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.rpc]
kind = "udp"
owner = {name = "udprpc", notification = 1}
port = 998
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.control_plane_agent]
kind = "udp"
owner = {name = "control_plane_agent", notification = 0b01}
port = 11111 # TODO do we have a documented port for MGS traffic?
tx = { packets = 3, bytes = 2048 }
rx = { packets = 3, bytes = 2048 }
