name = "psc-a"
target = "thumbv7em-none-eabihf"
board = "psc-a"
chip = "../../chips/stm32h7"
stacksize = 896

[kernel]
name = "psc"
requires = {flash = 32768, ram = 4096}
#
# For the kernel (and for any task that logs), we are required to enable
# either "itm" (denoting logging/panicking via ARM's Instrumentation Trace
# Macrocell) or "semihosting" (denoting logging/panicking via ARM
# semihosting).  We are biased to ITM because semihosting is excruciatingly
# slow (it is breakpoint based) and has an undesirable failure mode if logging
# output is generated and debugger is not attached (namely, the target stops).
# If one does choose to change this to semihosting for purposes of
# development, be sure to also change it in every task of interest.
#
features = ["itm"]

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536

[tasks.jefe.config.allowed-callers]
set_reset_reason = ["sys"]
request_reset = ["hiffy"]

[tasks.sys]
name = "drv-stm32xx-sys"
features = ["h753"]
priority = 1
max-sizes = {flash = 2048, ram = 1024}
uses = ["rcc", "gpios1", "gpios2", "gpios3"]
start = true
task-slots = ["jefe"]

[tasks.spi4_driver]
name = "drv-stm32h7-spi-server"
priority = 2
max-sizes = {flash = 16384, ram = 2048}
features = ["spi4", "h753"]
uses = ["spi4"]
start = true
interrupts = {"spi4.irq" = 1}
stacksize = 872
task-slots = ["sys"]

[tasks.spi4_driver.config.spi]
global_config = "spi4"

[tasks.spi2_driver]
name = "drv-stm32h7-spi-server"
priority = 2
max-sizes = {flash = 16384, ram = 2048}
features = ["spi2", "h753"]
uses = ["spi2"]
start = true
interrupts = {"spi2.irq" = 1}
stacksize = 872
task-slots = ["sys"]

[tasks.spi2_driver.config.spi]
global_config = "spi2"

[tasks.i2c_driver]
name = "drv-stm32xx-i2c-server"
features = ["h753", "itm"]
priority = 2
max-sizes = {flash = 16384, ram = 2048}
uses = ["i2c2", "i2c3", "i2c4"]
start = true
task-slots = ["sys"]

[tasks.i2c_driver.interrupts]
"i2c2.event" = 0b0000_0010
"i2c2.error" = 0b0000_0010
"i2c3.event" = 0b0000_0100
"i2c3.error" = 0b0000_0100
"i2c4.event" = 0b0000_1000
"i2c4.error" = 0b0000_1000

[tasks.update_server]
name = "stm32h7-update-server"
priority = 2
max-sizes = {flash = 16384, ram = 4096}
stacksize = 2048
start = true
uses = ["flash_controller", "bank2"]
interrupts = {"flash_controller.irq" = 0b1}

[tasks.hiffy]
name = "task-hiffy"
features = ["h753", "stm32h7", "itm", "i2c", "gpio", "spi"]
priority = 3
max-sizes = {flash = 32768, ram = 16384 }
stacksize = 1024
start = true
task-slots = ["sys", "i2c_driver"]

[tasks.net]
name = "task-net"
stacksize = 4640
priority = 3
features = ["mgmt", "h753", "vlan"]
max-sizes = {flash = 131072, ram = 32768, sram1 = 16384}
sections = {eth_bulk = "sram1"}
uses = ["eth", "eth_dma", "system_flash"]
start = true
interrupts = {"eth.irq" = 0b1}
task-slots = ["sys", { spi_driver = "spi2_driver" }]

[tasks.mgmt_gateway]
name = "task-mgmt-gateway"
priority = 4
max-sizes = {flash = 32768, ram = 8192}
stacksize = 1536
start = true
uses = [
    "system_flash", # TODO also used by `net`, both to read the stm32 uid
]
task-slots = ["jefe", "net", "update_server", "sys"]
features = ["psc", "vlan"]

[tasks.udpecho]
name = "task-udpecho"
priority = 4
max-sizes = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]

[tasks.udpbroadcast]
name = "task-udpbroadcast"
priority = 4
max-sizes = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]

[tasks.udprpc]
name = "task-udprpc"
priority = 4
max-sizes = {flash = 32768, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]

[tasks.eeprom]
name = "drv-eeprom"
priority = 3
max-sizes = {flash = 2048, ram = 256}
stacksize = 256
start = true
task-slots = ["i2c_driver"]

[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[config]
#
# I2C2: Local bus
#
[[config.i2c.controllers]]
controller = 2

#
# SP_I2C_LOCAL_SDA
# SP_I2C_LOCAL_SCL
#
[config.i2c.controllers.ports.F]
name = "local"
description = "Local bus"
pins = [ { pins = [ 0, 1 ], af = 4 } ]

#
# I2C3: Backplane bus
#
[[config.i2c.controllers]]
controller = 3

#
# SP_TO_PS_I2C_BP_SCL
# SP_TO_PS_I2C_BP_SDA
#
[config.i2c.controllers.ports.H]
name = "backplane"
description = "Backplane bus"
pins = [ { pins = [ 7, 8 ], af = 4 } ]

#
# I2C4: Status bus
#
[[config.i2c.controllers]]
controller = 4

#
# I2C_SP_TO_STATUS_SCL
# I2C_SP_TO_STATUS_SDA
#
[config.i2c.controllers.ports.B]
name = "status"
description = "Status bus"
pins = [ { pins = [ 8, 9 ], af = 6 } ]

[[config.i2c.devices]]
bus = "local"
address = 0b1000_001
device = "ina226"
description = "Current sensor"

[[config.i2c.devices]]
bus = "local"
address = 0b1001_000
device = "tmp116"
description = "Temperature sensor"

[[config.i2c.devices]]
bus = "local"
address = 0b1010_000
device = "at24csw080"
description = "FRU ID EEPROM"

[[config.i2c.devices]]
bus = "backplane"
name = "psu1eeprom"
address = 0b1010_000
device = "psueeprom"
description = "PSU 1 EEPROM"

[[config.i2c.devices]]
bus = "backplane"
name = "psu1mcu"
address = 0b1011_000
device = "psumcu"
description = "PSU 1 MCU"

[[config.i2c.devices]]
bus = "backplane"
name = "psu2eeprom"
address = 0b1010_001
device = "psueeprom"
description = "PSU 2 EEPROM"

[[config.i2c.devices]]
bus = "backplane"
name = "psu2mcu"
address = 0b1011_001
device = "psumcu"
description = "PSU 2 MCU"

[[config.i2c.devices]]
bus = "backplane"
name = "psu3eeprom"
address = 0b1010_010
device = "psueeprom"
description = "PSU 3 EEPROM"

[[config.i2c.devices]]
bus = "backplane"
name = "psu3mcu"
address = 0b1011_010
device = "psumcu"
description = "PSU 3 MCU"

[[config.i2c.devices]]
bus = "backplane"
name = "psu4eeprom"
address = 0b1010_011
device = "psueeprom"
description = "PSU 4 EEPROM"

[[config.i2c.devices]]
bus = "backplane"
name = "psu4mcu"
address = 0b1011_011
device = "psumcu"
description = "PSU 4 MCU"

[[config.i2c.devices]]
bus = "backplane"
name = "psu5eeprom"
address = 0b1010_100
device = "psueeprom"
description = "PSU 5 EEPROM"

[[config.i2c.devices]]
bus = "backplane"
name = "psu5mcu"
address = 0b1011_100
device = "psumcu"
description = "PSU 5 MCU"

[[config.i2c.devices]]
bus = "backplane"
name = "psu6eeprom"
address = 0b1010_101
device = "psueeprom"
description = "PSU 6 EEPROM"

[[config.i2c.devices]]
bus = "backplane"
name = "psu6mcu"
address = 0b1011_101
device = "psumcu"
description = "PSU 6 MCU"

[[config.i2c.devices]]
bus = "status"
address = 0b0100_000
device = "max7311"
description = "I2C expander"

[[config.i2c.devices]]
bus = "status"
address = 0b0100_100
device = "max7311"
description = "I2C expander"

[config.spi.spi2]
controller = 2

[config.spi.spi2.mux_options.port_i]
outputs = [
    {port = "I", pins = [1, 3], af = 5},
]
input = {port = "I", pin = 2, af = 5}

[config.spi.spi2.devices.ksz8463]
mux = "port_i"
cs = [{port = "I", pin = 0}]

[config.spi.spi4]
controller = 4

[config.spi.spi4.mux_options.rot]
outputs = [
    {port = "E", pins = [2, 6], af = 5},
]
input = {port = "E", pin = 5, af = 5}

[config.spi.spi4.devices.rot]
mux = "rot"
cs = [{port = "E", pin = 4}]
clock_divider = "DIV16"


[config.net]
vlan = { start = 0x301, count = 2 }

[config.net.sockets.echo]
kind = "udp"
owner = {name = "udpecho", notification = 1}
port = 7
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.broadcast]
kind = "udp"
owner = {name = "udpbroadcast", notification = 1}
port = 997
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.rpc]
kind = "udp"
owner = {name = "udprpc", notification = 1}
port = 998
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.mgmt_gateway]
kind = "udp"
owner = {name = "mgmt_gateway", notification = 0b01}
port = 11111 # TODO do we have a documented port for MGS traffic?
tx = { packets = 3, bytes = 2048 }
rx = { packets = 3, bytes = 2048 }
