name = "psc-c-dev"
inherit = ["rev-c.toml", "dev.toml"]

[tasks.framulator]
bin-crate = "task-framulator"
priority = 5
start = true
task-slots = [{spi_driver = "spi2_driver"}]
stacksize = 2048
notifications = ["hey-you"]
