[package]
name = "drv-stm32h7-rcc-api"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib"}
zerocopy = "0.6.1"
byteorder = {version = "1.3", default-features = false}
num-traits = {version = "0.2", default-features = false}

[build-dependencies]
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

[features]
default = ["standalone"]
standalone = ["h753"]
h743 = []
h747 = []
h753 = []
h757 = []
h7b3 = []

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
bench = false
