[package]
name = "task-hiffy"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib"}
hubris-num-tasks = {path = "../../sys/num-tasks", features = ["task-enum"]}
ringbuf = {path = "../../lib/ringbuf" }
drv-i2c-api = {path = "../../drv/i2c-api"}
drv-spi-api = {path = "../../drv/spi-api"}
drv-stm32h7-i2c = {path = "../../drv/stm32h7-i2c", default-features = false, optional = true }
drv-lpc55-gpio-api = {path = "../../drv/lpc55-gpio-api", optional = true}
drv-gimlet-hf-api = {path = "../../drv/gimlet-hf-api", optional = true}
drv-stm32g0-sys-api = {path = "../../drv/stm32g0-sys-api", default-features = false, optional = true}
cortex-m = { version = "0.7", features = ["inline-asm"] }
cfg-if = "0.1.10"
zerocopy = "0.6.1"
num-traits = { version = "0.2.12", default-features = false }
hif = { git = "https://github.com/oxidecomputer/hif" }
serde = { version = "1.0.114", default-features = false }
byteorder = { version = "1.3.4", default-features = false }
armv6m-atomic-hack = {path = "../../lib/armv6m-atomic-hack"}

[build-dependencies]
build-util = {path = "../../build/util"}
build-i2c = {path = "../../build/i2c"}
anyhow = "1.0.31"
cfg-if = "0.1.10"

[features]
itm = [ "userlib/log-itm" ]
semihosting = [ "userlib/log-semihosting" ]
i2c = []
gpio = []
spi = []
stm32h7 = ["drv-stm32g0-sys-api/family-stm32h7", "userlib/panic-messages"]
lpc55 = ["drv-lpc55-gpio-api", "userlib/panic-messages"]
stm32g0 = ["drv-stm32g0-sys-api/family-stm32g0"]
qspi = ["drv-gimlet-hf-api"]
h743 = ["stm32h7", "drv-stm32h7-i2c/h743", "build-i2c/h743"]
h753 = ["stm32h7", "drv-stm32h7-i2c/h753", "build-i2c/h753"]
micro = ["userlib/log-null"]
panic-messages = ["userlib/panic-messages"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-hiffy"
test = false
bench = false
