[package]
name = "task-hiffy"
version = "0.1.0"
edition = "2021"

[dependencies]
armv6m-atomic-hack = { path = "../../lib/armv6m-atomic-hack" }
drv-hf-api = { path = "../../drv/hf-api", optional = true }
drv-hash-api = { path = "../../drv/hash-api", optional = true }
drv-i2c-api = { path = "../../drv/i2c-api" }
drv-lpc55-gpio-api = { path = "../../drv/lpc55-gpio-api", optional = true }
drv-sp-ctrl-api = { path = "../../drv/sp-ctrl-api", optional = true }
drv-spi-api = { path = "../../drv/spi-api" }
drv-sprot-api = { path = "../../drv/sprot-api", optional = true }
drv-stm32xx-i2c = { path = "../../drv/stm32xx-i2c", optional = true  }
drv-stm32xx-sys-api = { path = "../../drv/stm32xx-sys-api", optional = true }
hubris-num-tasks = { path = "../../sys/num-tasks", features = ["task-enum"] }
ringbuf = { path = "../../lib/ringbuf"  }
static-cell = { path = "../../lib/static-cell"  }
userlib = { path = "../../sys/userlib" }
test-api = { path = "../../test/test-api", optional = true}

byteorder.workspace = true
cfg-if.workspace = true
cortex-m.workspace = true
hif.workspace = true
idol-runtime.workspace = true
num-traits.workspace = true
serde.workspace = true
zerocopy.workspace = true

[build-dependencies]
build-util = { path = "../../build/util" }
build-i2c = { path = "../../build/i2c" }
anyhow.workspace = true
cfg-if.workspace = true
idol.workspace = true

[features]
no-ipc-counters = ["idol/no-counters"]
testsuite = [ "test-api" ]
i2c = []
gpio = []
spi = []
send = []
send-rw = []
sprot = ["drv-sprot-api"]
stm32h7 = ["drv-stm32xx-sys-api/family-stm32h7", "userlib/panic-messages", "send", "send-rw"]
lpc55 = ["drv-lpc55-gpio-api", "userlib/panic-messages", "send", "send-rw"]
stm32g0 = ["drv-stm32xx-sys-api/family-stm32g0"]
qspi = ["drv-hf-api"]
hash = ["drv-hash-api"]
h743 = ["stm32h7", "drv-stm32xx-i2c/h743", "build-i2c/h743"]
h753 = ["stm32h7", "drv-stm32xx-i2c/h753", "build-i2c/h753"]
g031 = ["stm32g0", "drv-stm32xx-i2c/g031", "build-i2c/g031"]
g030 = ["stm32g0", "drv-stm32xx-i2c/g030", "build-i2c/g030"]
micro = ["no-ipc-counters"]
# enables large memory buffer to make hiffy not slow
turbo = []
panic-messages = ["userlib/panic-messages"]
spctrl = ["drv-sp-ctrl-api"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-hiffy"
test = false
doctest = false
bench = false

[lints]
workspace = true
