[package]
name = "drv-stm32h7-sprot-server"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = { workspace = true }
hubpack = { workspace = true }
idol-runtime = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
ssmarshal = { workspace = true }
zerocopy = { workspace = true }

drv-spi-api = { path = "../../drv/spi-api" }
drv-sprot-api = { path = "../../drv/sprot-api", features = ["sink_test"] }
drv-stm32h7-spi-server-core = { path = "../../drv/stm32h7-spi-server-core", optional = true }
drv-stm32xx-sys-api = { path = "../../drv/stm32xx-sys-api", features = ["family-stm32h7"] }
drv-update-api = { path = "../../drv/update-api" }
notifications = { path = "../../lib/notifications", features = ["stm32h7-sprot-server"] }
ringbuf = { path = "../../lib/ringbuf" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
build-util = { path = "../../build/util" }
idol = { workspace = true }

[features]
use-spi-core = ["drv-stm32h7-spi-server-core"]
h743 = ["drv-stm32h7-spi-server-core?/h743"]
h753 = ["drv-stm32h7-spi-server-core?/h753"]
sink_test = []

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-stm32h7-sprot-server"
test = false
bench = false
