[package]
name = "drv-grapefruit-seq-server"
version = "0.1.0"
edition = "2021"

[dependencies]
counters = { path = "../../lib/counters" }
drv-auxflash-api = { path = "../auxflash-api" }
drv-cpu-power-state = { path = "../cpu-power-state" }
drv-cpu-seq-api = { path = "../cpu-seq-api" }
drv-spartan7-loader-api = { path = "../spartan7-loader-api" }
drv-stm32xx-sys-api = { path = "../stm32xx-sys-api" }
drv-user-leds-api = { path = "../user-leds-api" }
task-packrat-api = { path = "../../task/packrat-api" }
ringbuf = { path = "../../lib/ringbuf" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }
task-jefe-api = { path = "../../task/jefe-api" }

cfg-if = { workspace = true }
idol-runtime.workspace = true
num-traits = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

[build-dependencies]
build-fpga-regmap = { path = "../../build/fpga-regmap" }
build-util = { path = "../../build/util" }
idol = { workspace = true }

[features]
h753 = ["drv-stm32xx-sys-api/h753"]

[[bin]]
name = "drv-grapefruit-seq-server"
test = false
doctest = false
bench = false

[lints]
workspace = true
