[package]
name = "task-jefe"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { workspace = true }
idol-runtime = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
ssmarshal = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }
hubpack = { workspace = true }
humpty = { workspace = true }
cfg-if = { workspace = true }

abi = { path = "../../sys/abi" }
armv6m-atomic-hack = { path = "../../lib/armv6m-atomic-hack" }
hubris-num-tasks = { path = "../../sys/num-tasks", features = ["task-enum"] }
ringbuf = { path = "../../lib/ringbuf"  }
task-jefe-api = { path = "../jefe-api" }
userlib = { path = "../../sys/userlib" }
static-cell = { path = "../../lib/static-cell" }

[build-dependencies]
anyhow = { workspace = true }
idol = { workspace = true }
serde = { workspace = true }

build-util = { path = "../../build/util" }

[features]
dump = []
nano = [ "ringbuf/disabled" ]
no-panic = [ "userlib/no-panic" ]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-jefe"
test = false
doctest = false
bench = false

[lints]
workspace = true
