[package]
name = "task-jefe"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { workspace = true }
cortex-m-semihosting = { workspace = true, optional = true }
idol-runtime = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
ssmarshal = { workspace = true }
zerocopy = { workspace = true }

abi = { path = "../../sys/abi" }
armv6m-atomic-hack = { path = "../../lib/armv6m-atomic-hack" }
hubris-num-tasks = { path = "../../sys/num-tasks", features = ["task-enum"] }
notifications = { path = "../../lib/notifications"  }
ringbuf = { path = "../../lib/ringbuf"  }
task-jefe-api = { path = "../jefe-api" }
userlib = { path = "../../sys/userlib" }

[build-dependencies]
anyhow = { workspace = true }
idol = { workspace = true }
serde = { workspace = true }

build-util = { path = "../../build/util" }

[features]
itm = [ "userlib/log-itm" ]
semihosting = [ "userlib/log-semihosting", "cortex-m-semihosting" ]
log-null = ["userlib/log-null"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-jefe"
test = false
bench = false
