[package]
name = "task-jefe"
version = "0.1.0"
edition = "2018"

[dependencies]
abi = {path = "../../sys/abi"}
userlib = {path = "../../sys/userlib"}
hubris-num-tasks = {path = "../../sys/num-tasks"}
ringbuf = {path = "../../lib/ringbuf" }
num-traits = { version = "0.2.12", default-features = false }
zerocopy = "0.6.1"
cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-semihosting = { version = "0.3.7", features = ["inline-asm"], optional = true }
armv6m-atomic-hack = {path = "../../lib/armv6m-atomic-hack"}

[build-dependencies]
build-util = {path = "../../build/util"}

[features]
itm = [ "userlib/log-itm" ]
semihosting = [ "userlib/log-semihosting", "cortex-m-semihosting" ]
log-null = ["userlib/log-null"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
name = "task_jefe"
test = false
bench = false
crate_type = ["staticlib"]
