# This is a variation on the main LPC55xpresso `app.toml` that allows it to be
# used as an SP-RoT tester, attached to a Gimletlet.  Only the SPI target should
# work; using the LPC55Xpresso as a debugger for the Gimletlet would require
# additional changes to this file.
#
# To set up the system, connect a (custom) cable from the Gimletlet's SPI3
# header to P23 on the LPC55Xpresso

name = "lpc55xpresso-sprot"
target = "thumbv8m.main-none-eabihf"
board = "lpcxpresso55s69"
chip = "../../chips/lpc55"
stacksize = 1024
image-names = ["a", "b"]
fwid = true

[kernel]
name = "lpc55xpresso"
features = ["dice-self"]
requires = {flash = 54128, ram = 4096}

[caboose]
region = "flash"
size = 256
default = true

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 16384, ram = 2048}
start = true
stacksize = 1536
notifications = ["fault", "timer"]
extern-regions = ["sram2"]

[tasks.jefe.config.allowed-callers]
request_reset = ["update_server"]

[tasks.hiffy]
name = "task-hiffy"
priority = 5
features = ["lpc55", "gpio"]
max-sizes = {flash = 32768, ram = 16384 }
stacksize = 2048
start = true
task-slots = ["gpio_driver", "update_server"]

[tasks.idle]
name = "task-idle"
priority = 7
max-sizes = {flash = 256, ram = 256}
stacksize = 256
start = true

[tasks.update_server]
name = "lpc55-update-server"
priority = 3
stacksize = 3136
start = true
sections = {bootstate = "usbsram"}
uses = ["flash_controller", "hash_crypt"]
notifications = ["flash-irq", "hashcrypt-irq"]
interrupts = {"flash_controller.irq" = "flash-irq", "hash_crypt.irq" = "hashcrypt-irq"}
task-slots = [{"syscon" = "syscon_driver"}, "jefe"]

[tasks.syscon_driver]
name = "drv-lpc55-syscon"
priority = 2
max-sizes = {flash = 8192, ram = 2048}
uses = ["syscon", "anactrl", "pmc"]
start = true
stacksize = 1000
task-slots = ["jefe"]

[tasks.gpio_driver]
name = "drv-lpc55-gpio"
priority = 3
max-sizes = {flash = 8192, ram = 2048}
uses = ["gpio", "iocon", "pint", "inputmux"]
start = true
stacksize = 1000
task-slots = ["syscon_driver"]

[tasks.user_leds]
name = "drv-user-leds"
features = ["lpc55"]
priority = 4
max-sizes = {flash = 8192, ram = 2048}
start = true
stacksize = 1000
task-slots = ["gpio_driver"]
notifications = ["timer"]

[tasks.usart_driver]
name = "drv-lpc55-usart"
priority = 4
max-sizes = {flash = 8192, ram = 2048}
uses = ["flexcomm0"]
start = true
notifications = ["usart-irq"]
interrupts = {"flexcomm0.irq" = "usart-irq"}
stacksize = 1000
task-slots = ["gpio_driver", "syscon_driver"]

[tasks.usart_driver.config]
pins = [
    { pin = { port = 0, pin = 29}, alt = 1},
    { pin = { port = 0, pin = 30}, alt = 1}
]

[tasks.i2c_driver]
name = "drv-lpc55-i2c"
priority = 4
uses = ["flexcomm4"]
start = true
stacksize = 1000
task-slots = ["gpio_driver", "syscon_driver"]

[tasks.rng_driver]
name = "drv-lpc55-rng"
priority = 3
max-sizes = {flash = 16384, ram = 4096}
uses = ["rng", "pmc"]
start = true
stacksize = 2200
task-slots = ["syscon_driver"]

[tasks.pong]
name = "task-pong"
priority = 5
max-sizes = {flash = 8192, ram = 2048}
start = true
stacksize = 1000
notifications = ["timer"]
task-slots = ["user_leds"]

[tasks.swd]
name = "drv-lpc55-swd"
priority = 4
max-sizes = {flash = 16384, ram = 4096}
uses = ["flexcomm5", "iocon"]
start = true
stacksize = 1000
task-slots = ["gpio_driver", "syscon_driver"]
notifications = ["spi-irq", "timer"]
interrupts = {"flexcomm5.irq" = "spi-irq"}

[tasks.swd.config]
# On the LPC55Xpresso, these are all connected to SD0, i.e. the SD card on P21.
# It's harmless to have them up and running, although they won't do anything.

# MOSI = PIO0_8
# MISO = PIO0_9
# CLK = PIO0_7

# Out = MOSI on, MISO off
out_cfg = [
    { pin = { port = 0, pin = 8 }, alt = 3 },
    { pin = { port = 0, pin = 9 }, alt = 0, mode = "pulldown" },
]
# In = MISO on, MOSI off
in_cfg = [
    { pin = { port = 0, pin = 9 }, alt = 3 },
    { pin = { port = 0, pin = 8 }, alt = 0, mode = "pulldown" },
]
pins = [
    # SCK
    { pin = { port = 0, pin = 7 }, alt = 3 },
    { name = "SD0_CARD_DET", pin = { port = 0, pin = 17 }, alt = 0, direction = "input" },
    { name = "SP_TO_ROT_JTAG_DETECT_L", pin = { port = 0, pin = 20 }, alt = 0, direction = "input" },
    { name = "ROT_TO_SP_RESET_L", pin = { port = 0, pin = 13 }, alt = 0, value = true, direction = "output", opendrain = "opendrain" },
]
spi_num = 5

[tasks.dumper]
name = "task-dumper"
priority = 5
max-sizes = {flash = 16384, ram = 4096}
start = true
stacksize = 2600
task-slots = ["swd"]

[tasks.sprot]
name = "drv-lpc55-sprot-server"
priority = 6
uses = ["flexcomm8", "bootrom"]
features = ["spi0"]
start = true
notifications = ["spi-irq"]
interrupts = {"flexcomm8.hs_spi" = "spi-irq"}
stacksize = 16384
task-slots = ["gpio_driver", "syscon_driver", "update_server", "dumper", "attest"]

[tasks.sprot.config]
pins = [
    # HS_SPI_MOSI = P0_26 = FUN9
    { pin = { port = 0, pin = 26}, alt = 9},
    # HS_SPI_MISO = P1_3 = FUN6
    { pin = { port = 1, pin = 3}, alt = 6},
    # HS_SPI_SCK = P1_2 = FUN6
    { pin = { port = 1, pin = 2}, alt = 6},
    # HS_SSEL1 = P1_1 = FUN5
    { name = "CHIP_SELECT", pin = { port = 1, pin = 1}, alt = 5},
    # ROT_IRQ = P0_16 = FUN0
    { name = "ROT_IRQ", pin = { port = 0, pin = 16}, alt = 0, direction = "output"},
    # SP_RESET = P1_5 = FUN0 (not connected)
    { name = "SP_RESET", pin = { port = 1, pin = 5}, alt = 0, direction = "input"},
]

[tasks.attest]
name = "task-attest"
priority = 5
max-sizes = {flash = 34336, ram = 16384}
stacksize = 12304
start = true
extern-regions = ["dice_alias", "dice_certs"]

[signing.certs]
signing-certs = ["../../support/fake_certs/fake_certificate.der.crt"]
root-certs = ["../../support/fake_certs/fake_certificate.der.crt"]
private-key = "../../support/fake_certs/fake_private_key.pem"
