name = "lpc55xpresso"
target = "thumbv8m.main-none-eabihf"
board = "lpcxpresso55s69"
chip = "../../chips/lpc55"
stacksize = 1024
image-names = ["a", "b"]
fwid = true

[kernel]
name = "lpc55xpresso"
features = ["dump", "dice-self"]
requires = {flash = 55040, ram = 4096}

[caboose]
region = "flash"
size = 256
default = true

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 16384, ram = 2048}
start = true
features = ["dump"]
stacksize = 1536
notifications = ["fault", "timer"]
extern-regions = ["sram2"]

[tasks.jefe.config.allowed-callers]
request_reset = ["update_server"]

[tasks.hiffy]
name = "task-hiffy"
priority = 5
features = ["lpc55", "gpio"]
max-sizes = {flash = 32768, ram = 16384 }
stacksize = 2048
start = true
task-slots = ["gpio_driver", "update_server"]

[tasks.idle]
name = "task-idle"
priority = 7
max-sizes = {flash = 256, ram = 256}
stacksize = 256
start = true

[tasks.update_server]
name = "lpc55-update-server"
priority = 3
max-sizes = {flash = 27008, ram = 16704}
stacksize = 8192
start = true
sections = {bootstate = "usbsram"}
uses = ["flash_controller", "hash_crypt"]
notifications = ["flash-irq", "hashcrypt-irq"]
interrupts = {"flash_controller.irq" = "flash-irq", "hash_crypt.irq" = "hashcrypt-irq"}
task-slots = [{"syscon" = "syscon_driver"}, "jefe"]

[tasks.syscon_driver]
name = "drv-lpc55-syscon"
priority = 2
max-sizes = {flash = 8192, ram = 2048}
uses = ["syscon", "anactrl", "pmc"]
start = true
stacksize = 1000
task-slots = ["jefe"]

[tasks.gpio_driver]
name = "drv-lpc55-gpio"
priority = 3
max-sizes = {flash = 8192, ram = 2048}
uses = ["gpio", "iocon", "pint", "inputmux"]
start = true
stacksize = 1000
task-slots = ["syscon_driver"]

[tasks.user_leds]
name = "drv-user-leds"
features = ["lpc55"]
priority = 4
max-sizes = {flash = 8192, ram = 2048}
start = true
stacksize = 1000
task-slots = ["gpio_driver"]
notifications = ["timer"]

[tasks.usart_driver]
name = "drv-lpc55-usart"
priority = 4
max-sizes = {flash = 8192, ram = 2048}
uses = ["flexcomm0"]
start = true
notifications = ["usart-irq"]
interrupts = {"flexcomm0.irq" = "usart-irq"}
stacksize = 1000
task-slots = ["gpio_driver", "syscon_driver"]

[tasks.usart_driver.config]
pins = [
    { pin = { port = 0, pin = 29}, alt = 1},
    { pin = { port = 0, pin = 30}, alt = 1}
]

[tasks.i2c_driver]
name = "drv-lpc55-i2c"
priority = 4
uses = ["flexcomm4"]
start = true
stacksize = 1000
task-slots = ["gpio_driver", "syscon_driver"]

[tasks.rng_driver]
name = "drv-lpc55-rng"
priority = 3
max-sizes = {flash = 16384, ram = 4096}
uses = ["rng", "pmc"]
start = true
stacksize = 2200
task-slots = ["syscon_driver"]

[tasks.pong]
name = "task-pong"
priority = 5
max-sizes = {flash = 8192, ram = 2048}
start = true
stacksize = 1000
notifications = ["timer"]
task-slots = ["user_leds"]

[tasks.dump_agent]
name = "task-dump-agent"
features = ["no-rot"]
priority = 5
max-sizes = {flash = 32768, ram = 2272 }
start = true
task-slots = ["jefe"]
stacksize = 1536
extern-regions = ["sram2"]

[tasks.attest]
name = "task-attest"
priority = 5
max-sizes = {flash = 35072, ram = 16384}
stacksize = 12304
start = true
extern-regions = ["dice_alias", "dice_certs"]

[signing.certs]
signing-certs = ["../../support/fake_certs/fake_certificate.der.crt"]
root-certs = ["../../support/fake_certs/fake_certificate.der.crt"]
private-key = "../../support/fake_certs/fake_private_key.pem"
