name = "lpc55xpresso"
target = "thumbv8m.main-none-eabihf"
board = "lpcxpresso55s69"
stacksize = 1024
secure = true

[kernel]
path = "."
name = "lpc55xpresso"
requires = {flash = 32768, ram = 4096}
features = ["itm"]

[supervisor]
notification = 1

[outputs.bootloader_sram]
address = 0x14000000
size = 0x8000

[outputs.bootloader_flash]
address = 0x00000000
size = 0x8000

[outputs.bootloader_ram]
address = 0x20000000
size = 0x4000

# We reserve the last sector (0x8000) for flash testing
[outputs.flash]
address = 0x00008000
size = 0x88000
read = true
execute = true

[outputs.ram]
address = 0x20004000
size = 0x18000
read = true
write = true
execute = true

[signing.combined]
method = "ecc"
priv-key = "../../support/fake_certs/p256-private-key.der"

[signing.bootloader]
method = "rsa"
priv-key = "../../support/fake_certs/fake_private_key.pem"
root-cert = "../../support/fake_certs/fake_certificate.der.crt"

[bootloader]
path = "../../stage0"
name = "stage0"
sections = {"flash_hypo" = "flash"}
sharedsyms = ["write_to_flash"]
# Currently we have the first 0x8000 of flash and first 0x4000 of RAM
# dedicated for the stage0 bootloader and the rest for Hubris. Once we have
# multiple images this will need to be adjusted
imagea-flash-start = 0x8000
imagea-flash-size = 0x88000
imagea-ram-start = 0x20004000
imagea-ram-size = 0x18000

[tasks.jefe]
path = "../../task/jefe"
name = "task-jefe"
priority = 0
requires = {flash = 32768, ram = 4096}
start = true
features = ["itm"]
stacksize = 1536

[tasks.hiffy]
path = "../../task/hiffy"
name = "task-hiffy"
priority = 3
features = ["lpc55", "gpio"]
requires = {flash = 32768, ram = 16384 }
stacksize = 2048
start = true
task-slots = ["gpio_driver"]

[tasks.idle]
path = "../../task/idle"
name = "task-idle"
priority = 5
requires = {flash = 256, ram = 256}
stacksize = 256
start = true

[tasks.syscon_driver]
path = "../../drv/lpc55-syscon"
name = "drv-lpc55-syscon"
priority = 2
requires = {flash = 16384, ram = 1024}
uses = ["syscon", "anactrl", "pmc"]
start = true
stacksize = 1000

[tasks.gpio_driver]
path = "../../drv/lpc55-gpio"
name = "drv-lpc55-gpio"
priority = 2
requires = {flash = 16384, ram = 1024}
uses = ["gpio", "iocon"]
start = true
stacksize = 1000
task-slots = ["syscon_driver"]

[tasks.user_leds]
path = "../../drv/user-leds"
name = "drv-user-leds"
features = ["lpc55"]
priority = 2
requires = {flash = 16384, ram = 1024}
start = true
stacksize = 1000
task-slots = ["gpio_driver"]

[tasks.usart_driver]
path = "../../drv/lpc55-usart"
name = "drv-lpc55-usart"
priority = 2
requires = {flash = 16384, ram = 1024}
uses = ["flexcomm0"]
start = true
interrupts = {14 = 1}
stacksize = 1000
task-slots = ["gpio_driver", "syscon_driver"]

[tasks.i2c_driver]
path = "../../drv/lpc55-i2c"
name = "drv-lpc55-i2c"
priority = 2
requires = {flash = 16384, ram = 1024}
uses = ["flexcomm4"]
start = true
stacksize = 1000
task-slots = ["gpio_driver", "syscon_driver"]

[tasks.rng_driver]
path = "../../drv/lpc55-rng"
name = "drv-lpc55-rng"
priority = 2
requires = {flash = 16384, ram = 1024}
uses = ["rng", "pmc"]
start = true
stacksize = 1000
task-slots = ["syscon_driver"]

[tasks.spi_driver]
path = "../../drv/lpc55-spi-server"
name = "drv-lpc55-spi-server"
priority = 2
requires = {flash = 16384, ram = 1024}
uses = ["flexcomm8"]
start = true
interrupts = {59 = 1}
stacksize = 1000
task-slots = ["gpio_driver", "syscon_driver"]

[tasks.ping]
path = "../../task/ping"
name = "task-ping"
features = ["uart"]
priority = 4
requires = {flash = 8192, ram = 1024}
start = true
stacksize = 1000
task-slots = [{peer = "pong"}, "usart_driver"]

[tasks.pong]
path = "../../task/pong"
name = "task-pong"
priority = 3
requires = {flash = 8192, ram = 1024}
start = true
stacksize = 1000
task-slots = ["user_leds"]

[tasks.spam]
path = "../../task/spam2"
name = "task-spam"
priority = 3
requires = {flash = 8192, ram = 1024}
stacksize = 1000
task-slots = ["i2c_driver"]

[peripherals.syscon]
address = 0x40000000
size = 4096

[peripherals.anactrl]
address = 0x40013000
size = 4096

[peripherals.gpio]
address = 0x4008c000
size = 9348

[peripherals.iocon]
address = 0x40001000
size = 4096

[peripherals.flexcomm0]
address = 0x40086000
size = 4096

[peripherals.flexcomm4]
address = 0x4008A000
size = 4096

[peripherals.pmc]
address = 0x40020000
size = 4096

[peripherals.flexcomm8]
address = 0x4009F000
size = 4096

[peripherals.rng]
address = 0x4003A000
size = 4096
