[package]
edition = "2021"
readme = "README.md"
name = "lpc55xpresso"
version = "0.1.0"

[features]
dump = ["kern/dump"]
dice-mfg= ["lpc55-rot-startup/dice-mfg"]
dice-self = ["lpc55-rot-startup/dice-self"]
locked = ["lpc55-rot-startup/locked"]

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
lpc55-pac = { workspace = true, features = ["rt"]}
cfg-if = { workspace = true }

abi = { path = "../../sys/abi"}
kern = { path = "../../sys/kern" }
lpc55-rot-startup = {path = "../../lib/lpc55-rot-startup"}
unwrap-lite = {path = "../../lib/unwrap-lite"}
lpc55_romapi = { path = "../../lib/lpc55-romapi" }
lpc55-hashcrypt = { path = "../../lib/lpc55-hashcrypt" }

# this lets you use `cargo fix`!
[[bin]]
name = "lpc55xpresso"
test = false
doctest = false
bench = false

[lints]
workspace = true
