[package]
edition = "2021"
readme = "README.md"
name = "lpc55xpresso"
version = "0.1.0"

[features]
dump = ["kern/dump"]

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
lpc55-pac = { workspace = true, features = ["rt"]}
cfg-if = { workspace = true }

abi = { path = "../../sys/abi"}
kern = { path = "../../sys/kern" }

# this lets you use `cargo fix`!
[[bin]]
name = "lpc55xpresso"
test = false
bench = false
