name = "lpc55xpresso"
target = "thumbv8m.main-none-eabihf"
board = "lpcxpresso55s69"
chip = "../../chips/lpc55"
secure-separation = true
image-names = ["stage0"]
external-images = ["a", "b"]

[kernel]
name = "stage0"
requires = {flash = 0x8000, ram = 16000}
features = ["tz_support", "dice"]
stacksize = 12000

[tasks.idle]
name = "task-idle"
priority = 0
max-sizes = {flash = 256, ram = 256}
stacksize = 256
start = true

[signing]
priv-key = "../../support/fake_certs/fake_private_key.pem"
root-cert = "../../support/fake_certs/fake_certificate.der.crt"
enable-dice = true
dice-inc-nxp-cfg = false
dice-cust-cfg = false
dice-inc-sec-epoch = false
