[package]
name = "drv-gimlet-seq-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
userlib = {path = "../../userlib"}
zerocopy = "0.3.0"
num-traits = { version = "0.2.12", default-features = false }
drv-stm32h7-spi = {path = "../stm32h7-spi"}
drv-stm32h7-rcc-api = {path = "../stm32h7-rcc-api"}
drv-stm32h7-gpio-api = {path = "../stm32h7-gpio-api"}
drv-spi-api = {path = "../spi-api"}
drv-ice40-spi-program = {path = "../ice40-spi-program"}
cortex-m = { version = "0.7", features = ["inline-asm"] }
cfg-if = "0.1.10"
gnarle = {path = "../../gnarle"}

[build-dependencies]
build-util = {path = "../../build-util"}
gnarle = {path = "../../gnarle"}

[features]
default = ["standalone"]
standalone = []

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"
