[package]
name = "drv-gimlet-seq-server"
version = "0.1.0"
edition = "2021"

[dependencies]
drv-gimlet-hf-api = { path = "../gimlet-hf-api" }
drv-gimlet-seq-api = { path = "../gimlet-seq-api" }
drv-gimlet-state = { path = "../gimlet-state" }
drv-i2c-api = { path = "../i2c-api" }
drv-i2c-devices = { path = "../i2c-devices" }
drv-ice40-spi-program = { path = "../ice40-spi-program" }
drv-packrat-vpd-loader = { path = "../packrat-vpd-loader" }
drv-spi-api = { path = "../spi-api" }
drv-stm32h7-spi = { path = "../stm32h7-spi" }
drv-stm32xx-sys-api = { path = "../stm32xx-sys-api" }
counters = { path = "../../lib/counters" }
gnarle = { path = "../../lib/gnarle" }
ringbuf = { path = "../../lib/ringbuf" }
task-jefe-api = { path = "../../task/jefe-api" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

byteorder = { workspace = true }
cfg-if = { workspace = true }
cortex-m = { workspace = true }
idol-runtime.workspace = true
num-traits = { workspace = true }
zerocopy = { workspace = true }
num-derive = { workspace = true }
static_assertions = { workspace = true }
spd = { workspace = true }

[build-dependencies]
build-fpga-regmap = { path = "../../build/fpga-regmap" }
build-i2c = { path = "../../build/i2c" }
build-util = { path = "../../build/util" }
gnarle = { path = "../../lib/gnarle", features=["std"] }

idol = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

[features]
h753 = ["drv-stm32h7-spi/h753", "drv-stm32xx-sys-api/h753"]
stay-in-a2 = []
no-ipc-counters = ["idol/no-counters"]

[[bin]]
name = "drv-gimlet-seq-server"
test = false
doctest = false
bench = false
