[package]
name = "drv-stm32h7-spi-server"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
ringbuf = {path = "../../lib/ringbuf"}
zerocopy = "0.6.1"
num-traits = { version = "0.2.12", default-features = false }
drv-stm32h7-spi = {path = "../stm32h7-spi", default-features = false}
drv-stm32h7-rcc-api = {path = "../stm32h7-rcc-api", default-features = false}
drv-stm32h7-gpio-api = {path = "../stm32h7-gpio-api", default-features = false}
drv-spi-api = {path = "../spi-api", default-features = false}
cortex-m = { version = "0.7", features = ["inline-asm"] }
stm32h7 = { version = "0.13.0", default-features = false }
cfg-if = "0.1.10"
idol-runtime = {git = "https://github.com/oxidecomputer/idolatry.git"}

[build-dependencies]
build-util = {path = "../../build/util"}
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

[features]
default = ["standalone"]
standalone = ["h753"]
spi1 = []
spi2 = []
spi3 = []
spi4 = []
spi5 = []
spi6 = []
h7b3 = ["stm32h7/stm32h7b3", "drv-stm32h7-spi/h7b3", "drv-stm32h7-rcc-api/h7b3"]
h743 = ["stm32h7/stm32h743", "drv-stm32h7-spi/h743", "drv-stm32h7-rcc-api/h743"]
h753 = ["stm32h7/stm32h753", "drv-stm32h7-spi/h753", "drv-stm32h7-rcc-api/h753"]

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-stm32h7-spi-server"
test = false
bench = false
