[package]
name = "drv-stm32h7-spi-server"
version = "0.1.0"
edition = "2021"

[dependencies]
idol-runtime = { workspace = true }
num-traits = { workspace = true }
zerocopy = { workspace = true }

drv-spi-api = { path = "../spi-api" }
drv-stm32h7-spi-server-core = { path = "../stm32h7-spi-server-core" }
drv-stm32xx-sys-api = { path = "../stm32xx-sys-api" }
notifications = { path = "../../lib/notifications" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
idol.workspace = true
build-util.path = "../../build/util"

[features]
# These features are unused in the app itself, but Humility uses them to decide
# which SPI server task to address for a given peripheral.
spi1 = []
spi2 = []
spi3 = []
spi4 = []
spi5 = []
spi6 = []
h743 = ["drv-stm32h7-spi-server-core/h743", "drv-stm32xx-sys-api/h743"]
h753 = ["drv-stm32h7-spi-server-core/h753", "drv-stm32xx-sys-api/h753"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-stm32h7-spi-server"
test = false
bench = false
