[package]
name = "task-caboose-reader-api"
version = "0.1.0"
edition = "2021"

[dependencies]
idol-runtime.workspace = true
num-traits.workspace = true
tlvc.workspace = true

derive-idol-err = { path = "../../lib/derive-idol-err" }
userlib = { path = "../../sys/userlib" }

[build-dependencies]
idol.workspace = true
