[package]
name = "task-udprpc"
version = "0.1.0"
edition = "2021"

[dependencies]
zerocopy = { workspace = true }

notifications = { path = "../../lib/notifications" }
task-net-api = { path = "../net-api" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[features]
vlan = ["task-net-api/vlan"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-udprpc"
test = false
bench = false
