[package]
name = "drv-gimletlet-front-io-seq-server"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder.workspace = true
cfg-if.workspace = true
cortex-m.workspace = true
hubpack.workspace = true
idol-runtime.workspace = true
num-traits.workspace = true
serde.workspace = true
zerocopy.workspace = true

drv-fpga-api = { path = "../fpga-api", features = ["auxflash"] }
drv-fpga-user-api = { path = "../fpga-user-api" }
drv-i2c-api = { path = "../i2c-api" }
drv-i2c-devices = { path = "../i2c-devices" }
drv-sidecar-front-io = { path = "../sidecar-front-io", features = ["controller", "phy_smi", "sequencer"] }
ringbuf = { path = "../../lib/ringbuf" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[features]
h753 = ["build-i2c/h753"]
stay-in-a2 = []

[build-dependencies]
build-util = { path = "../../build/util" }
build-i2c = { path = "../../build/i2c" }
idol = { workspace = true }

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-gimletlet-front-io-seq-server"
test = false
doctest = false
bench = false
