[package]
name = "drv-stm32h7-i2c-server"
version = "0.1.0"
authors = ["Bryan Cantrill <bryan@oxide.computer>"]
edition = "2018"

[dependencies]
fixedmap = {path = "../../fixedmap"}
userlib = {path = "../../userlib"}
ringbuf = {path = "../../ringbuf"}
num-traits = { version = "0.2.12", default-features = false }
drv-stm32h7-gpio-api = {path = "../stm32h7-gpio-api"}
drv-stm32h7-rcc-api = {path = "../stm32h7-rcc-api"}
drv-stm32h7-i2c = {path = "../stm32h7-i2c", default-features = false }
drv-i2c-api = {path = "../i2c-api"}
cortex-m-semihosting = "0.3.5"
cortex-m = { version = "0.7", features = ["inline-asm"] }
cfg-if = "0.1.10"
stm32h7 = { version = "0.13.0" }


[build-dependencies]
build-util = {path = "../../build-util"}
[features]
default = ["standalone"]
standalone = [ "h743" ]
h7b3 = ["stm32h7/stm32h7b3", "drv-stm32h7-i2c/h7b3"]
h743 = ["stm32h7/stm32h743", "drv-stm32h7-i2c/h743"]
itm = [ "userlib/log-itm" ]

# These options allow for external muxes on the Gemini bringup board:
#
# - external-max7358 assumes an external MAX7358 on I2C4 port D
# - external-pca9548 assumes an external PCA9548 on I2C4 port H
#
# Both options may be set, but neither option should be set when the part that
# it denotes isn't present.
external-max7358 = []
external-pca9548 = []

#
# This option allows for the Nucleo to be used as an initiator for the
# purposes of testing the spd-proxy
#
external-spd = []

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-stm32h7-i2c-server"
test = false
bench = false

