[syscon]
address = 0x40000000
size = 4096

[anactrl]
address = 0x40013000
size = 4096

[gpio]
address = 0x4008c000
size = 9348

[iocon]
address = 0x40001000
size = 4096

[flexcomm0]
address = 0x40086000
size = 4096
interrupts = { irq = 14 }

[flexcomm3]
address = 0x40089000
size = 4096
interrupts = { irq = 17 }

[flexcomm4]
address = 0x4008A000
size = 4096

[flexcomm5]
address = 0x40096000
size = 4096
interrupts = { irq = 19 }

[flexcomm8]
address = 0x4009F000
size = 4096
interrupts = { hs_spi = 59 }

[hash_crypt]
address = 0x400A4000
size = 4096
interrupts = { irq = 54 }

[pmc]
address = 0x40020000
size = 4096

[rng]
address = 0x4003A000
size = 4096

# this is the start of the USB SRAM AHB peripheral (0x4000 bytes total)
# we appropriate this SRAM for passing DICE artifacts
[dice_spmeasure]
address = 0x40101200
size = 0x800

[dice_rng]
address = 0x40101a00
size = 0x100

[secure_syscon]
address = 0x50000000
size = 4096

[flash_controller]
address = 0x40034000
size = 0x1000
interrupts = { irq = 0 }

[secure_flash_controller]
address = 0x50034000
size = 0x1000

[bootrom]
address = 0x03000000
size = 0x10000

[pint]
address = 0x4000_4000
size = 0x1000
interrupts = { irq0 = 4, irq1 = 5, irq2 = 6, irq3 = 7, irq4 = 32, irq5 = 33, irq6 = 34, irq7 = 35 }

[inputmux]
address = 0x4000_6000
size = 0x1000
