[[flash]]
name = "a"
address = 0x00010000
size = 0x40000
read = true
execute = true

[[flash]]
name = "b"
address = 0x00050000
size = 0x40000
read = true
execute = true

[[flash]]
name = "stage0"
address = 0x00000000
size = 0x02000
read = true
execute = true

# Staging area for "stage0" updates.
#
# The largest stage0 image to date is about 6-ish KiB,
# while the current release is 4-ish KiB.
# That leaves at least 56 KiB of "stage0" unused.
# The Hubris pre-main kernel code checks "stage0next" at boot time
# When it is still possible to call the ROM-based signature verification
# routine.
[[flash]]
name = "stage0next"
address = 0x00002000
size = 0x02000
read = true
execute = false

[[flash]]
name = "dice-mfg"
address = 0x90000
size = 0x800
read = true
write = false
execute = false

[[ram]]
name = "a"
address = 0x20004000
size = 0x18000
read = true
write = true
execute = false

[[ram]]
name = "b"
address = 0x20004000
size = 0x18000
read = true
write = true
execute = false

[[ram]]
name = "stage0"
address = 0x20000000
size = 0x4000
read = true
write = true
execute = false

[[sram2]]
name = "a"
address = 0x20020000
size = 0x10000
read = true
write = true
execute = false
dma = true

[[sram2]]
name = "b"
address = 0x20020000
size = 0x10000
read = true
write = true
execute = false
dma = true

[[sram2]]
name = "stage0"
address = 0x20020000
size = 0x10000
read = true
write = true
execute = false
dma = true

[[override]]
name = "a"
address = 0x2003ffe0
size = 32
read = true
write = true
execute = false

[[override]]
name = "b"
address = 0x3003ffe0
size = 32
read = true
write = true
execute = false

# Info about the images loaded into flash and dumped by stage0 into USB SRAM
# for hubris use.
[[usbsram]]
name = "a"
address = 0x40102000
size = 0x1000
read = true
write = false
execute = false
dma = true

[[usbsram]]
name = "b"
address = 0x40102000
size = 0x1000
read = true
write = false
execute = false
dma = true

[[usbsram]]
name = "stage0"
address = 0x40102000
size = 0x1000
read = true
write = false
execute = false
dma = true

# RAM region used to hand common part of DICE certificate chain forward to
# Hubris tasks
[[dice_certs]]
name = "a"
address = 0x40100000
size = 0xa00
read = true
write = false
execute = false

[[dice_certs]]
name = "b"
address = 0x40100000
size = 0xa00
read = true
write = false
execute = false

# RAM region used to hand DICE artifacts forward to the attestation responder
[[dice_alias]]
name = "a"
address = 0x40100a00
size = 0x800
read = true
write = true
execute = false

[[dice_alias]]
name = "b"
address = 0x40100a00
size = 0x800
read = true
write = true
execute = false
