[[flash]]
name = "a"
address = 0x00010000
size = 0x40000
read = true
execute = true

[[flash]]
name = "b"
address = 0x00050000
size = 0x40000
read = true
execute = true

[[flash]]
name = "stage0"
address = 0x00000000
size = 0x10000
read = true
execute = true

[[ram]]
name = "a"
address = 0x20004000
size = 0x18000
read = true
write = true
execute = false

[[ram]]
name = "b"
address = 0x20004000
size = 0x18000
read = true
write = true
execute = false

[[ram]]
name = "stage0"
address = 0x20000000
size = 0x4000
read = true
write = true
execute = false

