[package]
name = "drv-stm32h7-i2c"
version = "0.1.0"
authors = ["Bryan Cantrill <bryan@oxide.computer>"]
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib"}
ringbuf = {path = "../../lib/ringbuf"}
zerocopy = "0.3.0"
num-traits = { version = "0.2.12", default-features = false }
drv-stm32h7-gpio-api = {path = "../stm32h7-gpio-api"}
drv-stm32h7-rcc-api = {path = "../stm32h7-rcc-api", default-features = false}
drv-i2c-api = {path = "../i2c-api"}
cortex-m-semihosting = "0.3.5"
cortex-m = { version = "0.7", features = ["inline-asm"] }
cfg-if = "0.1.10"
bitfield = "0.13"
stm32h7 = { version = "0.13.0", default-features = false }

[features]
default = ["standalone"]
standalone = [ "h753" ]
h743 = ["stm32h7/stm32h743", "drv-stm32h7-rcc-api/h743"]
h753 = ["stm32h7/stm32h753", "drv-stm32h7-rcc-api/h753"]
h7b3 = ["stm32h7/stm32h7b3", "drv-stm32h7-rcc-api/h7b3"]
itm = [ "userlib/log-itm" ]

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
bench = false
