name = "gimletlet-sidecar-emulator"
target = "thumbv7em-none-eabihf"
board = "gimletlet-2"
chip = "../../chips/stm32h7"
memory = "memory-large.toml"
stacksize = 896
fwid = true

[kernel]
name = "gimletlet"
requires = {flash = 32768, ram = 8192}

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 2048}
start = true
stacksize = 1536
notifications = ["fault", "timer"]

[tasks.jefe.config.allowed-callers]
set_reset_reason = ["sys"]
request_reset = ["hiffy"]

[tasks.sys]
name = "drv-stm32xx-sys"
features = ["h753"]
priority = 1
max-sizes = {flash = 8192, ram = 1024}
uses = ["rcc", "gpios1", "gpios2", "gpios3", "system_flash"]
start = true
task-slots = ["jefe"]

[tasks.i2c_driver]
name = "drv-stm32xx-i2c-server"
features = ["h753", "itm"]
priority = 2
max-sizes = {flash = 16384, ram = 4096}
uses = ["i2c3", "i2c4"]
start = true
notifications = ["i2c3-irq", "i2c4-irq"]
task-slots = ["sys"]

[tasks.i2c_driver.interrupts]
"i2c3.event" = "i2c3-irq"
"i2c3.error" = "i2c3-irq"
"i2c4.event" = "i2c4-irq"
"i2c4.error" = "i2c4-irq"

[tasks.spi_driver]
name = "drv-stm32h7-spi-server"
priority = 2
max-sizes = {flash = 16384, ram = 4096}
features = ["spi4", "h753"]
uses = ["spi4"]
start = true
notifications = ["spi-irq"]
interrupts = {"spi4.irq" = "spi-irq"}
stacksize = 880
task-slots = ["sys"]

[tasks.user_leds]
name = "drv-user-leds"
features = ["stm32h7"]
priority = 2
max-sizes = {flash = 8192, ram = 1024}
start = true
task-slots = ["sys"]
notifications = ["timer"]

[tasks.pong]
name = "task-pong"
priority = 3
max-sizes = {flash = 8192, ram = 1024}
start = true
task-slots = ["user_leds"]
notifications = ["timer"]

[tasks.hiffy]
name = "task-hiffy"
features = ["h753", "stm32h7", "itm", "i2c", "gpio", "spi"]
priority = 3
max-sizes = {flash = 32768, ram = 32768}
stacksize = 2048
start = true
task-slots = ["sys", "i2c_driver", "user_leds"]

[tasks.fpga]
name = "drv-fpga-server"
priority = 3
max-sizes = {flash = 32768, ram = 4096}
#features = ["leds"]
stacksize = 2048
start = true
task-slots = ["sys", "spi_driver"]

#[tasks.i2c_emulator]
#name = "drv-sidecar-mainboard-i2c-emulator"
#priority = 2
#max-sizes = {flash = 8192, ram = 2048}
#start = true

#[tasks.sequencer]
#name = "drv-sidecar-seq-server"
#features = []
#priority = 4
#max-sizes = {flash = 262144, ram = 2048}
#stacksize = 1024
#start = true
#task-slots = ["sys", {i2c_driver = "i2c_emulator"}, "fpga", "spi_driver"]

[tasks.ignition]
name = "drv-ignition-server"
priority = 5
max-sizes = {flash = 16384, ram = 4096}
stacksize = 2048
start = true
task-slots = ["fpga"]
notifications = ["timer"]
features = ["always-transmit"]

[tasks.idle]
name = "task-idle"
priority = 6
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[config]
[[config.i2c.controllers]]
controller = 2
target = true

[config.i2c.controllers.ports.F]
name = "i2c2"
description = "I2C Port 2"
scl.pin = 1
sda.pin = 0
af = 4

[[config.i2c.controllers]]
controller = 3

#
# Note that I2C3 on Gimletlet is a bit unusual in that its SCL and SDA are on
# two different ports (port A and port C, respectively); we therefore have two
# pin structures for I2C3, but for purposes of the abstraction that i2c
# exports to consumers, we adhere to the convention outlined in the
# definition of `PortIndex` and name the logical port C after the GPIO pin that
# corresponds to SDA.
#
[config.i2c.controllers.ports.C]
scl = { gpio_port = "A", pin = 8 }
sda = { gpio_port = "C", pin = 9 }
af = 4

[[config.i2c.controllers]]
controller = 4

[config.i2c.controllers.ports.F]
scl.pin = 14
sda.pin = 15
af = 4

[config.spi.spi3]
controller = 3

[config.spi.spi3.mux_options.port_c]
outputs = [
    {port = "C", pins = [10, 12], af = 6},
]
input = {port = "C", pin = 11, af = 6}

[config.spi.spi3.devices.spi3_header]
mux = "port_c"
cs = [{port = "A", pin = 15}]


[config.spi.spi4]
controller = 4

[config.spi.spi4.mux_options.port_e]
outputs = [
    {port = "E", pins = [12, 14], af = 5},
]
input = {port = "E", pin = 13, af = 5}

[config.spi.spi4.devices.spi4_header]
mux = "port_e"
cs = [{port = "E", pin = 11}]

[config.spi.spi4.devices.mainboard_controller]
mux = "port_e"
cs = [{port = "E", pin = 11}]

[config.spi.spi6]
controller = 6

[config.spi.spi6.mux_options.port_g]
outputs = [
    {port = "G", pins = [13, 14], af = 5},
]
input = {port = "G", pin = 12, af = 5}

[config.spi.spi6.devices.spi6_header]
mux = "port_g"
cs = [{port = "G", pin = 8}]

[[config.i2c.devices]]
bus = "i2c2"
address = 0b1100_011
device = "raa229618"
description = "TF2 VDD rail"
power = { rails = [ "V0P8_TF2_VDD_CORE" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U31"

[[config.i2c.devices]]
bus = "i2c2"
address = 0b1011_000
device = "idt8a34001"
description = "Clock generator"
refdes = "U38"
