name = "gimletlet-sidecar-emulator"
inherit = "base-gimletlet2.toml"

[tasks.jefe.config.allowed-callers]
request_reset = ["hiffy"]

[tasks.hiffy]
features = ["h753", "stm32h7", "i2c", "gpio", "spi"]
task-slots = ["sys", "i2c_driver", "user_leds"]

[tasks.fpga]
bin-crate = "drv-fpga-server"
priority = 3
max-sizes = {flash = 32768, ram = 8192}
stacksize = 2048
start = true
#features = ["leds"]
features = ["h753", "use-spi-core", "spi6"]
uses = ["spi6"]
task-slots = ["sys"]
interrupts = {"spi6.irq" = "spi-irq"}
notifications = ["spi-irq"]

#[tasks.i2c_emulator]
#name = "drv-sidecar-mainboard-i2c-emulator"
#priority = 2
#max-sizes = {flash = 8192, ram = 2048}
#start = true

#[tasks.sequencer]
#name = "drv-sidecar-seq-server"
#features = []
#priority = 4
#max-sizes = {flash = 262144, ram = 2048}
#stacksize = 1024
#start = true
#task-slots = ["sys", {i2c_driver = "i2c_emulator"}, "fpga", "spi_driver"]

[tasks.ignition]
bin-crate = "drv-ignition-server"
priority = 5
max-sizes = {flash = 16384, ram = 4096}
stacksize = 2048
start = true
task-slots = ["fpga"]
notifications = ["timer"]
features = ["always-transmit"]

[[config.i2c.devices]]
bus = "i2c2"
address = 0b1100_011
device = "raa229618"
description = "TF2 VDD rail"
power = { rails = [ "V0P8_TF2_VDD_CORE" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U31"

[[config.i2c.devices]]
bus = "i2c2"
address = 0b1011_000
device = "idt8a34001"
description = "Clock generator"
refdes = "U38"
