[package]
name = "task-validate-api"
version = "0.1.0"
edition = "2021"

[features]


[dependencies]
idol-runtime.workspace = true
num-traits.workspace = true
zerocopy.workspace = true
zerocopy-derive.workspace = true
hubpack.workspace = true
serde.workspace = true

counters = { path = "../../lib/counters" }
derive-idol-err = { path = "../../lib/derive-idol-err"  }
drv-i2c-api = { path = "../../drv/i2c-api" }
task-sensor-api = { path = "../sensor-api" }
userlib = { path = "../../sys/userlib" }

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
doctest = false
bench = false

[build-dependencies]
build-i2c = { path = "../../build/i2c" }
idol.workspace = true
anyhow.workspace = true

[lints]
workspace = true
