[package]
name = "drv-lpc55-spi-server"
version = "0.1.0"
edition = "2021"

[dependencies]
lpc55-pac = { workspace = true }
num-traits = { workspace = true }
zerocopy = { workspace = true }

drv-lpc55-gpio-api = { path = "../lpc55-gpio-api" }
drv-lpc55-spi = { path = "../lpc55-spi" }
drv-lpc55-syscon-api = { path = "../lpc55-syscon-api" }
notifications = { path = "../../lib/notifications" }
ringbuf = { path = "../../lib/ringbuf" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
build-lpc55pins = { path = "../../build/lpc55pins" }
build-util = { path = "../../build/util" }
serde = { workspace = true }

[features]
spi0 = []

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-lpc55-spi-server"
test = false
bench = false
