[package]
name = "task-packrat"
version = "0.1.0"
edition = "2021"

[dependencies]
gateway-ereport-messages.workspace = true
idol-runtime.workspace = true
num-traits.workspace = true
spd.workspace = true
static_assertions.workspace = true
zerocopy.workspace = true
zerocopy-derive.workspace = true

drv-cpu-seq-api = { path = "../../drv/cpu-seq-api", optional = true }
drv-rng-api = { path = "../../drv/rng-api", optional = true  }
hubris-task-names = { path = "../../sys/task-names" }
mutable-statics = { path = "../../lib/mutable-statics" }
ringbuf = { path = "../../lib/ringbuf"  }
counters = { path = "../../lib/counters"  }
static-cell = { path = "../../lib/static-cell" }
task-packrat-api = { path = "../packrat-api" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }
snitch-core = { version = "0.1.0", path = "../../lib/snitch-core", optional = true, features = ["counters"] }
minicbor = { workspace = true,  optional = true }
minicbor-lease = { path = "../../lib/minicbor-lease", optional = true }
fixedstr = { path = "../../lib/fixedstr" , optional = true, features = ["microcbor"] }

[build-dependencies]
anyhow.workspace = true
cfg-if.workspace = true
idol.workspace = true
quote = { workspace = true, optional = true }
build-util = { path = "../../build/util" }

[features]
cosmo = ["drv-cpu-seq-api"]
gimlet = ["drv-cpu-seq-api"]
grapefruit = []
boot-kmdb = []
no-ipc-counters = ["idol/no-counters"]
ereport = [
    "dep:drv-rng-api",
    "dep:snitch-core",
    "dep:microcbor",
    "dep:minicbor",
    "dep:minicbor-lease",
    "dep:quote",
    "dep:fixedstr",
]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-packrat"
test = false
doctest = false
bench = false

[lints]
workspace = true
