[package]
name = "task-packrat"
version = "0.1.0"
edition = "2021"

[dependencies]
idol-runtime.workspace = true
num-traits.workspace = true
spd.workspace = true
static_assertions.workspace = true
zerocopy.workspace = true

drv-cpu-seq-api = { path = "../../drv/cpu-seq-api", optional = true }
mutable-statics = { path = "../../lib/mutable-statics" }
ringbuf = { path = "../../lib/ringbuf"  }
static-cell = { path = "../../lib/static-cell" }
task-packrat-api = { path = "../packrat-api" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
anyhow.workspace = true
cfg-if.workspace = true
idol.workspace = true

build-util = { path = "../../build/util" }

[features]
boot-kmdb = []
cosmo = ["drv-cpu-seq-api"]
gimlet = ["drv-cpu-seq-api"]
grapefruit = []
no-ipc-counters = ["idol/no-counters"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-packrat"
test = false
doctest = false
bench = false

[lints]
workspace = true
