name = "gimlet-rot"
target = "thumbv8m.main-none-eabihf"
board = "gimlet-rot-1"
chip = "../../chips/lpc55.toml"
stacksize = 1024

[kernel]
path = "."
name = "gimlet-rot"
requires = {flash = 32768, ram = 3072}
features = ["itm"]

[signing.combined]
method = "rsa"
priv-key = "../../support/fake_certs/fake_private_key.pem"
root-cert = "../../support/fake_certs/fake_certificate.der.crt"

[supervisor]
notification = 1

[outputs.flash]
address = 0x00000000
size = 645120
read = true
execute = true

[outputs.ram]
address = 0x20000000
size = 114688
read = true
write = true
execute = true

[tasks.jefe]
path = "../../task/jefe"
name = "task-jefe"
priority = 0
requires = {flash = 8192, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536

[tasks.hiffy]
path = "../../task/hiffy"
name = "task-hiffy"
priority = 3
features = ["lpc55", "gpio"]
requires = {flash = 32768, ram = 16384 }
stacksize = 2048
start = true
task-slots = ["gpio_driver"]

[tasks.idle]
path = "../../task/idle"
name = "task-idle"
priority = 5
requires = {flash = 128, ram = 256}
stacksize = 256
start = true

[tasks.syscon_driver]
path = "../../drv/lpc55-syscon"
name = "drv-lpc55-syscon"
priority = 2
requires = {flash = 4096, ram = 2048}
uses = ["syscon", "anactrl", "pmc"]
start = true

[tasks.gpio_driver]
path = "../../drv/lpc55-gpio"
name = "drv-lpc55-gpio"
priority = 2
requires = {flash = 8192, ram = 2048}
uses = ["gpio", "iocon"]
start = true
task-slots = ["syscon_driver"]

[tasks.usart_driver]
path = "../../drv/lpc55-usart"
name = "drv-lpc55-usart"
priority = 2
requires = {flash = 8192, ram = 2048}
uses = ["iocon", "flexcomm0"]
start = true
interrupts = {"flexcomm0.irq" = 1}
task-slots = ["gpio_driver", "syscon_driver"]

[tasks.spi0_driver]
path = "../../drv/lpc55-spi-server"
name = "drv-lpc55-spi-server"
priority = 2
requires = {flash = 16384, ram = 2048}
uses = ["iocon", "flexcomm3", "flexcomm8"]
features = ["spi0"]
start = true
interrupts = {"flexcomm8.hs_spi" = 1}
stacksize = 1000
task-slots = ["gpio_driver", "syscon_driver"]
