[package]
edition = "2018"
readme = "README.md"
name = "gimlet-rot"
version = "0.1.0"

[features]
itm = ["panic-itm"]
semihosting = ["panic-semihosting"]

[dependencies]
cortex-m = {version = "0.7", features = ["inline-asm"]}
cortex-m-rt = "0.6.12"
panic-itm = { version = "0.4.1", optional = true }
panic-halt = { version = "0.2.0", optional = true }
panic-semihosting = { version = "0.5.3", optional = true }
lpc55-pac = {version = "0.4", features = ["rt"]}
cfg-if = "1"
abi = { path = "../../sys/abi"}

[dependencies.kern]
path = "../../sys/kern"
default-features = false

# this lets you use `cargo fix`!
[[bin]]
name = "gimlet-rot"
test = false
bench = false
