name = "gimlet-rot-b"
target = "thumbv8m.main-none-eabihf"
board = "gimlet-rot-b"
chip = "../../chips/lpc55"
memory = "256k.toml"
stacksize = 1024
image-names = ["stage0"]
external-images = ["a", "b"]

[kernel]
name = "stage0"
requires = {flash = 0x4000, ram = 4096}
features = []

[tasks.idle]
name = "task-idle"
priority = 0
max-sizes = {flash = 256, ram = 256}
stacksize = 256
start = true

[signing]
enable-secure-boot = true
enable-dice = false
dice-inc-nxp-cfg = false
dice-cust-cfg = false
dice-inc-sec-epoch = false

[[signing.certs]]
cert-paths = ["../../support/fake_certs/fake_certificate.der.crt"  ]
priv-key = "../../support/fake_certs/fake_private_key.pem"
