[package]
name = "drv-stm32h7-gpio-int"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

[dependencies]
userlib = {path = "../../userlib"}
zerocopy = "0.3.0"
byteorder = { version = "1.3.4", default-features = false }
num-traits = { version = "0.2.12", default-features = false }
drv-stm32h7-rcc-api = {path = "../stm32h7-rcc-api"}
drv-stm32h7-gpio-api = {path = "../stm32h7-gpio-api"}
stm32h7 = { version = "0.13.0", features = ["stm32h7b3"] }
ringbuf = {path = "../../ringbuf"}


[features]
default = ["standalone"]
standalone = []

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-stm32h7-gpio-int"
test = false
bench = false
