[package]
name = "drv-lpc55-wwdt"
version = "0.1.0"
authors = ["Steve Klabnik <steve.klabnik@oxide.computer>"]
edition = "2018"

[package.metadata.build]
# Pick ONE of these compilation targets
# target = "thumbv6m-none-eabi"    # Cortex-M0 and Cortex-M0+
# target = "thumbv7m-none-eabi"    # Cortex-M3
# target = "thumbv7em-none-eabi"   # Cortex-M4 and Cortex-M7 (no FPU)
target = "thumbv8m.main-none-eabihf"

[dependencies]
userlib = {path = "../../userlib"}
zerocopy = "0.3.0"
lpc55-pac = "0.1.0"
cortex-m = "0.6.2"
num-traits = { version = "0.2.12", default-features = false }
drv-lpc55-syscon-api = {path = "../lpc55-syscon-api"}

[features]
default = ["standalone"]
standalone = []

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-lpc55-wwdt"
test = false
bench = false
