[package]
name = "drv-sidecar-mainboard-i2c-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
drv-i2c-api = { path = "../i2c-api" }
ringbuf = { path = "../../lib/ringbuf" }
userlib = { path = "../../sys/userlib" }

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-sidecar-mainboard-i2c-emulator"
test = false
doctest = false
bench = false

[lints]
workspace = true
