[package]
name = "drv-stm32xx-i2c"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib"}
ringbuf = {path = "../../lib/ringbuf"}
zerocopy = "0.6.1"
num-traits = { version = "0.2.12", default-features = false }
drv-stm32xx-sys-api = {path = "../stm32xx-sys-api", default-features = false}
drv-i2c-api = {path = "../i2c-api"}
cfg-if = "1"
bitfield = "0.13"
stm32g0 = { git = "https://github.com/oxidecomputer/stm32-rs-nightlies", branch = "stm32g0b1-update", default-features = false, optional = true }
stm32h7 = { version = "0.14", default-features = false }

[features]
h743 = ["stm32h7/stm32h743", "drv-stm32xx-sys-api/h743"]
h753 = ["stm32h7/stm32h753", "drv-stm32xx-sys-api/h753"]
g031 = ["stm32g0/stm32g031", "drv-stm32xx-sys-api/g031"]
amd_erratum_1394 = []

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
bench = false
