[package]
name = "drv-stm32xx-i2c"
version = "0.1.0"
edition = "2021"

[dependencies]
bitfield = { workspace = true }
cfg-if = { workspace = true }
num-traits = { workspace = true }
stm32g0 = { workspace = true, optional = true }
stm32h7 = { workspace = true, optional = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

drv-i2c-api = { path = "../i2c-api" }
drv-stm32xx-sys-api = { path = "../stm32xx-sys-api" }
ringbuf = { path = "../../lib/ringbuf" }
counters = { path = "../../lib/counters" }
userlib = { path = "../../sys/userlib" }

[features]
h743 = ["stm32h7/stm32h743", "drv-stm32xx-sys-api/h743"]
h753 = ["stm32h7/stm32h753", "drv-stm32xx-sys-api/h753"]
g031 = ["stm32g0/stm32g031", "drv-stm32xx-sys-api/g031"]
g030 = ["stm32g0/stm32g030", "drv-stm32xx-sys-api/g030"]
amd_erratum_1394 = []
enable_target = []

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
doctest = false
bench = false

[build-dependencies]
build-util = { path = "../../build/util" }

[lints]
workspace = true
