[package]
name = "drv-transceivers-api"
version = "0.1.0"
edition = "2021"

[dependencies]
idol-runtime = { workspace = true }
num-traits = { workspace = true }
transceiver-messages = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

counters = { path = "../../lib/counters" }
derive-idol-err = { path = "../../lib/derive-idol-err" }
drv-fpga-api = { path = "../fpga-api" }
drv-front-io-api = { path = "../front-io-api" }
task-sensor-api = { path = "../../task/sensor-api" }
userlib = { path = "../../sys/userlib" }

[build-dependencies]
idol = { workspace = true }
build-i2c = { path = "../../build/i2c" }

[lib]
test = false
doctest = false
bench = false

[lints]
workspace = true
