name = "oxcon2023g0"
target = "thumbv6m-none-eabi"
chip = "../../chips/stm32g0"
memory = "memory-g030x6.toml"
board = "oxcon2023g0"

[kernel]
name = "oxcon2023g0"
requires = {flash = 11776, ram = 1296}
stacksize = 640

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 4096, ram = 512}
start = true
features = ["nano"]
stacksize = 368
notifications = ["fault", "timer"]

[tasks.sys]
name = "drv-stm32xx-sys"
priority = 1
max-sizes = {flash = 2048, ram = 256}
uses = ["rcc", "gpio", "system_flash"]
start = true
features = ["g030", "no-ipc-counters"]
stacksize = 256
task-slots = ["jefe"]

[tasks.user_leds]
name = "drv-user-leds"
features = ["stm32g0", "no-ipc-counters"]
priority = 3
max-sizes = {flash = 2048, ram = 256}
start = true
task-slots = ["sys"]
stacksize = 256
notifications = ["timer"]
config = { blink_at_start = [ "Led::Zero" ] }

[tasks.hiffy]
name = "task-hiffy"
priority = 4
max-sizes = {flash = 8192, ram = 4096}
start = true
task-slots = ["sys", "i2c_driver"]
stacksize = 912
features = ["stm32g0", "gpio", "i2c", "g030", "micro"]

[tasks.i2c_driver]
name = "drv-stm32xx-i2c-server"
features = ["g030", "no-ipc-counters"]
priority = 2
uses = ["i2c1"]
start = true
task-slots = ["sys"]
stacksize = 896
notifications = ["i2c1-irq"]

[tasks.i2c_driver.interrupts]
"i2c1.irq" = "i2c1-irq"

[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = {flash = 128, ram = 64}
stacksize = 64
start = true
features = ["insomniac"]

[config]
[[config.i2c.controllers]]
controller = 1

[config.i2c.controllers.ports.A]
scl.pin = 9
sda.pin = 10
af = 6
