[package]
name = "drv-stm32h7-dbgmcu"
version = "0.1.0"
edition = "2021"

[dependencies]
stm32h7 = { workspace = true }

[features]
h743 = ["stm32h7/stm32h743"]
h753 = ["stm32h7/stm32h753"]

[lib]
test = false
doctest = false
bench = false

[lints]
workspace = true
