[package]
name = "task-ping"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
panic-halt = "0.2.0"
cortex-m = "0.6.0"
userlib = {path = "../userlib"}

[[bin]]
name = "task-ping"
test = false
bench = false
