[package]
name = "task-power-api"
version = "0.1.0"
edition = "2021"

[dependencies]
hubpack.workspace = true
num-traits.workspace = true
pmbus.workspace = true
serde.workspace = true
static_assertions.workspace = true
zerocopy.workspace = true

drv-i2c-api = { path = "../../drv/i2c-api" }
userlib = { path = "../../sys/userlib" }

[build-dependencies]
idol.workspace = true
