[package]
name = "task-power-api"
version = "0.1.0"
edition = "2021"

[dependencies]
hubpack.workspace = true
num-traits.workspace = true
serde.workspace = true
zerocopy.workspace = true

derive-idol-err = { path = "../../lib/derive-idol-err"  }
userlib = { path = "../../sys/userlib" }

[build-dependencies]
idol.workspace = true
