target = "thumbv7em-none-eabihf"
chip = "../../chips/stm32h7"
memory = "memory-large.toml"
stacksize = 896
fwid = true

[kernel]
name = "medusa"
requires = {flash = 24600, ram = 6256}

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 16384, ram = 4096}
start = true
stacksize = 2200
notifications = ["fault", "timer"]
extern-regions = ["sram1", "sram2", "sram3", "sram4"]

[tasks.jefe.config.allowed-callers]
set_reset_reason = ["sys"]
request_reset = ["hiffy"]

[tasks.sys]
name = "drv-stm32xx-sys"
features = ["h753"]
priority = 1
uses = ["rcc", "gpios", "system_flash"]
start = true
task-slots = ["jefe"]

[tasks.update_server]
name = "stm32h7-update-server"
priority = 3
max-sizes = {flash = 16384, ram = 4096}
stacksize = 2048
start = true
uses = ["flash_controller"]
extern-regions = ["bank2"]
notifications = ["flash-irq"]
interrupts = {"flash_controller.irq" = "flash-irq"}

[caboose]
region = "flash"
size = 256

[tasks.hiffy]
name = "task-hiffy"
priority = 7
max-sizes = {flash = 32768, ram = 32768}
stacksize = 2048
start = true
task-slots = ["sys", "i2c_driver"]
features = ["turbo"]

[tasks.i2c_driver]
name = "drv-stm32xx-i2c-server"
features = ["h753"]
priority = 2
max-sizes = {flash = 16384, ram = 4096}
uses = ["i2c1", "i2c2", "i2c3", "i2c4"]
notifications = ["i2c1-irq", "i2c2-irq", "i2c3-irq", "i2c4-irq"]
start = true
task-slots = ["sys"]

[tasks.i2c_driver.interrupts]
"i2c1.event" = "i2c1-irq"
"i2c1.error" = "i2c1-irq"
"i2c2.event" = "i2c2-irq"
"i2c2.error" = "i2c2-irq"
"i2c3.event" = "i2c3-irq"
"i2c3.error" = "i2c3-irq"
"i2c4.event" = "i2c4-irq"
"i2c4.error" = "i2c4-irq"

[tasks.ecp5_front_io]
name = "drv-fpga-server"
features = ["front_io", "use-spi-core", "h753", "spi1"]
priority = 3
max-sizes = {flash = 32768, ram = 8192}
stacksize = 2048
start = true
uses = ["spi1"]
task-slots = ["sys", "i2c_driver"]
notifications = ["spi-irq"]
interrupts = {"spi1.irq" = "spi-irq"}

[tasks.monorail]
name = "task-monorail-server"
priority = 6
max-sizes = {flash = 262144, ram = 8192}
features = ["mgmt", "medusa", "vlan", "use-spi-core", "h753", "spi2"]
stacksize = 4096
start = true
task-slots = ["ecp5_front_io", "sys", { seq = "sequencer" }]
uses = ["spi2"]
notifications = ["spi-irq", "wake-timer"]
interrupts = {"spi2.irq" = "spi-irq"}

[tasks.net]
name = "task-net"
stacksize = 6040
priority = 5
features = ["mgmt", "h753", "medusa", "vlan", "vpd-mac", "use-spi-core", "spi3"]
max-sizes = {flash = 131072, ram = 65536, sram1_mac = 16384}
sections = {eth_bulk = "sram1_mac"}
uses = ["eth", "tim16", "spi3"]
start = true
notifications = ["eth-irq", "mdio-timer-irq", "spi-irq", "wake-timer"]
task-slots = ["sys", "packrat", { seq = "sequencer" }, "jefe"]

[tasks.net.interrupts]
"eth.irq" = "eth-irq"
"tim16.irq" = "mdio-timer-irq"
"spi3.irq" = "spi-irq"

[tasks.sequencer]
name = "drv-medusa-seq-server"
priority = 4
stacksize = 4096
start = true
task-slots = [
    "sys",
    "i2c_driver",
    "auxflash",
    "packrat",
    {front_io = "ecp5_front_io"}]

[tasks.transceivers]
name = "drv-transceivers-server"
features = ["vlan"]
priority = 6
max-sizes = {flash = 65536, ram = 16384}
stacksize = 4096
start = true
task-slots = [
    "i2c_driver",
    "net",
    "sensor",
    "sys",
    {front_io = "ecp5_front_io"},
    {seq = "sequencer"}]
notifications = ["socket", "timer"]

[tasks.packrat]
name = "task-packrat"
priority = 3
max-sizes = {flash = 8192, ram = 2048}
start = true
# task-slots is explicitly empty: packrat should not send IPCs!
task-slots = []

[tasks.validate]
name = "task-validate"
priority = 5
max-sizes = {flash = 16384, ram = 4096 }
stacksize = 1000
start = true
task-slots = ["i2c_driver"]

[tasks.sensor]
name = "task-sensor"
features = []
priority = 4
stacksize = 1024
start = true
notifications = ["timer"]

[tasks.vpd]
name = "task-vpd"
priority = 3
max-sizes = {flash = 8192, ram = 1024}
start = true
task-slots = ["sys", "i2c_driver"]
stacksize = 800

[tasks.idle]
name = "task-idle"
priority = 9
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[tasks.auxflash]
name = "drv-auxflash-server"
priority = 3
max-sizes = {flash = 32768, ram = 4096}
features = ["h753"]
uses = ["quadspi"]
start = true
notifications = ["qspi-irq"]
interrupts = {"quadspi.irq" = "qspi-irq"}
stacksize = 3504
task-slots = ["sys"]

[tasks.udpecho]
name = "task-udpecho"
priority = 6
max-sizes = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]
notifications = ["socket"]

[tasks.udpbroadcast]
name = "task-udpbroadcast"
priority = 6
max-sizes = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net", "packrat"]
features = ["vlan"]
notifications = ["socket"]

#
# Configuration
#
[config]

#
# Net
#

# VLAN configuration
[config.net.vlans.sidecar1]
vid = 0x301
trusted = true
port = 1

[config.net.vlans.sidecar2]
vid = 0x302
trusted = true
port = 2

[config.net.sockets.echo]
kind = "udp"
owner = {name = "udpecho", notification = "socket"}
port = 7
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.broadcast]
kind = "udp"
owner = {name = "udpbroadcast", notification = "socket"}
port = 997
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.transceivers]
kind = "udp"
owner = {name = "transceivers", notification = "socket"}
port = 11112
tx = { packets = 3, bytes = 2048 }
rx = { packets = 3, bytes = 2048 }

#
# Auxflash
#
[config.auxflash]
memory-size = 33_554_432 # 256 Mib / 32 MiB
slot-count = 16 # 2 MiB slots

[[auxflash.blobs]]
file = "drv/sidecar-front-io/sidecar_qsfp_x32_controller_rev_b_c.bit"
compress = true
tag = "QSFP"

#
# I2C1: Primary Bus
#
[[config.i2c.controllers]]
controller = 1

[config.i2c.controllers.ports.B1]
name = "primary"
description = "Primary I2C bus to all on-board devices"
scl = { gpio_port = "B", pin = 6 } # I2C_SP_TO_ALL_SCL
sda = { gpio_port = "B", pin = 7 } # I2C_SP_TO_ALL_SDA
af = 4

[[config.i2c.devices]]
bus = "primary"
address = 0b1010_100
device = "ltc4282"
description = "Front I/O hotswap controller"
power = { rails = [ "V12_SYS" ], pmbus = false }
sensors = { voltage = 1, current = 1 }
refdes = "U1"

[[config.i2c.devices]]
bus = "primary"
address = 0b1010_000
device = "at24csw080"
description = "Medusa FRUID"
name = "local_vpd"
refdes = "U9"

[[config.i2c.devices]]
bus = "primary"
address = 0b0011_001
device = "tps546b24a"
description = "V5P0_SYS rail"
power = { rails = [ "V5P0_SYS" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U10"

[[config.i2c.devices]]
bus = "primary"
address = 0b0011_010
device = "tps546b24a"
description = "V3P3_SYS rail"
power = { rails = [ "V3P3_SYS" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U11"

[[config.i2c.devices]]
bus = "primary"
address = 0b0011_100
device = "tps546b24a"
description = "V1P8_SYS rail"
power = { rails = [ "V1P8_SYS" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U12"

[[config.i2c.devices]]
bus = "primary"
address = 0b0011_011
device = "tps546b24a"
description = "V1P0_MGMT rail"
power = { rails = [ "V1P0_MGMT" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U13"

[[config.i2c.devices]]
bus = "primary"
address = 0b1000_000
device = "ltc4282"
description = "Front I/O hotswap controller"
power = { rails = [ "V12_QSFP_OUT" ], pmbus = false }
sensors = { voltage = 1, current = 1 }
refdes = "U16"

#
# I2C2: Front I/O 0
#
[[config.i2c.controllers]]
controller = 2
[config.i2c.controllers.ports.F]
name = "front_io0"
description = "Front I/O Board"
scl.pin = 1 # I2C_FRONT_IO0_SCL
sda.pin = 0 # I2C_FRONT_IO0_SDA
af = 4

[[config.i2c.devices]]
bus = "front_io0"
address = 0b1010_000
device = "at24csw080"
description = "Front IO board FRUID"
removable = true
refdes = [
    "J2", # on front IO board
    "U3",
]

[[config.i2c.devices]]
bus = "front_io0"
address = 0b1110_011
device = "pca9538"
description = "Front IO GPIO expander"
removable = true
refdes = [
    "J2", # on front IO board
    "U4",
]

[[config.i2c.devices]]
bus = "front_io0"
address = 0b0001_010
device = "pca9956b"
name = "front_leds_left"
description = "Front IO LED driver (left)"
removable = true
refdes = [
    "J2", # on front IO board
    "U5",
]

[[config.i2c.devices]]
bus = "front_io0"
address = 0b0001_011
device = "pca9956b"
name = "front_leds_right"
description = "Front IO LED driver (right)"
removable = true
refdes = [
    "J2", # on front IO board
    "U6",
]

[[config.i2c.devices]]
bus = "front_io0"
address = 0b0011_011
device = "tps546b24a"
description = "Front IO V3P3_SYS_A2 rail"
removable = true
power = {rails = ["V3P3_SYS_A2"] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = [
    "J2", # on front IO board
    "U7",
]

[[config.i2c.devices]]
bus = "front_io0"
address = 0b0011_001
device = "tps546b24a"
description = "Front IO V3P3_QSFP0_A0 rail"
removable = true
power = {rails = ["V3P3_QSFP0_A0"] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = [
    "J2", # on front IO board
    "U15",
]

[[config.i2c.devices]]
bus = "front_io0"
address = 0b0011_010
device = "tps546b24a"
description = "Front IO V3P3_QSFP1_A0 rail"
removable = true
power = {rails = ["V3P3_QSFP1_A0"] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = [
    "J2", # on front IO board
    "U18",
]

#
# I2C3: Front I/O 1
#
[[config.i2c.controllers]]
controller = 3
[config.i2c.controllers.ports.H]
name = "front_io1"
description = "Front I/O Board"
scl.pin = 7 # I2C_FRONT_IO1_SCL
sda.pin = 8 # I2C_FRONT_IO1_SDA
af = 4

#
# SPI1: Front IO FPGAs
#
[config.spi.spi1]
controller = 1

[config.spi.spi1.mux_options.port_adg]
outputs = [
    {port = "A", pins = [5], af = 5}, # SPI_SP_TO_FRONT_IO_SCK
    {port = "D", pins = [7], af = 5}, # SPI_SP_TO_FRONT_IO_MOSI
]
input = {port = "G", pin = 9, af = 5} # SPI_SP_TO_FRONT_IO_MISO

[config.spi.spi1.devices.ecp5_front_io_fpga]
mux = "port_adg"
cs = [{port = "G", pin = 10}] # SPI_SP_TO_FRONT_IO_CS_CFG_L

[config.spi.spi1.devices.ecp5_front_io_user_design]
mux = "port_adg"
cs = [{port = "A", pin = 15}] # SPI_SP_TO_FRONT_IO_CS_USER_L

#
# SPI2: VSC7448
#
[config.spi.spi2]
controller = 2

[config.spi.spi2.mux_options.port_i]
outputs = [
    # SPI_SP_TO_MGMT_SCK, SPI_SP_TO_MGMT_MOSI
    {port = "I", pins = [1, 3], af = 5},
]
input = {port = "I", pin = 2, af = 5} # SPI_SP_TO_MGMT_MISO

[config.spi.spi2.devices.vsc7448]
mux = "port_i"
cs = [{port = "I", pin = 0}] # SPI_SP_TO_MGMT_CS_L

#
# SPI3: KSZ8463
#
[config.spi.spi3]
controller = 3

[config.spi.spi3.mux_options.port_c]
outputs = [
    # SPI_SP_TO_EPE_SCK, SPI_SP_TO_EPE_MOSI
    {port = "C", pins = [10, 12], af = 6},
]
input = {port = "C", pin = 11, af = 6} # SPI_SP_TO_EPE_MISO

[config.spi.spi3.devices.ksz8463]
mux = "port_c"
cs = [{port = "A", pin = 4}] # SPI_SP_TO_EPE_CS_L

#
# QSFP Module Temperature Sensors
#
[[config.sensor.devices]]
name = "xcvr0"
device = "qsfp"
description = "QSFP transceiver 0"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr1"
device = "qsfp"
description = "QSFP transceiver 1"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr2"
device = "qsfp"
description = "QSFP transceiver 2"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr3"
device = "qsfp"
description = "QSFP transceiver 3"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr4"
device = "qsfp"
description = "QSFP transceiver 4"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr5"
device = "qsfp"
description = "QSFP transceiver 5"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr6"
device = "qsfp"
description = "QSFP transceiver 6"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr7"
device = "qsfp"
description = "QSFP transceiver 7"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr8"
device = "qsfp"
description = "QSFP transceiver 8"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr9"
device = "qsfp"
description = "QSFP transceiver 9"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr10"
device = "qsfp"
description = "QSFP transceiver 10"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr11"
device = "qsfp"
description = "QSFP transceiver 11"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr12"
device = "qsfp"
description = "QSFP transceiver 12"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr13"
device = "qsfp"
description = "QSFP transceiver 13"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr14"
device = "qsfp"
description = "QSFP transceiver 14"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr15"
device = "qsfp"
description = "QSFP transceiver 15"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr16"
device = "qsfp"
description = "QSFP transceiver 16"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr17"
device = "qsfp"
description = "QSFP transceiver 17"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr18"
device = "qsfp"
description = "QSFP transceiver 18"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr19"
device = "qsfp"
description = "QSFP transceiver 19"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr20"
device = "qsfp"
description = "QSFP transceiver 20"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr21"
device = "qsfp"
description = "QSFP transceiver 21"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr22"
device = "qsfp"
description = "QSFP transceiver 22"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr23"
device = "qsfp"
description = "QSFP transceiver 23"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr24"
device = "qsfp"
description = "QSFP transceiver 24"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr25"
device = "qsfp"
description = "QSFP transceiver 25"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr26"
device = "qsfp"
description = "QSFP transceiver 26"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr27"
device = "qsfp"
description = "QSFP transceiver 27"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr28"
device = "qsfp"
description = "QSFP transceiver 28"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr29"
device = "qsfp"
description = "QSFP transceiver 29"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr30"
device = "qsfp"
description = "QSFP transceiver 30"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr31"
device = "qsfp"
description = "QSFP transceiver 31"
sensors.temperature = 1
