[package]
name = "kern"
version = "0.1.0"
edition = "2021"

[dependencies]
abi = {path = "../abi"}
zerocopy = "0.6.1"
byteorder = { version = "1.3.4", default-features = false }
bitflags = "1.2.1"
cfg-if = "1"
serde = { version = "1.0.114", default-features = false }
ssmarshal = { version = "1.0.0", default-features = false }
unwrap-lite = { path = "../../lib/unwrap-lite" }
phash = { path = "../../lib/phash" }

[target.thumbv6m-none-eabi.dependencies]
cortex-m = {version = "0.7", features = ["inline-asm"]}

[target.thumbv7em-none-eabihf.dependencies]
cortex-m = {version = "0.7", features = ["inline-asm"]}

[target."thumbv8m.main-none-eabihf".dependencies]
cortex-m = {version = "0.7", features = ["inline-asm"]}

[build-dependencies]
build-util = {path = "../../build/util"}
serde = "1"
ron = "0.7"
abi = {path = "../abi"}
phash-gen = {path = "../../build/phash-gen"}
anyhow = "1.0.66"
proc-macro2 = "1.0.32"
syn = { version = "1.0.94", features = ["parsing"] }
quote = "1.0.10"
call_rustfmt = {path = "../../build/call_rustfmt"}
build-kconfig = {path = "../../build/kconfig"}
indexmap = "1.9.1"

[lib]
bench = false
