[package]
name = "task-thermal-sensors"
description = "Monitoring-only task for temperature and fan sensors"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = {version = "0.7", features = ["inline-asm"]}
zerocopy = "0.6.1"

drv-i2c-api = {path = "../../drv/i2c-api"}
drv-i2c-devices = { path = "../../drv/i2c-devices" }
ringbuf = {path = "../../lib/ringbuf" }
task-sensor-api = {path = "../sensor-api"}
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}

[build-dependencies]
build-util = {path = "../../build/util"}
build-i2c = {path = "../../build/i2c"}
anyhow = "1.0.31"

[[bin]]
name = "task-thermal-sensors"
test = false
bench = false
