board = "grapefruit"
target = "thumbv7em-none-eabihf"
chip = "../../chips/stm32h7"
memory = "memory-large.toml"
stacksize = 896
epoch = 0
version = 0

[mmio]
peripheral-region = "fmc_nor_psram_bank_1"
register-map = "../../drv/spartan7-loader/grapefruit/gfruit_top.json"

[kernel]
name = "grapefruit"
requires = {flash = 32768, ram = 8192}
features = ["dump", "measurement-handoff"]
extern-regions = ["dtcm"]

[caboose]
tasks = ["control_plane_agent", "packrat"]
region = "flash"
size = 256
default = true

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 16384, ram = 4096}
start = true
stacksize = 3000
notifications = ["fault", "timer"]
features = ["dump"]
extern-regions = ["sram1", "sram2", "sram3", "sram4"]

[tasks.jefe.config.allowed-callers]
set_reset_reason = ["sys"]
set_state = ["grapefruit_seq"]
request_reset = ["hiffy", "udprpc", "control_plane_agent"]

[tasks.sys]
name = "drv-stm32xx-sys"
# Enable EXTI in the sys task so that we can notify sprot when the RoT
# raises an IRQ.
features = ["h753", "exti"]
priority = 1
max-sizes = {flash = 4096, ram = 2048}
uses = ["rcc", "gpios", "system_flash", "syscfg", "exti"]
start = true
task-slots = ["jefe"]
notifications = ["exti-wildcard-irq"]

[tasks.sys.interrupts]
"exti.exti0" = "exti-wildcard-irq"
"exti.exti1" = "exti-wildcard-irq"
"exti.exti2" = "exti-wildcard-irq"
"exti.exti3" = "exti-wildcard-irq"
"exti.exti4" = "exti-wildcard-irq"
"exti.exti9_5" = "exti-wildcard-irq"
"exti.exti15_10" = "exti-wildcard-irq"

[tasks.sys.config.gpio-irqs.rot_irq]
port = "F"
pin = 2
owner = {name = "sprot", notification = "rot_irq"}

[tasks.spi2_driver]
name = "drv-stm32h7-spi-server"
priority = 2
max-sizes = {flash = 16384, ram = 4096}
features = ["spi2", "h753"]
uses = ["spi2"]
start = true
interrupts = {"spi2.irq" = "spi-irq"}
stacksize = 872
task-slots = ["sys"]
notifications = ["spi-irq"]

[tasks.i2c_driver]
name = "drv-stm32xx-i2c-server"
stacksize = 1048
features = ["h753"]
priority = 2
max-sizes = {flash = 16384, ram = 4096}
uses = ["i2c1", "i2c2", "i2c3", "i2c4"]
start = true
task-slots = ["sys"]
notifications = ["i2c1-irq", "i2c2-irq", "i2c3-irq", "i2c4-irq"]

[tasks.i2c_driver.interrupts]
"i2c1.event" = "i2c1-irq"
"i2c1.error" = "i2c1-irq"
"i2c2.event" = "i2c2-irq"
"i2c2.error" = "i2c2-irq"
"i2c3.event" = "i2c3-irq"
"i2c3.error" = "i2c3-irq"
"i2c4.event" = "i2c4-irq"
"i2c4.error" = "i2c4-irq"

[tasks.user_leds]
name = "drv-user-leds"
features = ["stm32h7"]
priority = 5
max-sizes = {flash = 2048, ram = 1024}
start = true
task-slots = ["sys"]
notifications = ["timer"]

[tasks.packrat]
name = "task-packrat"
priority = 1
start = true
# task-slots is explicitly empty: packrat should not send IPCs!
task-slots = []
features = ["grapefruit", "boot-kmdb"]

[tasks.hiffy]
name = "task-hiffy"
priority = 7
max-sizes = {flash = 32768, ram = 65536}
stacksize = 2048
start = true
features = ["h753", "stm32h7", "i2c", "gpio", "sprot", "qspi", "hash", "turbo"]
task-slots = ["i2c_driver", "sys", "user_leds", "sprot", "hf", "hash_driver"]

[tasks.validate]
name = "task-validate"
priority = 3
max-sizes = {flash = 32768, ram = 4096}
stacksize = 1024
start = true
task-slots = ["i2c_driver"]

[tasks.hash_driver]
name = "drv-stm32h7-hash-server"
features = ["h753"]
priority = 2
max-sizes = {flash = 16384, ram=4096 }
stacksize = 2048
start = true
uses = ["hash"]
interrupts = {"hash.irq" = "hash-irq"}
task-slots = ["sys"]
notifications = ["hash-irq"]

[tasks.idle]
name = "task-idle"
priority = 9
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[tasks.dump_agent]
name = "task-dump-agent"
priority = 6
max-sizes = {flash = 32768, ram = 16384 }
start = true
task-slots = ["jefe", "net", "sprot"]
stacksize = 2400
extern-regions = ["sram1", "sram2", "sram3", "sram4"]
notifications = ["socket"]
features = ["net", "vlan"]

[tasks.sprot]
name = "drv-stm32h7-sprot-server"
priority = 5
max-sizes = {flash = 65536, ram = 32768}
stacksize = 16384
start = true
task-slots = ["sys"]
features = ["sink_test", "use-spi-core", "h753", "spi4"]
uses = ["spi4"]
notifications = ["spi-irq", "rot-irq", "timer"]
interrupts = {"spi4.irq" = "spi-irq"}

[tasks.grapefruit_seq]
name = "drv-grapefruit-seq-server"
features = ["h753"]
priority = 5
max-sizes = {flash = 131072, ram = 16384 }
stacksize = 2600
start = true
task-slots = ["sys", "jefe", "packrat", "spartan7_loader"]
uses = ["mmio_sgpio", "mmio_espi"]

[tasks.spartan7_loader]
name = "drv-spartan7-loader"
features = ["h753"]
priority = 4
max-sizes = {flash = 131072, ram = 16384 }
stacksize = 2600
start = true
task-slots = ["sys", {spi = "spi2_driver"}, "auxflash"]

[tasks.spartan7_loader.config]
program_l = "sys_api::Port::B.pin(6)"
init_l = "sys_api::Port::B.pin(5)"
config_done = "sys_api::Port::B.pin(4)"
user_reset_l = "sys_api::Port::I.pin(15)"

[tasks.update_server]
name = "stm32h7-update-server"
priority = 3
max-sizes = {flash = 16384, ram = 4096}
stacksize = 2048
start = true
uses = ["flash_controller"]
extern-regions = ["bank2"]
interrupts = {"flash_controller.irq" = "flash-irq"}
notifications = ["flash-irq"]

[tasks.sensor]
name = "task-sensor"
priority = 4
max-sizes = {flash = 16384, ram = 8192 }
stacksize = 1024
start = true

# Note that host_sp_comms does not specify a UART!  It must be fully specified
# with features + uses + interrupts by manifests inheriting from this file.
[tasks.host_sp_comms]
name = "task-host-sp-comms"
features = ["stm32h753", "baud_rate_3M", "vlan", "grapefruit"]
uses = ["dbgmcu"]
priority = 8
max-sizes = {flash = 65536, ram = 65536}
stacksize = 5080
start = true
task-slots = ["sys", "hf", "packrat", "control_plane_agent", "net",  { cpu_seq = "grapefruit_seq" }, { spi_driver = "spi2_driver" }, "sprot", "auxflash"]
notifications = ["jefe-state-change", "usart-irq", "multitimer", "control-plane-agent"]

[tasks.control_plane_agent]
name = "task-control-plane-agent"
priority = 7
stacksize = 7000
start = true
uses = ["usart1"]
task-slots = [
    "auxflash",
    "dump_agent",
    "jefe",
    "net",
    "update_server",
    "sys",
    "hf",
    { cpu_seq = "grapefruit_seq" },
    "validate",
    "sensor",
    "sprot",
    "packrat",
    "user_leds",
]
features = [
    "auxflash",
    "cosmo", # close enough!
    "usart1",
    "vlan",
    "baud_rate_3M",
]
notifications = ["usart-irq", "socket", "timer"]
interrupts = {"usart1.irq" = "usart-irq"}


[tasks.auxflash]
name = "drv-auxflash-server"
priority = 3
max-sizes = {flash = 32768, ram = 4096}
features = ["h753", "fast-qspi"]
uses = ["quadspi"]
start = true
notifications = ["qspi-irq"]
interrupts = {"quadspi.irq" = "qspi-irq"}
stacksize = 3504
task-slots = ["sys"]

[tasks.net]
name = "task-net"
stacksize = 8000
priority = 3
features = ["h753", "vlan", "grapefruit"]
max-sizes = {flash = 131072, ram = 65536, sram1_mac = 16384}
sections = {eth_bulk = "sram1_mac"}
uses = ["eth", "tim16"]
start = true
task-slots = ["sys", "jefe", { spi_driver = "spi2_driver" }]
notifications = ["eth-irq", "mdio-timer-irq", "spi-irq", "wake-timer"]

[tasks.net.interrupts]
"eth.irq" = "eth-irq"
"tim16.irq" = "mdio-timer-irq"

[tasks.udprpc]
name = "task-udprpc"
priority = 6
max-sizes = {flash = 32768, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]
notifications = ["socket"]

[tasks.udpecho]
name = "task-udpecho"
priority = 4
max-sizes = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]
notifications = ["socket"]

[tasks.udpbroadcast]
name = "task-udpbroadcast"
priority = 6
max-sizes = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net", "packrat"]
features = ["vlan"]
notifications = ["socket"]

[tasks.fmc_demo]
name = "drv-stm32h7-fmc-demo-server"
features = ["h753"]
priority = 4
start = true
task-slots = ["sys", "net"]
uses = ["mmio_base", "mmio_spi_nor", "mmio_espi", "mmio_sgpio"]
notifications = ["socket"]

[tasks.hf]
name = "drv-cosmo-hf"
priority = 5
start = true
uses = ["mmio_base", "mmio_spi_nor"]
task-slots = ["hash_driver", "spartan7_loader"]
stacksize = 4000
notifications = ["timer"]

[config.net]
# VLAN configuration
[config.net.vlans.sidecar1]
vid = 0x301
trusted = true
port = 1

[config.net.vlans.sidecar2]
vid = 0x302
trusted = true
port = 2
# UDP ports in sockets below are assigned in oxidecomputer/oana

[config.net.sockets.broadcast]
kind = "udp"
owner = {name = "udpbroadcast", notification = "socket"}
port = 997
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.echo]
kind = "udp"
owner = {name = "udpecho", notification = "socket"}
port = 7
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.rpc]
kind = "udp"
owner = {name = "udprpc", notification = "socket"}
port = 998
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.control_plane_agent]
kind = "udp"
owner = {name = "control_plane_agent", notification = "socket"}
port = 11111
tx = { packets = 3, bytes = 2048 }
rx = { packets = 3, bytes = 2048 }

[config.net.sockets.dump_agent]
kind = "udp"
owner = {name = "dump_agent", notification = "socket"}
port = 11113
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.fmc_test]
kind = "udp"
owner = {name = "fmc_demo", notification = "socket"}
port = 11114
tx = { packets = 3, bytes = 4096 }
rx = { packets = 3, bytes = 4096 }

################################################################################

[config]
[[config.i2c.controllers]]
controller = 1

[config.i2c.controllers.ports.B]
name = "fpga"
sda.pin = 8
scl.pin = 9
af = 4

################################################################################

[config.spi.spi2]
controller = 2

[config.spi.spi2.mux_options.port_i]
outputs = [
    {port = "I", pins = [1, 3], af = 5},
]
input = {port = "I", pin = 2, af = 5}

[config.spi.spi2.devices.ksz8463]
mux = "port_i"
cs = [{port = "I", pin = 0}]

[config.spi.spi2.mux_options.port_b]
outputs = [
    {port = "B", pins = [13, 15], af = 5},
]
input = {port = "B", pin = 14, af = 5} # not actually used in FPGA config

[config.spi.spi2.devices.spartan7_fpga]
mux = "port_b"
cs = []
clock_divider = "DIV8" # 12.5 MHz
# no CS pin; we're using the SPI peripheral to send synchronized CLK + DATA

[config.spi.spi4]
controller = 4

[config.spi.spi4.mux_options.port_e]
outputs = [
    {port = "E", pins = [2, 6], af = 5},
]
input = {port = "E", pin = 5, af = 5}

[config.spi.spi4.devices.rot]
mux = "port_e"
cs = [{port = "E", pin = 4}]
clock_divider = "DIV256"

################################################################################

[config.auxflash]
memory-size = 33_554_432 # 256 Mib / 32 MiB
slot-count = 16 # 2 MiB slots

[[auxflash.blobs]]
file = "drv/spartan7-loader/grapefruit/grapefruit.bz2"
unzip = "bz2"
compress = true
tag = "SPA7" # used by drv-spartan7-loader
