[package]
name = "grapefruit"
edition = "2021"
readme = "README.md"
version = "0.1.0"

[features]
dump = ["kern/dump"]
measurement-handoff = ["drv-stm32h7-startup/measurement-handoff"]

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
cfg-if = { workspace = true }
stm32h7 = { workspace = true, features = ["rt", "stm32h753"] }

drv-stm32h7-startup = { path = "../../drv/stm32h7-startup", features = ["h753"] }
kern = { path = "../../sys/kern" }

[build-dependencies]
build-util = {path = "../../build/util"}

# this lets you use `cargo fix`!
[[bin]]
name = "grapefruit"
test = false
doctest = false
bench = false

[lints]
workspace = true
