[package]
name = "stage0"
version = "0.1.0"
edition = "2018"

[features]
dice = ["dice_crate", "digest", "salty", "sha3", "unwrap-lite"]
tz_support = []

[dependencies]
cortex-m = {version = "0.7", features = ["inline-asm"]}
cortex-m-rt = "0.6.12"
digest = { version = "0.10", optional = true }
panic-semihosting = "0.5.3"
lpc55_romapi = { path = "../drv/lpc55-romapi" }
panic-halt = "0.2.0"
lpc55-pac = {version = "0.4", features = ["rt"]}
ecdsa = { version = "0.12.4", default-features = false, features = ["der"] }
p256 = { version = "0.9.0", default-features = false, features = ["ecdsa", "ecdsa-core"] }
hmac = { version = "0.10.1", default-features = false }
sha3 = { version = "0.10", default-features = false, optional = true }
zerocopy = "0.6.1"
abi = { path = "../sys/abi" }
unwrap-lite = { path = "../lib/unwrap-lite", optional = true }
nb = "1"

# features & deps can't have the same name, using this method from:
# https://github.com/RustCrypto/RSA/pull/41/files
[dependencies.dice_crate]
package = "dice"
path = "../lib/dice"
default-features = false
optional = true

[dependencies.salty]
git = "https://github.com/oxidecomputer/salty"
rev = "eb3c31858f631a7fb9934246c8efdef080d05726"
optional = true

[[bin]]
name = "stage0"
test = false
bench = false

