[package]
name = "stage0"
version = "0.1.0"
authors = ["Laura Abbott <laura@oxide.computer>"]
edition = "2018"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.6.12"
cortex-m-semihosting = "0.3.5"
panic-semihosting = "0.5.3"
lpc55_romapi = { path = "../drv/lpc55-romapi" }
panic-halt = "0.2.0"
lpc55-pac = "0.3.0"
ecdsa = { version = "0.12.4", default-features = false, features = ["der"] }
p256 = { version = "0.9.0", default-features = false, features = ["ecdsa", "ecdsa-core"] }
hmac = { version = "0.10.1", default-features = false }
sha2 = { version = "0.9.2", default-features = false }
zerocopy = "0.3.0"

[package.metadata.build]
target = "thumbv8m.main-none-eabihf"

[[bin]]
name = "stage0"
test = false
bench = false

