[package]
name = "drv-stm32h7-gpio"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

[dependencies]
userlib = {path = "../../userlib"}
zerocopy = "0.3.0"
byteorder = { version = "1.3.4", default-features = false }
num-traits = { version = "0.2.12", default-features = false }
drv-stm32h7-rcc-api = {path = "../stm32h7-rcc-api", default-features = false }
stm32h7 = { version = "0.13.0", default-features = false }
cortex-m = { version = "0.7", features = ["inline-asm"] }

[features]
default = ["standalone"]
standalone = ["h753"]
h743 = ["stm32h7/stm32h743", "drv-stm32h7-rcc-api/h743"]
h753 = ["stm32h7/stm32h753", "drv-stm32h7-rcc-api/h753"]
h7b3 = ["stm32h7/stm32h7b3", "drv-stm32h7-rcc-api/h7b3"]

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-stm32h7-gpio"
test = false
bench = false
