# This is the production image. We expect `name` to match `board`
name = "gimlet-b"
board = "gimlet-b"
inherit = "base.toml"

#
# I2C2: Front/M.2 bus
#
[[config.i2c.controllers]]
controller = 2

#
# SMBUS_SP_TO_M2_SMCLK_A2_V3P3
# SMBUS_SP_TO_M2_SMDAT_A2_V3P3
#
[config.i2c.controllers.ports.B]
name = "m2"
description = "M.2 bus"
scl.pin = 10
sda.pin = 11
af = 4
[[config.i2c.controllers.ports.B.muxes]]
driver = "pca9545"
address = 0x73

#
# SMBUS_SP_TO_LVL_FRONT_SMDAT
# SMBUS_SP_TO_LVL_FRONT_SMCLK
#
[config.i2c.controllers.ports.F]
name = "front"
description = "Front bus"
scl.pin = 1
sda.pin = 0
af = 4

#
# Shark fin muxes
#
[[config.i2c.controllers.ports.F.muxes]]
driver = "pca9545"
address = 0x70

[[config.i2c.controllers.ports.F.muxes]]
driver = "pca9545"
address = 0x71

[[config.i2c.controllers.ports.F.muxes]]
driver = "pca9545"
address = 0x72

[[config.i2c.devices]]
bus = "m2"
mux = 1
segment = 1
address = 0b110_1010
device = "m2_hp_only"
description = "M.2 A NVMe Basic Management Command"
name = "M2_A"
refdes = "P1"
sensors = { temperature = 1 }
removable = true

[[config.i2c.devices]]
bus = "m2"
mux = 1
segment = 2
address = 0b110_1010
device = "m2_hp_only"
description = "M.2 B NVMe Basic Management Command"
name = "M2_B"
refdes = "P2"
sensors = { temperature = 1 }
removable = true
