name = "gimlet-b"
target = "thumbv7em-none-eabihf"
board = "gimlet-b"
chip = "../../chips/stm32h7.toml"
stacksize = 896

[kernel]
path = "."
name = "gimlet"
requires = {flash = 32768, ram = 8192}
#
# For the kernel (and for any task that logs), we are required to enable
# either "itm" (denoting logging/panicking via ARM's Instrumentation Trace
# Macrocell) or "semihosting" (denoting logging/panicking via ARM
# semihosting).  We are biased to ITM because semihosting is excruciatingly
# slow (it is breakpoint based) and has an undesirable failure mode if logging
# output is generated and debugger is not attached (namely, the target stops).
# If one does choose to change this to semihosting for purposes of
# development, be sure to also change it in every task of interest.
#
features = ["itm"]

[supervisor]
notification = 1

# Flash sections are mapped into flash bank 1 (of 2).
[outputs.flash]
address = 0x08000000
size = 1048576
read = true
execute = true

# RAM sections are currently mapped into DTCM, a small but fast SRAM.
[outputs.ram]
address = 0x20000000
size = 131072
read = true
write = true
execute = false  # let's assume XN until proven otherwise

# Network buffers are placed in sram1, which is directly accessible by the
# Ethernet MAC.
[outputs.sram1]
address = 0x30000000
size = 0x20000
read = true
write = true
dma = true

[tasks.jefe]
path = "../../task/jefe"
name = "task-jefe"
priority = 0
requires = {flash = 8192, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536

[tasks.net]
path = "../../task/net"
name = "task-net"
stacksize = 5400
priority = 2
features = ["mgmt", "h753", "gimlet", "h7-vlan"]
requires = {flash = 131072, ram = 16384, sram1 = 16384}
sections = {eth_bulk = "sram1"}
uses = ["eth", "eth_dma", "system_flash"]
start = true
interrupts = {"eth.irq" = 0b1}
task-slots = ["sys", { spi_driver = "spi2_driver" }, { seq = "gimlet_seq" }]

[tasks.sys]
path = "../../drv/stm32xx-sys"
name = "drv-stm32xx-sys"
features = ["h753"]
priority = 1
requires = {flash = 2048, ram = 1024}
uses = ["rcc", "gpios1", "gpios2", "gpios3"]
start = true

[tasks.spi4_driver]
path = "../../drv/stm32h7-spi-server"
name = "drv-stm32h7-spi-server"
priority = 2
requires = {flash = 16384, ram = 2048}
features = ["spi4", "h753"]
uses = ["spi4"]
start = true
interrupts = {"spi4.irq" = 1}
stacksize = 872
task-slots = ["sys"]

[tasks.spi4_driver.config.spi]
global_config = "spi4"

[tasks.spi2_driver]
path = "../../drv/stm32h7-spi-server"
name = "drv-stm32h7-spi-server"
priority = 2
requires = {flash = 16384, ram = 2048}
features = ["spi2", "h753"]
uses = ["spi2"]
start = true
interrupts = {"spi2.irq" = 1}
stacksize = 872
task-slots = ["sys"]

[tasks.spi2_driver.config.spi]
global_config = "spi2"

[tasks.i2c_driver]
path = "../../drv/stm32h7-i2c-server"
name = "drv-stm32h7-i2c-server"
features = ["h753", "itm"]
priority = 2
requires = {flash = 16384, ram = 2048}
uses = ["i2c2", "i2c3", "i2c4"]
start = true
task-slots = ["sys"]

[tasks.i2c_driver.interrupts]
"i2c2.event" = 0b0000_0010
"i2c2.error" = 0b0000_0010
"i2c3.event" = 0b0000_0100
"i2c3.error" = 0b0000_0100
"i2c4.event" = 0b0000_1000
"i2c4.error" = 0b0000_1000

[tasks.spd]
path = "../../task/spd"
name = "task-spd"
features = ["h753", "itm"]
priority = 2
requires = {flash = 16384, ram = 16384}
uses = ["i2c1"]
start = true
task-slots = ["sys", "i2c_driver"]

[tasks.spd.interrupts]
"i2c1.event" = 0b0000_0001
"i2c1.error" = 0b0000_0001

[tasks.thermal]
path = "../../task/thermal"
name = "task-thermal"
features = ["itm", "h753"]
priority = 3
requires = {flash = 16384, ram = 4096 }
stacksize = 3504
start = true
task-slots = ["i2c_driver", "sensor"]

[tasks.power]
path = "../../task/power"
name = "task-power"
features = ["itm", "h753"]
priority = 3
requires = {flash = 16384, ram = 4096 }
stacksize = 2048
start = true
task-slots = ["i2c_driver", "sensor", "gimlet_seq"]

[tasks.hiffy]
path = "../../task/hiffy"
name = "task-hiffy"
features = ["h753", "stm32h7", "itm", "i2c", "gpio", "spi", "qspi"]
priority = 3
requires = {flash = 32768, ram = 32768 }
stacksize = 1024
start = true
task-slots = ["sys", "hf", "i2c_driver"]

[tasks.gimlet_seq]
path = "../../drv/gimlet-seq-server"
name = "drv-gimlet-seq-server"
features = ["h753"]
priority = 3
requires = {flash = 65536, ram = 4096 }
stacksize = 1600
start = true
task-slots = ["sys", "i2c_driver", {spi_driver = "spi2_driver"}, "hf"]

[tasks.gimlet_seq.config]
fpga_image = "fpga-b.bin"
register_defs = "gimlet_regs.json"

[tasks.hf]
path = "../../drv/gimlet-hf-server"
name = "drv-gimlet-hf-server"
features = ["h753"]
priority = 3
requires = {flash = 16384, ram = 2048 }
stacksize = 1920
start = true
uses = ["quadspi"]
interrupts = {"quadspi.irq" = 1}
task-slots = ["sys"]

[tasks.sensor]
path = "../../task/sensor"
name = "task-sensor"
features = ["itm"]
priority = 3
requires = {flash = 8192, ram = 2048 }
stacksize = 1920        # Sensor data is stored on the stack
start = true

[tasks.udpecho]
path = "../../task/udpecho"
name = "task-udpecho"
priority = 3
requires = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]

[tasks.udpbroadcast]
path = "../../task/udpbroadcast"
name = "task-udpbroadcast"
priority = 3
requires = {flash = 16384, ram = 8192}
stacksize = 2048
start = true
task-slots = ["net"]
features = ["vlan"]

[tasks.validate]
path = "../../task/validate"
name = "task-validate"
priority = 3
requires = {flash = 8192, ram = 4096 }
stacksize = 1000 
start = true
task-slots = ["i2c_driver"]

[tasks.idle]
path = "../../task/idle"
name = "task-idle"
priority = 5
requires = {flash = 128, ram = 256}
stacksize = 256
start = true

[config]

#
# I2C1: SPD proxy bus
#
[[config.i2c.controllers]]
controller = 1
target = true

#
# SMBUS_SPD_PROXY_SP3_TO_SP_SMCLK
# SMBUS_SPD_PROXY_SP3_TO_SP_SMDAT
#
[config.i2c.controllers.ports.B]
name = "spd"
description = "SPD proxy"
pins = [ { pins = [ 6, 7 ], af = 4 } ]

#
# I2C2: Front/M.2 bus
#
[[config.i2c.controllers]]
controller = 2

#
# SMBUS_SP_TO_M2_SMCLK_A2_V3P3
# SMBUS_SP_TO_M2_SMDAT_A2_V3P3
#
[config.i2c.controllers.ports.B]
name = "m2"
description = "M.2 bus"
pins = [ { pins = [ 10, 11 ], af = 4 } ]
muxes = [ { driver = "pca9548", address = 0x73 } ]

#
# SMBUS_SP_TO_LVL_FRONT_SMDAT
# SMBUS_SP_TO_LVL_FRONT_SMCLK
#
[config.i2c.controllers.ports.F]
name = "front"
description = "Front bus"
pins = [ { pins = [ 0, 1 ], af = 4 } ]

#
# Shark fin muxes
#
[[config.i2c.controllers.ports.F.muxes]]
driver = "pca9548"
address = 0x70

[[config.i2c.controllers.ports.F.muxes]]
driver = "pca9548"
address = 0x71

[[config.i2c.controllers.ports.F.muxes]]
driver = "pca9548"
address = 0x72

#
# I2C3: Mid bus
#
[[config.i2c.controllers]]
controller = 3

#
# SMBUS_SP_TO_LVL_MID_SMCLK
# SMBUS_SP_TO_LVL_MID_SMDAT
#
[config.i2c.controllers.ports.H]
name = "mid"
description = "Mid bus"
pins = [ { pins = [ 7, 8 ], af = 4 } ]

#
# I2C4: Rear bus
#
[[config.i2c.controllers]]
controller = 4

#
# SMBUS_SP_TO_LVL_REAR_SMCLK
# SMBUS_SP_TO_LVL_REAR_SMDAT
#
[config.i2c.controllers.ports.F]
name = "rear"
description = "Rear bus"
pins = [ { pins = [ 14, 15 ], af = 4 } ]

[[config.i2c.devices]]
bus = "front"
address = 0x48
device = "tmp117"
name = "Southwest"
description = "Southwest temperature sensor"
sensors = { temperature = 1 }
removable = true
refdes = "J194"

[[config.i2c.devices]]
bus = "front"
address = 0x49
device = "tmp117"
name = "South"
description = "South temperature sensor"
sensors = { temperature = 1 }
removable = true
refdes = "J195"

[[config.i2c.devices]]
bus = "front"
address = 0x4a
device = "tmp117"
name = "Southeast"
description = "Southeast temperature sensor"
sensors = { temperature = 1 }
removable = true
refdes = "J196"

[[config.i2c.devices]]
bus = "front"
address = 0x70
device = "pca9545"
description = "U.2 ABCD mux"
refdes = "U336"

[[config.i2c.devices]]
bus = "front"
address = 0x71
device = "pca9545"
description = "U.2 EFGH mux"
refdes = "U339"

[[config.i2c.devices]]
bus = "front"
address = 0x72
device = "pca9545"
description = "U.2 IJ/FRUID mux"
refdes = "U337"

[[config.i2c.devices]]
bus = "m2"
address = 0x73
device = "pca9545"
description = "M.2 mux"
refdes = "U422"

[[config.i2c.devices]]
bus = "m2"
mux = 1
segment = 4
address = 0x4c
device = "tmp451"
sensors = { temperature = 1 }
description = "T6 temperature sensor"
refdes = "U491"

[[config.i2c.devices]]
bus = "mid"
address = 0x24
device = "tps546b24a"
description = "A2 3.3V rail"
pmbus = { rails = [ "V3P3_SP_A2" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U522"

[[config.i2c.devices]]
bus = "mid"
address = 0x26
device = "tps546b24a"
description = "A0 3.3V rail"
pmbus = { rails = [ "V3P3_SYS_A0" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U560"

[[config.i2c.devices]]
bus = "mid"
address = 0x27
device = "tps546b24a"
description = "A2 5V rail"
pmbus = { rails = [ "V5_SYS_A2" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U524"

[[config.i2c.devices]]
bus = "mid"
address = 0x29
device = "tps546b24a"
description = "A2 1.8V rail"
pmbus = { rails = [ "V1P8_SYS_A2" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U561"

[[config.i2c.devices]]
bus = "mid"
address = 0x3a
device = "max5970"
description = "M.2 hot plug controller"
refdes = "U275"

[[config.i2c.devices]]
bus = "mid"
address = 0x4c
device = "sbtsi"
name = "CPU"
description = "CPU temperature sensor"
sensors = { temperature = 1 }

[[config.i2c.devices]]
bus = "mid"
address = 0x58
device = "idt8a34003"
description = "Clock generator"
refdes = "U446"

[[config.i2c.devices]]
bus = "mid"
address = 0x5a
device = "raa229618"
description = "CPU power controller"
pmbus = { rails = [ "VDD_VCORE", "VDD_MEM_ABCD" ] }
sensors = { temperature = 2, power = 2, voltage = 2, current = 2 }
refdes = "U350"

[[config.i2c.devices]]
bus = "mid"
address = 0x5b
device = "raa229618"
description = "SoC power controller"
pmbus = { rails = [ "VDDCR_SOC", "VDD_MEM_EFGH" ] }
sensors = { temperature = 2, power = 2, voltage = 2, current = 2 }
refdes = "U351"

[[config.i2c.devices]]
bus = "mid"
address = 0x5c
device = "isl68224"
description = "DIMM/SP3 1.8V A0 power controller"
pmbus = { rails = [ "VPP_ABCD", "VPP_EFGH", "V1P8_SP3" ] }
sensors = { voltage = 3, current = 3 }
refdes = "U352"

[[config.i2c.devices]]
bus = "rear"
address = 0x10
device = "adm1272"
description = "Fan hot swap controller"
pmbus = { rails = [ "V54_FAN" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U419"

[[config.i2c.devices]]
bus = "rear"
address = 0x14
device = "adm1272"
description = "Sled hot swap controller"
pmbus = { rails = [ "V54_HS_OUTPUT" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U452"

[[config.i2c.devices]]
bus = "rear"
address = 0x20
device = "max31790"
description = "Fan controller"
sensors = { speed = 6 }
refdes = "U321"

[[config.i2c.devices]]
bus = "rear"
address = 0x25
device = "tps546b24a"
description = "T6 power controller"
pmbus = { rails = [ "V0P96_NIC_VDD_A0HP" ] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "U565"

[[config.i2c.devices]]
bus = "rear"
address = 0x48
device = "tmp117"
name = "Northeast"
description = "Northeast temperature sensor"
sensors = { temperature = 1 }
removable = true
refdes = "J197"

[[config.i2c.devices]]
bus = "rear"
address = 0x49
device = "tmp117"
name = "North"
description = "North temperature sensor"
sensors = { temperature = 1 }
removable = true
refdes = "J198"

[[config.i2c.devices]]
bus = "rear"
address = 0x4a
device = "tmp117"
name = "Northwest"
description = "Northwest temperature sensor"
sensors = { temperature = 1 }
removable = true
refdes = "J199"

[[config.i2c.devices]]
bus = "rear"
address = 0x67
device = "bmr491"
name = "IBC"
description = "Intermediate bus converter"
pmbus = { rails = [ "V12_SYS_A2" ] }
sensors = { temperature = 1, power = 1, voltage = 1, current = 1 }
refdes = "U431"

################################################################################
# DIMM slots
[[config.i2c.devices]]
bus = "mid"
address = 0x18
device = "tse2004av"
name = "DIMM_A0"
description = "DIMM A0"
sensors = { temperature = 1 }
refdes = "M0"
removable = true

[[config.i2c.devices]]
bus = "mid"
address = 0x19
device = "tse2004av"
name = "DIMM_A1"
description = "DIMM A1"
sensors = { temperature = 1 }
refdes = "M8"
removable = true

[[config.i2c.devices]]
bus = "mid"
address = 0x1a
device = "tse2004av"
name = "DIMM_B0"
description = "DIMM B0"
sensors = { temperature = 1 }
refdes = "M1"
removable = true

[[config.i2c.devices]]
bus = "mid"
address = 0x1b
device = "tse2004av"
name = "DIMM_B1"
description = "DIMM B1"
sensors = { temperature = 1 }
refdes = "M9"
removable = true

[[config.i2c.devices]]
bus = "mid"
address = 0x1c
device = "tse2004av"
name = "DIMM_C0"
description = "DIMM C0"
sensors = { temperature = 1 }
refdes = "M2"
removable = true

[[config.i2c.devices]]
bus = "mid"
address = 0x1d
device = "tse2004av"
name = "DIMM_C1"
description = "DIMM C1"
sensors = { temperature = 1 }
refdes = "M10"
removable = true

[[config.i2c.devices]]
bus = "mid"
address = 0x1e
device = "tse2004av"
name = "DIMM_D0"
description = "DIMM D0"
sensors = { temperature = 1 }
refdes = "M3"
removable = true

[[config.i2c.devices]]
bus = "mid"
address = 0x1f
device = "tse2004av"
name = "DIMM_D1"
description = "DIMM D1"
sensors = { temperature = 1 }
refdes = "M11"
removable = true

[[config.i2c.devices]]
bus = "rear"
address = 0x18
device = "tse2004av"
name = "DIMM_E0"
description = "DIMM E0"
sensors = { temperature = 1 }
refdes = "M4"
removable = true

[[config.i2c.devices]]
bus = "rear"
address = 0x19
device = "tse2004av"
name = "DIMM_E1"
description = "DIMM E1"
sensors = { temperature = 1 }
refdes = "M12"
removable = true

[[config.i2c.devices]]
bus = "rear"
address = 0x1a
device = "tse2004av"
name = "DIMM_F0"
description = "DIMM F0"
sensors = { temperature = 1 }
refdes = "M5"
removable = true

[[config.i2c.devices]]
bus = "rear"
address = 0x1b
device = "tse2004av"
name = "DIMM_F1"
description = "DIMM F1"
sensors = { temperature = 1 }
refdes = "M13"
removable = true

[[config.i2c.devices]]
bus = "rear"
address = 0x1c
device = "tse2004av"
name = "DIMM_G0"
description = "DIMM G0"
sensors = { temperature = 1 }
refdes = "M6"
removable = true

[[config.i2c.devices]]
bus = "rear"
address = 0x1d
device = "tse2004av"
name = "DIMM_G1"
description = "DIMM G1"
sensors = { temperature = 1 }
refdes = "M14"
removable = true

[[config.i2c.devices]]
bus = "rear"
address = 0x1e
device = "tse2004av"
name = "DIMM_H0"
description = "DIMM H0"
sensors = { temperature = 1 }
refdes = "M7"
removable = true

[[config.i2c.devices]]
bus = "rear"
address = 0x1f
device = "tse2004av"
name = "DIMM_H1"
description = "DIMM H1"
sensors = { temperature = 1 }
refdes = "M15"
removable = true

################################################################################

[config.spi.spi2]
controller = 2

[config.spi.spi2.mux_options.port_i]
outputs = [
    {port = "I", pins = [1, 3], af = 5},
]
input = {port = "I", pin = 2, af = 5}

[config.spi.spi2.mux_options.port_b]
outputs = [
    {port = "B", pins = [13, 15], af = 5},
]
input = {port = "B", pin = 14, af = 5}

[config.spi.spi2.devices.sequencer]
mux = "port_b"
cs = [{port = "B", pin = 5}]

[config.spi.spi2.devices.ice40]
mux = "port_b"
cs = [{port = "B", pin = 5}]

[config.spi.spi2.devices.ksz8463]
mux = "port_i"
cs = [{port = "I", pin = 0}]

[config.spi.spi2.devices.local_flash]
mux = "port_b"
cs = [{port = "B", pin = 12}]

[config.spi.spi4]
controller = 4

[config.spi.spi4.mux_options.rot]
outputs = [
    {port = "E", pins = [2, 6], af = 5},
]
input = {port = "E", pin = 5, af = 5}

[config.spi.spi4.devices.rot]
mux = "rot"
cs = [{port = "E", pin = 4}]
clock_divider = "DIV16"

[config.net]
vlan = { start = 0x301, count = 2 }

[config.net.sockets.echo]
kind = "udp"
owner = {name = "udpecho", notification = 1}
port = 7
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.broadcast]
kind = "udp"
owner = {name = "udpbroadcast", notification = 1}
port = 997
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }
