[package]
name = "lpc55-iocon-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

[build-dependencies]
build-util = { path = "../../build/util" }

[lib]
proc-macro = true

[lints]
workspace = true
