[package]
name = "drv-ice40-spi-program"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
userlib = {path = "../../sys/userlib", default-features = false}
drv-spi-api = {path = "../spi-api"}
drv-stm32h7-gpio-api = {path = "../stm32h7-gpio-api"}

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"
