[package]
name = "drv-stm32h7-rcc"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
zerocopy = "0.3.0"
num-traits = { version = "0.2.12", default-features = false }
stm32h7 = { version = "0.13.0" }
cortex-m = { version = "0.7", features = ["inline-asm"] }

[features]
default = ["standalone"]
standalone = [ "h753" ]
h743 = ["stm32h7/stm32h743"]
h753 = ["stm32h7/stm32h753"]
h7b3 = ["stm32h7/stm32h7b3"]

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-stm32h7-rcc"
test = false
bench = false
