[package]
name = "task-validate"
version = "0.1.0"
edition = "2018"

[package.metadata.build]
target = "thumbv7em-none-eabihf"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
ringbuf = {path = "../../lib/ringbuf" }
drv-i2c-api = {path = "../../drv/i2c-api"}
cortex-m = {version = "0.7", features = ["inline-asm"]}
zerocopy = "0.6.1"
cfg-if = "1"
num-traits = { version = "0.2.12", default-features = false }
drv-i2c-devices = { path = "../../drv/i2c-devices" }
task-validate-api = {path = "../validate-api"}
idol-runtime = {git = "https://github.com/oxidecomputer/idolatry.git"}

[build-dependencies]
build-util = {path = "../../build/util"}
build-i2c = {path = "../../build/i2c"}
anyhow = "1.0.31"
cfg-if = "1"
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

[features]
itm = [ "userlib/log-itm" ]
semihosting = [ "userlib/log-semihosting" ]
h743 = ["build-i2c/h743"]
h753 = ["build-i2c/h753"]
h7b3 = ["build-i2c/h7b3"]
g031 = ["build-i2c/g031", "ringbuf/disabled"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-validate"
test = false
bench = false
