[package]
name = "task-net-api"
version = "0.1.0"
edition = "2021"

[features]
use-smoltcp = ["smoltcp"]

[dependencies]
derive-idol-err = {path = "../../lib/derive-idol-err" }
userlib = {path = "../../sys/userlib"}
serde = {version = "1", default-features = false, features = ["derive"]}
ssmarshal = {version = "1", default-features = false}
num-traits = {version = "0.2", default-features = false}
zerocopy = "0.6"

[dependencies.smoltcp]
version = "0.8.0"
optional = true
default-features = false

[build-dependencies]
build-net = {path = "../../build/net"}
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
bench = false
