[package]
name = "drv-oxide-vpd"
version = "0.1.0"
edition = "2021"

[dependencies]
tlvc = { workspace = true }
zerocopy = { workspace = true }

drv-i2c-api = { path = "../../drv/i2c-api" }
drv-i2c-devices = { path = "../../drv/i2c-devices" }
ringbuf = { path = "../../lib/ringbuf" }
