[package]
name = "drv-lpc55-rng"
version = "0.1.0"
authors = ["Steve Klabnik <steve.klabnik@oxide.computer>",]
edition = "2018"

[features]
default = ["standalone"]
standalone = []

[dependencies]
userlib = {path = "../../sys/userlib"}
zerocopy = "0.3.0"
lpc55-pac = "0.3.0"
num-traits = { version = "0.2.12", default-features = false }
drv-lpc55-syscon-api = {path = "../lpc55-syscon-api"}

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv8m.main-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-lpc55-rng"
test = false
bench = false
