[package]
edition = "2021"
readme = "README.md"
name = "demo-stm32f4-discovery"
version = "0.1.0"

[features]
itm = ["panic-itm"]
semihosting = ["panic-semihosting"]

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
panic-itm = { workspace = true, optional = true }
panic-halt = { workspace = true, optional = true }
panic-semihosting = { workspace = true, optional = true }
stm32f3 = { workspace = true, optional = true, features = ["stm32f303", "rt"] }
stm32f4 = { workspace = true, optional = true, features = ["stm32f407", "rt"] }

kern = { path = "../../sys/kern", default-features = false }

# this lets you use `cargo fix`!
[[bin]]
name = "demo-stm32f4-discovery"
test = false
bench = false
