[package]
edition = "2021"
readme = "README.md"
name = "demo-stm32f4-discovery"
version = "0.1.0"

[features]
dump = ["kern/dump"]

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
stm32f3 = { workspace = true, optional = true, features = ["stm32f303", "rt"] }
stm32f4 = { workspace = true, optional = true, features = ["stm32f407", "rt"] }

kern = { path = "../../sys/kern" }

# this lets you use `cargo fix`!
[[bin]]
name = "demo-stm32f4-discovery"
test = false
doctest = false
bench = false

[lints]
workspace = true
