[package]
name = "task-uartecho"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = { workspace = true }
cortex-m = { workspace = true }
heapless = { workspace = true }

drv-stm32h7-usart = { path = "../../drv/stm32h7-usart", optional = true }
ringbuf = { path = "../../lib/ringbuf" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
build-util = { path = "../../build/util" }

[features]
stm32h743 = ["drv-stm32h7-usart/h743"]
stm32h753 = ["drv-stm32h7-usart/h753"]
usart1 = []
usart2 = []
uart7 = []

hardware_flow_control = []

# we could expand this if needed; exactly one of these must be specified
baud_rate_115_200 = []
baud_rate_3M = []

[[bin]]
name = "task-uartecho"
test = false
doctest = false
bench = false
