[package]
name = "drv-sidecar-mainboard-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
drv-auxflash-api = {path = "../../drv/auxflash-api"}
drv-fpga-api = {path = "../../drv/fpga-api", features = ["auxflash"]}
userlib = {path = "../../sys/userlib"}
num-traits = { version = "0.2.12", default-features = false }
zerocopy = "0.6.1"

[build-dependencies]
build-fpga-regmap = {path = "../../build/fpga-regmap"}
build-util = {path = "../../build/util"}
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0"
gnarle = {path = "../../lib/gnarle", features=["std"]}
