[package]
name = "drv-sidecar-mainboard-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
bitfield = { workspace = true }
cfg-if = { workspace = true }
derive_more = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

drv-auxflash-api = { path = "../auxflash-api", optional = true }
drv-fpga-api = { path = "../fpga-api" }
drv-fpga-user-api = { path = "../fpga-user-api" }
drv-ignition-api = { path = "../ignition-api" }
ringbuf = { path = "../../lib/ringbuf" }
userlib = { path = "../../sys/userlib" }

[features]
bitstream = ["dep:drv-auxflash-api", "drv-fpga-api/auxflash"]
no-ipc-counters = ["idol/no-counters"]

[build-dependencies]
build-fpga-regmap = { path = "../../build/fpga-regmap" }
build-util = { path = "../../build/util" }
gnarle = { path = "../../lib/gnarle", features=["std"] }
idol = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lib]
test = false
doctest = false
bench = false

[lints]
workspace = true
