[package]
name = "drv-lpc55-gpio-api"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib"}
zerocopy = "0.3.0"
num-traits = { version = "0.2.12", default-features = false }
cfg-if = "0.1.10"

[build-dependencies]
build-util = {path = "../../build/util"}

[features]
default = ["standalone"]
standalone = []

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv8m.main-none-eabihf"

