[package]
name = "drv-cosmo-seq-server"
version = "0.1.0"
edition = "2021"

[dependencies]
drv-auxflash-api = { path = "../auxflash-api" }
drv-cpu-power-state = { path = "../cpu-power-state" }
counters = { path = "../../lib/counters" }
drv-cpu-seq-api = { path = "../cpu-seq-api" }
drv-hf-api = { path = "../hf-api" }
drv-i2c-api = { path = "../i2c-api", features = ["component-id"] }
drv-i2c-devices = { path = "../i2c-devices" }
drv-ice40-spi-program = { path = "../ice40-spi-program" }
drv-packrat-vpd-loader = { path = "../packrat-vpd-loader" }
drv-spartan7-loader-api = { path = "../spartan7-loader-api" }
drv-spi-api = { path = "../spi-api" }
drv-stm32xx-sys-api = { path = "../stm32xx-sys-api" }
fixedstr = { path = "../../lib/fixedstr", features = ["microcbor"] }
gnarle = { path = "../../lib/gnarle" }
ringbuf = { path = "../../lib/ringbuf" }
microcbor = { path = "../../lib/microcbor" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }
task-jefe-api = { path = "../../task/jefe-api" }
task-packrat-api = { path = "../../task/packrat-api", features = ["microcbor"] }
static-cell = { path = "../../lib/static-cell" }

cfg-if = { workspace = true }
idol-runtime.workspace = true
num-traits = { workspace = true }
pmbus = { workspace = true }
serde = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

[build-dependencies]
build-fpga-regmap = { path = "../../build/fpga-regmap" }
build-i2c = { path = "../../build/i2c" }
build-util = { path = "../../build/util" }
build-stm32xx-sys = { path = "../../build/stm32xx-sys" }
idol = { workspace = true }

[features]
h753 = ["drv-stm32xx-sys-api/h753"]
stay-in-a2 = []
enable-backplane-pcie-clk = []

[[bin]]
name = "drv-cosmo-seq-server"
test = false
doctest = false
bench = false

[lints]
workspace = true
