[package]
name = "drv-cosmo-hf"
version = "0.1.0"
edition = "2021"

[dependencies]
counters = { path = "../../lib/counters" }
drv-hash-api = { path = "../hash-api" }
drv-hf-api = { path = "../hf-api" }
drv-spartan7-loader-api = { path = "../spartan7-loader-api" }
ringbuf = { path = "../../lib/ringbuf" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }
drv-hf-fail-server = { path = "../hf-fail-server" }

cortex-m = { workspace = true }
idol-runtime = { workspace = true }
num-traits = { workspace = true }
stm32h7 = { workspace = true }
serde = { workspace = true }
hubpack = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

[build-dependencies]
build-util = { path = "../../build/util" }
build-fpga-regmap = { path = "../../build/fpga-regmap" }
idol = { workspace = true }

[[bin]]
name = "drv-cosmo-hf"
test = false
doctest = false
bench = false

[lints]
workspace = true
