[package]
name = "test-runner"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

[dependencies]
userlib = {path = "../userlib"}
cortex-m = "0.6.3"
zerocopy = "0.3.0"
num-traits = { version = "0.2.12", default-features = false }

[features]
default = ["standalone"]
standalone = []
itm = [ "userlib/log-itm" ]

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

[[bin]]
name = "test-runner"
test = false
bench = false
