[package]
name = "drv-stm32xx-i2c-server"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = { workspace = true }
cortex-m = { workspace = true }
num-traits = { workspace = true }
stm32g0 = { workspace = true }
stm32h7 = { workspace = true }

drv-i2c-api = { path = "../i2c-api" }
drv-stm32xx-i2c = { path = "../stm32xx-i2c"  }
drv-stm32xx-sys-api = { path = "../stm32xx-sys-api" }
fixedmap = { path = "../../lib/fixedmap" }
ringbuf = { path = "../../lib/ringbuf" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
anyhow = { workspace = true }
cfg-if = { workspace = true }

build-util = { path = "../../build/util" }
build-i2c = { path = "../../build/i2c" }

[features]
h743 = ["stm32h7/stm32h743", "drv-stm32xx-i2c/h743", "drv-stm32xx-sys-api/h743", "build-i2c/h743"]
h747cm7 = ["stm32h7/stm32h747cm7", "drv-stm32xx-i2c/h747cm7", "drv-stm32xx-sys-api/h747cm7", "build-i2c/h747cm7"]
h753 = ["stm32h7/stm32h753", "drv-stm32xx-i2c/h753", "drv-stm32xx-sys-api/h753", "build-i2c/h753"]
g031 = ["stm32g0/stm32g031", "drv-stm32xx-i2c/g031", "drv-stm32xx-sys-api/g031",
"build-i2c/g031", "ringbuf/disabled"]
itm = []

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-stm32xx-i2c-server"
test = false
bench = false
