[package]
name = "drv-gimlet-hf-api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-idol-err = {path = "../../lib/derive-idol-err" }
userlib = {path = "../../sys/userlib"}
num-traits = { version = "0.2.12", default-features = false }
zerocopy = "0.6.1"
drv-qspi-api = {path = "../qspi-api"}
drv-hash-api = {path = "../hash-api"}

[build-dependencies]
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}
