[package]
name = "task-udpbroadcast"
version = "0.1.0"
edition = "2021"

[features]
vlan = ["task-net-api/vlan"]
no-ipc-counters = ["idol/no-counters"]

[dependencies]
hubpack = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
ssmarshal = { workspace = true }
static_assertions = { workspace = true }
zerocopy = { workspace = true }

task-net-api = { path = "../net-api" }
task-packrat-api = { path = "../packrat-api" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
idol.workspace = true

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-udpbroadcast"
test = false
doctest = false
bench = false
