[package]
name = "lpc55-update-server"
version = "0.1.0"
edition = "2021"

[dependencies]
abi.path = "../../sys/abi"
drv-caboose.path = "../../drv/caboose"
drv-update-api.path = "../update-api/"
drv-lpc55-update-api.path = "../lpc55-update-api/"
ringbuf.path = "../../lib/ringbuf"
stage0-handoff.path = "../../lib/stage0-handoff"
# userlib = {path = "../../sys/userlib" }
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
drv-lpc55-flash.path = "../lpc55-flash"
drv-lpc55-sha256.path = "../lpc55-sha256"
drv-lpc55-syscon-api.path = "../lpc55-syscon-api"
sha3 = { workspace = true, optional = false }
task-jefe-api = { path = "../../task/jefe-api" }
mutable-statics = { path = "../../lib/mutable-statics" }

cfg-if.workspace = true
hubpack.workspace = true
hex-literal.workspace = true
idol-runtime.workspace = true
lpc55-pac.workspace = true
num-traits.workspace = true
serde.workspace = true
static_assertions.workspace = true
tlvc.workspace = true
zerocopy.workspace = true
zerocopy-derive.workspace = true

[build-dependencies]
build-util = { path = "../../build/util" }
idol = { workspace = true }

[features]
no-ipc-counters = ["idol/no-counters"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "lpc55-update-server"
test = false
doctest = false
bench = false

[lints]
workspace = true
