[package]
name = "task-jefe-api"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = { workspace = true }
serde = { workspace = true }
ssmarshal = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }
hubpack = { workspace = true }
humpty = { workspace = true }
derive-idol-err = { path = "../../lib/derive-idol-err" }
hubris-num-tasks = { path = "../../sys/num-tasks" }
userlib = { path = "../../sys/userlib" }
counters = { path = "../../lib/counters" }
dump-agent-api = { path = "../dump-agent-api" }
idol-runtime = { workspace = true }

[build-dependencies]
idol = { workspace = true }

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
doctest = false
bench = false

[lints]
workspace = true
