[package]
name = "task-jefe-api"
version = "0.1.0"
edition = "2021"

[dependencies]
derive-idol-err = {path = "../../lib/derive-idol-err" }
userlib = {path = "../../sys/userlib"}
num-traits = {version = "0.2", default-features = false}
serde = {version = "1", default-features = false, features = ["derive"]}
ssmarshal = {version = "1", default-features = false}
zerocopy = "0.6"

[build-dependencies]
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
bench = false
