[package]
name = "drv-lpc55-sprot-server"
version = "0.1.0"
edition = "2021"

[dependencies]
crc = { workspace = true }
hubpack = { workspace = true }
idol-runtime = { workspace = true }
lpc55-pac = { workspace = true }
num-traits = { workspace = true }
salty = { workspace = true }
sprockets-common = { workspace = true }
sprockets-rot = { workspace = true }
static_assertions = { workspace = true }
zerocopy = { workspace = true }

attest-api = { path = "../../task/attest-api" }
drv-lpc55-gpio-api = { path = "../lpc55-gpio-api" }
drv-lpc55-spi = { path = "../lpc55-spi" }
drv-lpc55-syscon-api = { path = "../lpc55-syscon-api" }
drv-lpc55-update-api = { path = "../lpc55-update-api" }
drv-sp-ctrl-api = { path = "../sp-ctrl-api" }
drv-sprot-api = { path = "../sprot-api" }
drv-update-api = { path = "../update-api" }
dumper-api = { path = "../../task/dumper-api" }
lpc55_romapi = { path = "../../lib/lpc55-romapi" }
ringbuf = { path = "../../lib/ringbuf" }
static-cell = { path = "../../lib/static-cell" }
task-jefe-api = { path = "../../task/jefe-api" }
userlib = { path = "../../sys/userlib" }
lpc55-rom-data = { path = "../../lib/lpc55-rom-data" }

[build-dependencies]
build-lpc55pins = { path = "../../build/lpc55pins" }
build-util = { path = "../../build/util" }
serde = { workspace = true }
quote = { workspace = true }
idol = { workspace = true }

[features]
spi0 = []
no-ipc-counters = ["idol/no-counters"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-lpc55-sprot-server"
test = false
doctest = false
bench = false
