[package]
name = "drv-gimlet-hf-server"
version = "0.1.0"
edition = "2021"

[dependencies]
idol-runtime = { workspace = true }
num-traits = { workspace = true }
stm32h7 = { workspace = true }
zerocopy = { workspace = true }

drv-gimlet-hf-api = { path = "../gimlet-hf-api" }
drv-hash-api = { path = "../hash-api" }
drv-stm32h7-qspi = { path = "../stm32h7-qspi" }
drv-stm32xx-sys-api = { path = "../stm32xx-sys-api" }
notifications = { path = "../../lib/notifications" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
build-util = {path = "../../build/util"}
idol = { workspace = true }

[features]
host_access = []
hash = []
h743 = ["stm32h7/stm32h743", "drv-stm32xx-sys-api/h743", "drv-stm32h7-qspi/h743"]
h753 = ["stm32h7/stm32h753", "drv-stm32xx-sys-api/h753", "drv-stm32h7-qspi/h753"]
