[package]
name = "drv-gimlet-hf-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
stm32h7 = { version = "0.13.0", default-features = false }
drv-stm32h7-rcc-api = {path = "../stm32h7-rcc-api", default-features = false}
drv-stm32h7-gpio-api = {path = "../stm32h7-gpio-api", default-features = false}
drv-stm32h7-qspi = {path = "../stm32h7-qspi", default-features = false}
cfg-if = "0.1.10"
num-traits = { version = "0.2.12", default-features = false }
drv-gimlet-hf-api = {path = "../gimlet-hf-api"}
cortex-m = { version = "0.7", features = ["inline-asm"] }
idol-runtime = {git = "https://github.com/oxidecomputer/idolatry.git"}
zerocopy = "0.6.1"

[build-dependencies]
build-util = {path = "../../build/util"}
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

[features]
default = ["standalone"]
standalone = ["h753"]
h743 = ["stm32h7/stm32h743", "drv-stm32h7-rcc-api/h743", "drv-stm32h7-qspi/h743"]
h753 = ["stm32h7/stm32h753", "drv-stm32h7-rcc-api/h753", "drv-stm32h7-qspi/h753"]

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"
