[package]
name = "drv-stm32h7-spi"
version = "0.1.0"
edition = "2018"

[dependencies]
ringbuf = {path = "../../lib/ringbuf"}
zerocopy = "0.6.1"
num-traits = { version = "0.2.12", default-features = false }
vcell = "0.1.2"
stm32h7 = { version = "0.14", default-features = false }

[features]
h743 = ["stm32h7/stm32h743"]
h753 = ["stm32h7/stm32h753"]
h7b3 = ["stm32h7/stm32h7b3"]
