[package]
name = "task-dump-agent"
version = "0.1.0"
edition = "2021"

[package.metadata.build]
target = "thumbv7em-none-eabihf"

[dependencies]
cfg-if = { workspace = true }
cortex-m = { workspace = true }
idol-runtime = { workspace = true }
num-traits = { workspace = true }
zerocopy = { workspace = true }
hubpack = { workspace = true }
serde = { workspace = true }
humpty = { workspace = true }
ringbuf = { path = "../../lib/ringbuf"  }
dump-agent-api = { path = "../dump-agent-api" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }
static_assertions = { workspace = true }
drv-sprot-api = { path = "../../drv/sprot-api" }
task-jefe-api = { path = "../../task/jefe-api" }

[features]
# Disable the SP-ROT communication, e.g. to run dump-agent on a Gimletlet
no-rot = []

[build-dependencies]
anyhow = { workspace = true }
cfg-if = { workspace = true }
idol = { workspace = true }

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-dump-agent"
test = false
bench = false
