[package]
name = "task-thermal"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags.workspace = true
cortex-m.workspace = true
idol-runtime.workspace = true
num-traits.workspace = true
serde.workspace = true
hubpack.workspace = true
zerocopy.workspace = true
zerocopy-derive.workspace = true

drv-cpu-seq-api = { path = "../../drv/cpu-seq-api", optional = true }
drv-front-io-api = { path = "../../drv/front-io-api", optional = true }
drv-sidecar-seq-api = { path = "../../drv/sidecar-seq-api", optional = true }
drv-transceivers-api = { path = "../../drv/transceivers-api", optional = true }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

drv-i2c-api.path = "../../drv/i2c-api"
drv-i2c-devices.path = "../../drv/i2c-devices"
drv-onewire-devices.path = "../../drv/onewire-devices"
drv-onewire.path = "../../drv/onewire"
counters.path = "../../lib/counters"
ringbuf.path = "../../lib/ringbuf"
static-cell.path = "../../lib/static-cell"
task-sensor-api.path = "../sensor-api"
task-thermal-api.path = "../thermal-api"

[build-dependencies]
anyhow = { workspace = true }
idol = { workspace = true }

build-i2c = { path = "../../build/i2c" }
build-util = { path = "../../build/util" }

[features]
gimlet = ["drv-cpu-seq-api", "h753"]
cosmo = ["drv-cpu-seq-api", "h753"]
sidecar = ["drv-sidecar-seq-api", "drv-front-io-api", "drv-transceivers-api", "h753"]
medusa = ["h753", "drv-transceivers-api"]
grapefruit = ["h753"]
minibar = ["h753"]
h743 = ["build-i2c/h743"]
h753 = ["build-i2c/h753"]
no-ipc-counters = ["idol/no-counters"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-thermal"
test = false
doctest = false
bench = false

[lints]
workspace = true
