[package]
name = "task-sensor-api"
version = "0.1.0"
edition = "2021"

[dependencies]
hubpack.workspace = true
idol-runtime.workspace = true
num-derive.workspace = true
num-traits.workspace = true
serde.workspace = true
zerocopy.workspace = true
zerocopy-derive.workspace = true

counters = { path = "../../lib/counters" }
drv-i2c-api.path = "../../drv/i2c-api"
derive-idol-err.path = "../../lib/derive-idol-err"
userlib.path = "../../sys/userlib"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
doctest = false
bench = false

[build-dependencies]
anyhow = { workspace = true }
idol = { workspace = true }
serde = { workspace = true }

build-i2c = { path = "../../build/i2c" }
build-util = { path = "../../build/util" }

[features]
h743 = ["build-i2c/h743"]
h753 = ["build-i2c/h753"]
# Include component ID strings in I2cDevice structs. This is necessary if
# `drv-i2c-api` is built with the `component-id` feature.
component-id = ["drv-i2c-api/component-id"]

[lints]
workspace = true
