name = "gemini-bu"
target = "thumbv7em-none-eabihf"
board = "gemini-bu-1"
chip = "../../chips/stm32h7"
stacksize = 896

[kernel]
name = "gemini-bu"
requires = {flash = 32768, ram = 8192}

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 4096}
start = true
stacksize = 2200
notifications = ["fault", "timer"]

[tasks.jefe.config.allowed-callers]
set_reset_reason = ["sys"]
request_reset = ["hiffy"]

[tasks.sys]
name = "drv-stm32xx-sys"
features = ["h753", "exti"]
priority = 1
max-sizes = {flash = 4096, ram = 2048}
uses = ["rcc", "gpios", "system_flash", "syscfg", "exti"]
start = true
task-slots = ["jefe"]
notifications = ["exti-wildcard-irq"]

[tasks.sys.interrupts]
"exti.exti0" = "exti-wildcard-irq"
"exti.exti1" = "exti-wildcard-irq"
"exti.exti2" = "exti-wildcard-irq"
"exti.exti3" = "exti-wildcard-irq"
"exti.exti4" = "exti-wildcard-irq"
"exti.exti9_5" = "exti-wildcard-irq"
"exti.exti15_10" = "exti-wildcard-irq"

[tasks.sys.config.gpio-irqs.rot_irq]
port = "E"
pin = 3
owner = {name = "sprot", notification = "rot_irq"}

[tasks.i2c_driver]
name = "drv-stm32xx-i2c-server"
stacksize = 1048
features = ["h753"]
priority = 2
uses = ["i2c1", "i2c3", "i2c4"]
start = true
notifications = ["i2c1-irq", "i2c3-irq", "i2c4-irq"]
task-slots = ["sys"]

[tasks.i2c_driver.interrupts]
"i2c1.event" = "i2c1-irq"
"i2c1.error" = "i2c1-irq"
"i2c3.event" = "i2c3-irq"
"i2c3.error" = "i2c3-irq"
"i2c4.event" = "i2c4-irq"
"i2c4.error" = "i2c4-irq"

[tasks.spi2_driver]
name = "drv-stm32h7-spi-server"
priority = 2
max-sizes = {flash = 16384, ram = 4096}
features = ["h753", "spi2"]
uses = ["spi2"]
start = true
notifications = ["spi-irq"]
interrupts = {"spi2.irq" = "spi-irq"}
stacksize = 880
task-slots = ["sys"]

[tasks.user_leds]
name = "drv-user-leds"
features = ["stm32h7"]
priority = 5
max-sizes = {flash = 2048, ram = 1024}
start = true
task-slots = ["sys"]
notifications = ["timer"]

[tasks.pong]
name = "task-pong"
priority = 8
max-sizes = {flash = 1024, ram = 1024}
start = true
task-slots = ["user_leds"]
notifications = ["timer"]

[tasks.hf]
name = "drv-mock-gimlet-hf-server"
features = ["h753", "hash"]
priority = 6
max-sizes = {flash = 16384, ram = 4096 }
stacksize = 2048
start = true
uses = ["quadspi"]
notifications = ["qspi-irq"]
interrupts = {"quadspi.irq" = "qspi-irq"}
task-slots = ["sys", "hash_driver"]

[tasks.hash_driver]
name = "drv-stm32h7-hash-server"
features = ["h753"]
priority = 5
max-sizes = {flash = 16384, ram=4096 }
stacksize = 2048
start = true
uses = ["hash"]
notifications = ["hash-irq"]
interrupts = {"hash.irq" = "hash-irq"}
task-slots = ["sys"]

[tasks.hiffy]
name = "task-hiffy"
features = ["h753", "stm32h7", "i2c", "gpio", "spi", "qspi", "hash", "sprot"]
priority = 7
max-sizes = {flash = 32768, ram = 16384 }
stacksize = 2048
start = true
task-slots = ["sys", "i2c_driver", "hf", "hash_driver", "sprot", "update_server"]

[tasks.sprot]
name = "drv-stm32h7-sprot-server"
priority = 5
max-sizes = {flash = 65536, ram = 32768}
stacksize = 4096
start = true
task-slots = ["sys"]
uses = ["spi4"]
features = ["use-spi-core", "h753", "spi4"]
notifications = ["spi-irq", "rot-irq", "timer"]
interrupts = {"spi4.irq" = "spi-irq"}

[tasks.validate]
name = "task-validate"
priority = 3
max-sizes = {flash = 8192, ram = 4096 }
stacksize = 1000
start = true
task-slots = ["i2c_driver"]

[tasks.idle]
name = "task-idle"
priority = 9
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[tasks.rng_driver]
features = ["h753"]
name = "drv-stm32h7-rng"
priority = 6
uses = ["rng"]
start = true
stacksize = 512
task-slots = ["sys", "user_leds"]

[tasks.update_server]
name = "stm32h7-update-server"
priority = 3
max-sizes = {flash = 16384, ram = 4096}
stacksize = 2048
start = true
uses = ["flash_controller"]
extern-regions = ["bank2"]
interrupts = {"flash_controller.irq" = "flash-irq"}
notifications = ["flash-irq"]

[config]
[[config.i2c.controllers]]
controller = 1

[config.i2c.controllers.ports.B]
name = "onboard"
scl.pin = 8
sda.pin = 9
af = 4

[[config.i2c.controllers]]
controller = 2
target = true

[config.i2c.controllers.ports.F]
scl.pin = 1
sda.pin = 0
af = 4

[[config.i2c.controllers]]
controller = 3

[config.i2c.controllers.ports.H]
scl.pin = 7
sda.pin = 8
af = 4

[[config.i2c.controllers]]
controller = 4

[config.i2c.controllers.ports.D]
scl.pin = 12
sda.pin = 13
af = 4

[config.i2c.controllers.ports.F]
scl.pin = 14
sda.pin = 15
af = 4

[[config.i2c.controllers.ports.F.muxes]]
driver = "ltc4306"
address = 0x44
enable = { port = "G", pin = 0 }

[config.i2c.controllers.ports.H]
scl.pin = 11
sda.pin = 12
af = 4

[[config.i2c.devices]]
device = "max31790"
bus = "onboard"
address = 0x20
description = "Fan controller"
refdes = "U701"

[[config.i2c.devices]]
device = "pca9555"
bus = "onboard"
address = 0x21
description = "GPIO expander"
refdes = "U1501"

[[config.i2c.devices]]
device = "ina219"
bus = "onboard"
address = 0x40
description = "Current sensor"
refdes = "U602"

[[config.i2c.devices]]
device = "ina219"
bus = "onboard"
address = 0x41
description = "Current sensor"
refdes = "U603"

[[config.i2c.devices]]
device = "ltc4306"
controller = 4
port = "F"
address = 0x44
description = "Multiplexer"
refdes = "U501"

#
# The following are devices for which Gemini BU has been or can be used as
# a development or evaluation vehicle
#
[[config.i2c.devices]]
device = "adm127x"
controller = 4
port = "F"
mux = 1
segment = 1
address = 0x10
description = "ADM1272 evaluation board"
power = { rails = [ "ADM_EVL_VOUT" ] }
refdes = "J501"

[[config.i2c.devices]]
device = "isl68224"
controller = 4
port = "F"
mux = 1
segment = 3
address = 0x60
description = "ISL68224 evaluation board"
power = { rails = [ "ISL_EVL_VOUT0", "ISL_EVL_VOUT1", "ISL_EVL_VOUT2" ] }
refdes = "J503"

[[config.i2c.devices]]
device = "tps546b24a"
controller = 4
port = "F"
mux = 1
segment = 4
address = 0x24
description = "TPS546B24A evaluation board"
power = { rails = [ "TPS_EVL_VOUT" ] }
refdes = "J504"

[config.spi.spi2]
controller = 2

[config.spi.spi2.mux_options.port_i]
outputs = [
    {port = "I", pins = [1, 3], af = 5},
]
input = {port = "I", pin = 2, af = 5}

[config.spi.spi2.devices.header]
mux = "port_i"
cs = [{port = "I", pin = 0}]


[config.spi.spi4]
controller = 4

[config.spi.spi4.mux_options.port_e]
outputs = [
    {port = "E", pins = [2, 6], af = 5},
]
input = {port = "E", pin = 5, af = 5}

[config.spi.spi4.devices.rot]
mux = "port_e"
cs = [{port = "E", pin = 4}]
clock_divider = "DIV256"
