name = "donglet-g031"
target = "thumbv6m-none-eabi"
chip = "../../chips/stm32g0"
memory = "memory-g031x8.toml"
board = "donglet-g031"

[kernel]
name = "app-donglet"
requires = {flash = 19168, ram = 1824}
features = ["g031"]
stacksize = 936

[tasks.jefe]
bin-crate = "task-jefe"
priority = 0
max-sizes = {flash = 4096, ram = 512}
start = true
stacksize = 384
notifications = ["fault", "timer"]
features = ["no-panic", "nano"]

[tasks.sys]
bin-crate = "drv-stm32xx-sys"
priority = 1
max-sizes = {flash = 2048, ram = 256}
uses = ["rcc", "gpio", "system_flash"]
start = true
features = ["g031", "no-ipc-counters"]
stacksize = 256
task-slots = ["jefe"]

[tasks.i2c_driver]
bin-crate = "drv-stm32xx-i2c-server"
features = ["g031", "no-ipc-counters"]
priority = 2
uses = ["i2c1"]
start = true
task-slots = ["sys"]
stacksize = 896
notifications = ["i2c1-irq"]

[tasks.i2c_driver.interrupts]
"i2c1.irq" = "i2c1-irq"

[tasks.validate]
bin-crate = "task-validate"
priority = 4
max-sizes = {flash = 8192, ram = 1024}
start = true
task-slots = ["sys", "i2c_driver"]
stacksize = 800
features = ["g031"]

[tasks.vpd]
bin-crate = "task-vpd"
priority = 4
max-sizes = {flash = 8192, ram = 1024}
start = true
task-slots = ["sys", "i2c_driver"]
stacksize = 800
features = ["g031", "tmp117-eeprom", "no-ipc-counters"]

[tasks.hiffy]
bin-crate = "task-hiffy"
priority = 4
max-sizes = {flash = 8192, ram = 2048}
start = true
task-slots = ["sys"]
stacksize = 912
features = ["stm32g0", "g031", "gpio", "micro", "send"]

[tasks.idle]
bin-crate = "task-idle"
priority = 5
max-sizes = {flash = 128, ram = 64}
stacksize = 64
start = true
features = ["insomniac"]

[config]
[[config.i2c.controllers]]
controller = 1

[config.i2c.controllers.ports.B]
scl.pin = 6
sda.pin = 9
af = 6

#
# This presumes that the VPD board is plugged into Donglet
#
[[config.i2c.controllers.ports.B.muxes]]
driver = "pca9548"
address = 0x73

[[config.i2c.devices]]
controller = 1
mux = 1
segment = 1
address = 0b1010_000
device = "at24csw080"
description = "Sharkfin VPD"
removable = true
refdes = ["J3", "J3", "U7"]

[[config.i2c.devices]]
controller = 1
mux = 1
segment = 2
address = 0b1010_000
device = "at24csw080"
description = "Gimlet Fan VPD"
removable = true
refdes = ["J3", "J5", "U1"]

[[config.i2c.devices]]
controller = 1
mux = 1
segment = 3
address = 0b1010_000
device = "at24csw080"
description = "Sidecar Fan VPD"
removable = true
refdes = ["J3", "J4", "U1"]

[[config.i2c.devices]]
controller = 1
mux = 1
segment = 4
address = 0x48
device = "tmp117"
description = "TempSense"
sensors = { temperature = 1 }
removable = true
refdes = ["J3", "J2"]
