[package]
name = "drv-stm32h7-hash-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
stm32h7 = { version = "0.14", default-features = false }
drv-stm32xx-sys-api = {path = "../stm32xx-sys-api", default-features = false}
drv-stm32h7-hash = {path = "../stm32h7-hash", default-features = false, optional = true}
cfg-if = "1"
num-traits = { version = "0.2.12", default-features = false }
drv-hash-api = {path = "../hash-api", default-features = false}
cortex-m = { version = "0.7", features = ["inline-asm"] }
idol-runtime = {git = "https://github.com/oxidecomputer/idolatry.git"}
zerocopy = "0.6.1"

[build-dependencies]
build-util = {path = "../../build/util"}
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

[features]
h753 = ["stm32h7/stm32h753", "drv-stm32xx-sys-api/h753", "drv-stm32h7-hash/h753"]
