[package]
name = "userlib"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

[features]
default = ["panic-messages"]
panic-messages = []

[dependencies]
abi = {path = "../abi"}
r0 = "1.0"

[lib]
test = false
bench = false

[build-dependencies]
serde = "1"
serde_json = "1"
