[package]
name = "userlib"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

[features]
default = ["panic-messages"]
panic-messages = []
log-itm = []
log-semihosting = []

[dependencies]
abi = {path = "../abi"}
serde = { version = "1.0.114", default-features = false }
ssmarshal = { version = "1.0.0", default-features = false }
zerocopy = "0.3.0"
num-traits = { version = "0.2.12", default-features = false }

#
# In order to use macros as discriminants in enums that make use of derive
# macros (e.g., AsBytes, FromPrimitive), we need the syn crate to have "full"
# enabled. The easiest way to do this is to use num-derive's "full-syntax",
# which passes "full" through to syn.
#
num-derive = { version = "0.3.0", features = [ "full-syntax" ] }

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

[lib]
test = false
bench = false
