[package]
name = "userlib"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

[features]
default = ["panic-messages"]
panic-messages = []
log-itm = []
log-semihosting = []

[dependencies]
abi = {path = "../abi"}
serde = { version = "1.0.114", default-features = false }
ssmarshal = { version = "1.0.0", default-features = false }
zerocopy = "0.3.0"
num-traits = { version = "0.2.12", default-features = false }
num-derive = "0.3.0"

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv7em-none-eabihf"

[lib]
test = false
bench = false
