[package]
name = "drv-stm32h7-qspi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stm32h7 = { version = "0.14", default-features = false }
vcell = "0.1.2"
zerocopy = "0.6.1"
userlib = {path = "../../sys/userlib"}

[features]
h743 = ["stm32h7/stm32h743"]
h753 = ["stm32h7/stm32h753"]
