[package]
name = "drv-stm32xx-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
drv-stm32xx-gpio-common = { path = "../stm32xx-gpio-common", features = ["server-support"] }
drv-stm32xx-sys-api = { path = "../stm32xx-sys-api" }
drv-stm32xx-uid = { path = "../../drv/stm32xx-uid" }
hubris-num-tasks = { path = "../../sys/num-tasks", features = ["task-enum"], optional = true }
task-jefe-api = { path="../../task/jefe-api" }
userlib = { path = "../../sys/userlib" }
counters = { path = "../../lib/counters", optional = true }

bitflags = { workspace = true }
cfg-if = { workspace = true }
idol-runtime = { workspace = true }
num-traits = { workspace = true }
stm32g0 = { workspace = true, optional = true }
stm32h7 = { workspace = true, optional = true }
stm32f4 = { workspace = true, optional = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

[build-dependencies]
idol = { workspace = true }
build-util = { path = "../../build/util" }
build-stm32xx-sys = { path = "../../build/stm32xx-sys" }

[features]
family-stm32h7 = ["stm32h7", "drv-stm32xx-uid/family-stm32h7"]
h743 = ["family-stm32h7", "stm32h7/stm32h743", "drv-stm32xx-sys-api/h743", "drv-stm32xx-gpio-common/model-stm32h743"]
h753 = ["family-stm32h7", "stm32h7/stm32h753", "drv-stm32xx-sys-api/h753", "drv-stm32xx-gpio-common/model-stm32h753"]

family-stm32g0 = ["stm32g0", "drv-stm32xx-uid/family-stm32g0"]
g030 = ["family-stm32g0", "stm32g0/stm32g030", "drv-stm32xx-sys-api/g030", "drv-stm32xx-gpio-common/model-stm32g030"]
g031 = ["family-stm32g0", "stm32g0/stm32g031", "drv-stm32xx-sys-api/g031", "drv-stm32xx-gpio-common/model-stm32g031"]
g070 = ["family-stm32g0", "stm32g0/stm32g070", "drv-stm32xx-sys-api/g070", "drv-stm32xx-gpio-common/model-stm32g070"]
g0b1 = ["family-stm32g0", "stm32g0/stm32g0b1", "drv-stm32xx-sys-api/g0b1", "drv-stm32xx-gpio-common/model-stm32g0b1"]

family-stm32f4 = ["stm32f4", "drv-stm32xx-uid/family-stm32f4"]
f407 = ["family-stm32f4", "stm32f4/stm32f407", "drv-stm32xx-sys-api/f407", "drv-stm32xx-gpio-common/model-stm32f407"]
f429 = ["family-stm32f4", "stm32f4/stm32f429", "drv-stm32xx-sys-api/f429", "drv-stm32xx-gpio-common/model-stm32f429"]

no-ipc-counters = ["idol/no-counters"]
no-panic = ["userlib/no-panic"]

# Enable external interrupt controller support.
exti = ["dep:hubris-num-tasks", "dep:counters"]

# Disables the Jefe dependency, for use in tests where the test-runner task is
# used as supervisor, rather than Jefe.
#
# TODO(eliza): eventually, it would be much better if tasks that depend on the
# sys driver could run separately from the kernel tests, and use a real Jefe
# rather than the test supervisor. But, for now, this makes it build.
test = []

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-stm32xx-sys"
test = false
doctest = false
bench = false

[lints]
workspace = true
