[package]
name = "abi"
version = "0.1.0"
edition = "2021"

[dependencies]
zerocopy = { workspace = true, features = ["derive"] }
bitflags = { workspace = true }
byteorder = { workspace = true }
serde = { workspace = true }
phash = { path = "../../lib/phash" }

[lints]
workspace = true
