[package]
name = "task-template"
version = "0.1.0"
authors = ["Your Name Here <anonymous@oxide.computer>"]
edition = "2018"

[dependencies]
userlib = {path = "../userlib"}

[features]
default = ["standalone"]
standalone = []

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-template"
test = false
bench = false
