[package]
name = "task-host-sp-comms"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = { workspace = true }
corncobs = { workspace = true }
cortex-m = { workspace = true }
enum-map = { workspace = true }
heapless = { workspace = true }
idol-runtime = { workspace = true }
num-traits = { workspace = true }
zerocopy = { workspace = true }

drv-gimlet-hf-api = { path = "../../drv/gimlet-hf-api" }
drv-gimlet-seq-api = { path = "../../drv/gimlet-seq-api" }
drv-stm32h7-usart = { path = "../../drv/stm32h7-usart", optional = true }
drv-stm32xx-sys-api = { path = "../../drv/stm32xx-sys-api" }
host-sp-messages = { path = "../../lib/host-sp-messages" }
multitimer = { path = "../../lib/multitimer" }
mutable-statics = { path = "../../lib/mutable-statics" }
notifications = { path = "../../lib/notifications" }
ringbuf = { path = "../../lib/ringbuf" }
task-control-plane-agent-api = { path = "../control-plane-agent-api" }
task-host-sp-comms-api = { path = "../host-sp-comms-api" }
task-net-api = { path = "../net-api" }
userlib = { path = "../../sys/userlib" }

[build-dependencies]
build-util = { path = "../../build/util" }
idol = { workspace = true }

[features]
stm32h743 = ["drv-stm32h7-usart/h743", "drv-stm32xx-sys-api/h743"]
stm32h753 = ["drv-stm32h7-usart/h753", "drv-stm32xx-sys-api/h753"]
uart7 = []
baud_rate_3M = []
hardware_flow_control = []
vlan = ["task-net-api/vlan"]

[[bin]]
name = "task-host-sp-comms"
test = false
bench = false
