[package]
name = "task-host-sp-comms"
version = "0.1.0"
edition = "2018"

[dependencies]
cfg-if = "1"
corncobs = "0.1.1"
cortex-m = {version = "0.7", features = ["inline-asm"]}
heapless = "0.7.16"
num-traits = { version = "0.2.12", default-features = false }
zerocopy = "0.6.1"

drv-stm32h7-usart = {path = "../../drv/stm32h7-usart", optional = true}
drv-gimlet-hf-api = {path = "../../drv/gimlet-hf-api"}
drv-gimlet-seq-api = {path = "../../drv/gimlet-seq-api"}
host-sp-messages = {path = "../../lib/host-sp-messages"}
mutable-statics = {path = "../../lib/mutable-statics"}
ringbuf = {path = "../../lib/ringbuf"}
task-host-sp-comms-api = {path = "../host-sp-comms-api"}
userlib = {path = "../../sys/userlib"}

idol-runtime = {git = "https://github.com/oxidecomputer/idolatry.git"}

[build-dependencies]
build-util = {path = "../../build/util"}
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

[features]
stm32h743 = ["drv-stm32h7-usart/h743"]
stm32h753 = ["drv-stm32h7-usart/h753"]
uart7 = []
baud_rate_3M = []
hardware_flow_control = []

[[bin]]
name = "task-host-sp-comms"
test = false
bench = false
