[package]
name = "task-host-sp-comms"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if.workspace = true
corncobs.workspace = true
cortex-m.workspace = true
enum-map.workspace = true
heapless.workspace = true
hubpack.workspace = true
idol-runtime.workspace = true
num-traits.workspace = true
paste.workspace = true
static_assertions.workspace = true
zerocopy.workspace = true

tlvc = { workspace = true, optional = true }
pmbus = { workspace = true, optional = true }

counters.path = "../../lib/counters"

drv-gimlet-hf-api.path= "../../drv/gimlet-hf-api"
drv-gimlet-seq-api.path= "../../drv/gimlet-seq-api"
drv-oxide-vpd.path= "../../drv/oxide-vpd"
drv-stm32h7-dbgmcu.path = "../../drv/stm32h7-dbgmcu"
drv-stm32xx-sys-api.path= "../../drv/stm32xx-sys-api"
host-sp-messages.path= "../../lib/host-sp-messages"
multitimer.path= "../../lib/multitimer"
mutable-statics.path= "../../lib/mutable-statics"
oxide-barcode.path = "../../lib/oxide-barcode"
ringbuf.path= "../../lib/ringbuf"
task-control-plane-agent-api.path= "../control-plane-agent-api"
task-host-sp-comms-api.path = "../host-sp-comms-api"
task-net-api.path= "../net-api"
task-packrat-api.path= "../packrat-api"
userlib.path= "../../sys/userlib"

drv-i2c-api = { path = "../../drv/i2c-api", optional = true }
drv-spi-api = { path = "../../drv/spi-api", optional = true }
drv-i2c-devices = { path = "../../drv/i2c-devices", optional = true }
drv-stm32h7-usart = { path = "../../drv/stm32h7-usart", optional = true }
task-sensor-api = { path = "../../task/sensor-api", optional = true }
ksz8463 = { path = "../../drv/ksz8463", optional = true }

[build-dependencies]
build-util.path = "../../build/util"
build-i2c = { path = "../../build/i2c", optional = true }
idol.workspace = true

[features]
stm32h743 = ["drv-stm32h7-usart/h743", "drv-stm32xx-sys-api/h743", "drv-stm32h7-dbgmcu/h743"]
stm32h753 = ["drv-stm32h7-usart/h753", "drv-stm32xx-sys-api/h753", "drv-stm32h7-dbgmcu/h753"]
uart7 = []
baud_rate_3M = []
hardware_flow_control = []
vlan = ["task-net-api/vlan"]
gimlet = ["pmbus", "tlvc", "drv-i2c-api", "drv-i2c-devices", "drv-spi-api", "ksz8463", "build-i2c", "task-sensor-api"]

[[bin]]
name = "task-host-sp-comms"
test = false
doctest = false
bench = false
