[package]
name = "drv-packrat-vpd-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
drv-local-vpd.path = "../local-vpd"
oxide-barcode.path = "../../lib/oxide-barcode"
ringbuf.path = "../../lib/ringbuf"
task-packrat-api.path = "../../task/packrat-api"
userlib.path = "../../sys/userlib"

[lib]
test = false
doctest = false
bench = false
