[package]
name = "drv-stm32h7-usart"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

[dependencies]
userlib = {path = "../../userlib"}
zerocopy = "0.3.0"
num-traits = { version = "0.2.12", default-features = false }
drv-stm32h7-gpio-api = {path = "../stm32h7-gpio-api"}
drv-stm32h7-rcc-api = {path = "../stm32h7-rcc-api"}

[dependencies.stm32h7]
git = "https://github.com/oxidecomputer/stm32-rs-nightlies"

[features]
default = ["standalone", "h7b3"]
standalone = []
h7b3 = ["stm32h7/stm32h7b3"]
h743 = ["stm32h7/stm32h743"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-stm32h7-usart"
test = false
bench = false
