[package]
name = "task-caboose-reader"
description = "tiny task to read from the caboose with Idol APIs"
version = "0.1.0"
authors = ["Matt Keeter <matt@oxide.computer>"]
edition = "2021"

[dependencies]
cfg-if.workspace = true
idol-runtime.workspace = true
num-traits.workspace = true
tlvc.workspace = true
zerocopy.workspace = true

derive-idol-err.path = "../../lib/derive-idol-err"
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
build-util = { path = "../../build/util" }
idol = { workspace = true }
