[package]
name = "drv-transceivers-server"
version = "0.1.0"
authors = ["Aaron Hartwig <aaron@oxide.computer>"]
edition = "2021"

[dependencies]
drv-fpga-api = { path = "../fpga-api" }
drv-i2c-api = { path = "../i2c-api" }
drv-i2c-devices = { path = "../i2c-devices" }
drv-sidecar-front-io = { path = "../sidecar-front-io", features = ["transceivers", "leds"] }
drv-sidecar-seq-api = { path = "../sidecar-seq-api" }
drv-transceivers-api = { path = "../transceivers-api" }
multitimer = { path = "../../lib/multitimer" }
mutable-statics = { path = "../../lib/mutable-statics" }
ringbuf = { path = "../../lib/ringbuf" }
task-net-api = { path = "../../task/net-api" }
task-sensor-api = { path = "../../task/sensor-api" }
task-thermal-api = { path = "../../task/thermal-api" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

cfg-if = { workspace = true }
enum-map = { workspace = true }
hubpack = { workspace = true }
idol-runtime = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
ssmarshal = { workspace = true }
stm32h7 = { workspace = true }
transceiver-messages = { workspace = true }
zerocopy = { workspace = true }

[features]
vlan = ["task-net-api/vlan"]

[build-dependencies]
build-util = { path = "../../build/util" }
build-i2c = { path = "../../build/i2c" }

idol = { workspace = true }

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-transceivers-server"
test = false
bench = false
