[package]
name = "drv-lpc55-i2c"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
zerocopy = "0.3.0"
lpc55-pac = "0.3.0"
drv-lpc55-syscon-api = {path = "../lpc55-syscon-api"}
num-traits = { version = "0.2.12", default-features = false }
drv-lpc55-gpio-api = {path = "../lpc55-gpio-api"}

[features]
default = ["standalone"]
standalone = []

# a target for `cargo xtask check`
[package.metadata.build]
target = "thumbv8m.main-none-eabihf"

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-lpc55-i2c"
test = false
bench = false
